const B=(en,ar)=>[en,ar];
const SCENARIO_VERSION='1.0.0';
const CHAPTERS=[B('Meet & identify','التعارف والهوية'),B('Assess','التقييم'),B('Make care safe','تهيئة رعاية آمنة'),B('Prevent a fall','منع السقوط'),B('Medication safety','سلامة الدواء'),B('Urgent change','تغير عاجل'),B('Reassess & record','إعادة التقييم والتوثيق'),B('Safe handover','التسليم الآمن')];
const PAIN=[
 ['location',B('Where does it hurt?','أين تشعر بالألم؟'),B('Across my lower abdomen, around the operation site.','أسفل بطني، حول موضع العملية.')],
 ['onset',B('When did it start? Has it changed?','متى بدأ؟ وهل تغير؟'),B('Since the operation yesterday. It is worse when I move.','منذ العملية أمس. ويزيد عندما أتحرك.')],
 ['quality',B('What does the pain feel like?','كيف تصف طبيعة الألم؟'),B('An ache, with a sharper pain when I cough.','وجع مستمر، يصبح حاداً عندما أسعل.')],
 ['severity',B('How strong is it, from 0 to 10?','ما شدته من 0 إلى 10؟'),B('Seven. Zero is no pain and ten is the worst pain I can imagine.','سبعة. الصفر يعني عدم وجود ألم والعشرة أشد ألم أستطيع تصوره.')],
 ['factors',B('What makes it worse or helps?','ما الذي يزيد الألم أو يخففه؟'),B('Moving and coughing hurt. Keeping still helps a little.','الحركة والسعال يزيدانه. والراحة تخففه قليلاً.')],
 ['associated',B('Anything else worrying you?','هل تشعر بشيء آخر يقلقك؟'),B('I feel dizzy when I try to sit up. I need the bathroom.','أشعر بالدوار عندما أحاول الجلوس. وأحتاج إلى الحمام.')]
];
const VITALS=[['bp','BP',B('Blood pressure','ضغط الدم'),'104/66','mmHg'],['hr','HR',B('Pulse','النبض'),'96','/min'],['rr','RR',B('Respiratory rate','معدل التنفس'),'20','/min'],['spo2','SpO₂',B('Oxygen saturation','تشبع الأكسجين'),'97','% · room air'],['temp','T',B('Temperature','الحرارة'),'37.2','°C']];
const CHART=[
 ['procedure',B('Operation & history','العملية والتاريخ'),B('Khaled Salem · DOB 12 March 1968 · Record TU-SIM-204. Day 1 after colon resection. Fictional training patient. Awake and communicating.','خالد سالم · الميلاد 12 مارس 1968 · الملف TU-SIM-204. اليوم الأول بعد استئصال جزء من القولون. مريض افتراضي للتدريب. واعٍ وقادر على التواصل.')],
 ['allergies',B('Allergy record','سجل الحساسية'),B('Admission form: “No known allergies” ticked. Reconciliation signature is blank. Confirm the history directly with Khaled; a ticked box can be wrong.','استمارة الدخول: تم اختيار «لا توجد حساسية معروفة». توقيع مراجعة الحساسية غير موجود. تأكد من خالد مباشرة؛ قد تكون العلامة في الاستمارة غير صحيحة.')],
 ['orders',B('Medication order','الأمر الدوائي'),B('Oral analgesia is requested. The photocopied dose is unreadable; the administration record must also be checked. This copy is not a complete usable order. Do not guess a dose.','المطلوب مسكن فموي. الجرعة في الصورة الورقية غير مقروءة؛ ويجب مراجعة سجل إعطاء الأدوية أيضاً. هذه النسخة ليست أمراً مكتملاً يمكن العمل به. لا تخمّن الجرعة.')],
 ['mobility',B('Mobility & supervision','الحركة والإشراف'),B('First postoperative mobilisation: assess tolerance and arrange assistance. Student Ahmed works with the registered nurse. Dizziness requires review before walking.','أول تحريك بعد العملية: قيّم تحمل الحركة ورتّب المساعدة. يعمل الطالب أحمد تحت إشراف الممرض المسؤول. الدوار يستدعي المراجعة قبل المشي.')]
];
const C=(id,text,why,opts={})=>({id,text,why,...opts});
const NODES={
 hand:{title:B('Clean hands','نظافة اليدين'),body:B('Your hands are not visibly soiled. You are about to make routine patient contact. Choose your action.','يداك غير متسختين بشكل ظاهر. أنت على وشك ملامسة المريض للرعاية المعتادة. اختر الإجراء.'),choices:[
 C('rub',B('Use alcohol hand rub; cover all surfaces until dry','استخدم مطهراً كحولياً وغطِّ كل أسطح اليدين حتى تجفا'),B('For this contact, clean hands reduce transfer of organisms. Repeat hand hygiene at the appropriate moments; one action at the door does not cover the whole visit. If visibly soiled, use soap and water.','تقلل نظافة اليدين انتقال الميكروبات. كررها في الأوقات المناسبة؛ مرة واحدة عند الباب لا تكفي طوال الزيارة. استخدم الماء والصابون عند وجود اتساخ ظاهر.'),{flag:'hand'}),
 C('gloves',B('Put on gloves and skip hand hygiene','ارتدِ القفازات دون تنظيف اليدين'),B('Gloves do not replace hand hygiene. Choose gloves for the exposure risk and clean hands at the relevant moments.','القفازات لا تحل محل نظافة اليدين. اخترها حسب خطر التعرض ونظف يديك في الأوقات المناسبة.'),{severity:'learning'}),
 C('skip',B('Start touching the patient immediately','ابدأ بملامسة المريض مباشرة'),B('Pause before routine contact and clean your hands. This is a missed infection-prevention step, not a reason to delay life-saving emergency help.','توقف قبل الملامسة المعتادة ونظف يديك. هذه خطوة للوقاية من العدوى، وليست سبباً لتأخير المساعدة المنقذة للحياة.'),{severity:'learning'})]},
 intro:{title:B('Meet Khaled','التعارف مع خالد'),quote:B('Are you the nurse? My stomach hurts.','هل أنت الممرض؟ بطني يؤلمني.'),body:B('You are Ahmed, a student nurse working with the registered nurse.','أنت أحمد، طالب تمريض تعمل مع الممرض المسؤول.'),choices:[
 C('introduce',B('Introduce yourself, explain your student role, ask permission and protect privacy','عرّف بنفسك ودورك كطالب، واستأذن واحفظ الخصوصية'),B('Khaled agrees. Clear role, consent and privacy support safe communication. He now understands that you work under supervision.','وافق خالد. وضوح الدور والاستئذان والخصوصية تدعم التواصل الآمن. أصبح يعرف أنك تعمل تحت الإشراف.'),{flag:'intro'}),
 C('start',B('Start the examination without speaking','ابدأ الفحص دون حديث'),B('For routine care, explain what you will do and seek permission. Do not describe yourself as a registered nurse when you are a student.','في الرعاية المعتادة، اشرح ما ستفعله واستأذن. لا تقدم نفسك كممرض مسجل وأنت طالب.'),{severity:'learning'})]},
 identity:{title:B('Match two identifiers','طابق معرفين للهوية'),body:B('Ask Khaled to state his full name and date of birth. He says: “Khaled Salem, 12 March 1968.” His wristband and chart both show the same details, record TU-SIM-204.','اطلب من خالد أن يذكر اسمه الكامل وتاريخ ميلاده. يقول: «خالد سالم، 12 مارس 1968». السوار والملف يحملان البيانات نفسها ورقم TU-SIM-204.'),choices:[
 C('match',B('Compare the stated name and date of birth with wristband and chart','طابق الاسم وتاريخ الميلاد المصرّح بهما مع السوار والملف'),B('Both identifiers match. Room or bed number is a location, not a patient identifier. If details differ, resolve the discrepancy before routine patient-specific care.','تطابق المعرفان. رقم الغرفة أو السرير يحدد المكان وليس هوية المريض. عند الاختلاف، عالج التعارض قبل الرعاية المعتادة الخاصة بالمريض.'),{flag:'identity'}),
 C('leading',B('Ask only: “You are Khaled, right?”','اسأل فقط: «أنت خالد، صحيح؟»'),B('A patient may agree to a leading question. Ask the patient to state identifying details and compare two approved identifiers.','قد يوافق المريض على سؤال موجّه. اطلب منه ذكر بياناته وطابق معرفين معتمدين.'),{severity:'learning'}),
 C('bednumber',B('Use Bed 4 as confirmation','استخدم رقم السرير 4 للتأكيد'),B('Beds and rooms can change. This does not establish identity.','يمكن أن يتغير السرير أو الغرفة؛ وهذا لا يثبت الهوية.'),{severity:'learning'})]},
 interpretation:{title:B('What do the findings mean?','ماذا تعني النتائج؟'),body:B('Khaled reports pain 7/10 and dizziness on sitting. Baseline: BP 104/66, HR 96, RR 20, SpO₂ 97% on room air, T 37.2°C.','يشكو خالد من ألم 7/10 ودوار عند الجلوس. القياسات الأولية: ضغط 104/66، نبض 96، تنفس 20، تشبع 97% بهواء الغرفة، حرارة 37.2°C.'),requires:'baseline',choices:[
 C('recognise',B('Keep him supported; tell the nurse about dizziness before mobilisation','أبقِه مدعوماً وأبلغ الممرض بالدوار قبل التحريك'),B('One acceptable-looking observation does not cancel a symptom. Combine symptoms, trends, surgery and the environment when judging fall risk.','لا تلغي قراءة تبدو مقبولة وجود عرض مهم. اجمع الأعراض والاتجاهات وحالة ما بعد العملية والبيئة عند تقدير خطر السقوط.'),{flag:'interpret'}),
 C('dismiss',B('The oxygen reading is normal, so he can walk alone','التشبع طبيعي، إذن يمكنه المشي وحده'),B('Oxygen saturation does not measure balance or postural tolerance. Dizziness needs assessment and supervision.','تشبع الأكسجين لا يقيس التوازن أو تحمل تغيير الوضع. الدوار يحتاج إلى تقييم وإشراف.'),{severity:'learning'})]},
 floor:{title:B('Inspect the walking surface','افحص مسار المشي'),body:B('There is a wet patch beside the bed, on the likely path to the bathroom.','توجد بقعة ماء قرب السرير في المسار المتوقع إلى الحمام.'),choices:[
 C('secure',B('Keep Khaled safe, restrict the wet area and arrange prompt cleaning','حافظ على أمان خالد، امنع المرور على البلل ورتّب تنظيفه سريعاً'),B('The area is cleaned and dry in the simulated care record. Do not leave an unsteady patient alone to fetch cleaning equipment. Clean your hands after environmental contact.','أصبح المسار نظيفاً وجافاً في سجل المحاكاة. لا تترك مريضاً غير متزن وحده لجلب أدوات التنظيف. نظف يديك بعد ملامسة البيئة.'),{flag:'floor'}),
 C('stepover',B('Tell him to step over it','اطلب منه تخطي البلل'),B('That leaves the hazard in place and adds a balance challenge for a dizzy patient. Control the hazard before walking.','يبقى الخطر قائماً وتزداد صعوبة التوازن لدى مريض يشعر بالدوار. عالج الخطر قبل المشي.'),{severity:'learning'})]},
 bed:{title:B('Inspect the bed','افحص السرير'),body:B('The bed is higher than its safe resting position and one brake is not engaged.','السرير أعلى من وضع الراحة الآمن وإحدى الفرامل غير مثبتة.'),choices:[
 C('secure',B('Engage brakes; lower to a safe resting height and plan transfer height with the nurse','ثبّت الفرامل، اخفضه إلى ارتفاع راحة آمن واتفق مع الممرض على ارتفاع النقل'),B('The simulated bed is now secured. Resting height and transfer height may differ. Side rails require individual assessment; raising all rails is not an automatic fall-prevention solution.','أصبح السرير مثبتاً في المحاكاة. قد يختلف ارتفاع الراحة عن ارتفاع النقل. الحواجز الجانبية تحتاج إلى تقييم فردي؛ رفعها كلها ليس حلاً تلقائياً لمنع السقوط.'),{flag:'bed'}),
 C('rails',B('Raise every side rail and leave the brakes as they are','ارفع كل الحواجز واترك الفرامل كما هي'),B('Rails do not secure the bed and may create other risks. Address the brake and bed height directly.','الحواجز لا تثبت السرير وقد تنشئ مخاطر أخرى. عالج الفرامل والارتفاع مباشرة.'),{severity:'learning'})]},
 bell:{title:B('Call bell & belongings','جرس النداء والمتعلقات'),body:B('The call bell is on the cabinet, outside Khaled’s comfortable reach.','جرس النداء على الخزانة، بعيداً عن متناول خالد المريح.'),choices:[
 C('place',B('Place the bell within reach; ask Khaled to demonstrate how to call','ضع الجرس في متناوله واطلب منه توضيح طريقة النداء'),B('Khaled demonstrates using the bell. Explain that he should call and wait for help before getting up. Recheck reach at the end of care.','أظهر خالد كيفية استخدام الجرس. وضّح له أن يطلب المساعدة وينتظر قبل النهوض. أعد التحقق من وصوله للجرس في نهاية الرعاية.'),{flag:'bell'}),
 C('tell',B('Tell him to shout if needed','اطلب منه الصراخ عند الحاجة'),B('A reachable and usable call bell gives him a reliable way to request assistance.','يوفر الجرس القريب والقابل للاستخدام وسيلة موثوقة لطلب المساعدة.'),{severity:'learning'})]},
 shoes:{title:B('Footwear','الحذاء'),body:B('Loose slippers are beside the bed. They fit poorly and have smooth soles.','شبشب واسع قرب السرير، غير ثابت ونعله أملس.'),choices:[
 C('replace',B('Arrange secure, well-fitting non-slip footwear before walking','وفّر حذاءً ثابتاً مناسب المقاس ومانعاً للانزلاق قبل المشي'),B('Footwear is corrected in the scenario. This is one part of a wider fall-prevention plan; it does not remove dizziness.','تم توفير الحذاء المناسب في السيناريو. هذه خطوة ضمن خطة منع السقوط، ولا تعالج الدوار.'),{flag:'shoes'}),
 C('slippers',B('Use the loose slippers; it is only a short walk','استخدم الشبشب الواسع؛ المسافة قصيرة'),B('A short distance still presents a fall risk, particularly with dizziness and tubing.','حتى المسافة القصيرة تحمل خطر السقوط، خاصة مع الدوار والأنابيب.'),{severity:'learning'})]},
 iv:{title:B('Inspect the IV line','افحص الخط الوريدي'),body:B('A section of tubing could catch on the bed during movement. The visible site has no swelling or redness.','قد يعلق جزء من الأنبوب بالسرير أثناء الحركة. الموضع الظاهر لا يبدو متورماً أو محمراً.'),choices:[
 C('trace',B('Trace patient-to-source, check the site and secure slack without disconnecting','تتبّع الخط من المريض إلى المصدر وافحص الموضع ورتّب الأنبوب دون فصله'),B('The line is clear of the transfer route and the pole is stable. Visual inspection does not require opening the system. Do not change a prescribed flow rate on your own.','أصبح الخط بعيداً عن مسار النقل والحامل ثابتاً. الفحص البصري لا يتطلب فتح النظام. لا تغيّر معدل التسريب الموصوف من تلقاء نفسك.'),{flag:'iv'}),
 C('disconnect',B('Disconnect it to make walking easier','افصل الأنبوب لتسهيل المشي'),B('Unnecessary disconnection risks contamination and interrupts treatment. Stop and seek supervision rather than disconnecting. No line has been disconnected in this simulation.','الفصل غير الضروري قد يسبب تلوثاً ويوقف العلاج. اطلب الإشراف بدلاً من الفصل. لم يُفصل أي خط في المحاكاة.'),{severity:'critical'})]},
 gloves:{title:B('Prepare for a dressing task','الاستعداد للعناية بالضماد'),body:B('A supervisor asks how you would prepare for a dressing task with possible body-fluid exposure. This is a preparation decision, not an instruction to remove Khaled’s dressing now.','يسألك المشرف عن الاستعداد للعناية بضماد مع احتمال التعرض لسوائل الجسم. هذا قرار استعداد، وليس أمراً بإزالة ضماد خالد الآن.'),choices:[
 C('prepare',B('Clean hands; select task-appropriate PPE and aseptic technique; clean hands after glove removal','نظف اليدين واختر الوقاية وتقنية منع التلوث المناسبتين، ثم نظفهما بعد نزع القفازات'),B('Match protection to the task and exposure. Avoid touching clean supplies with contaminated gloves. Glove type and the dressing procedure follow local policy.','اختر الوقاية وفق المهمة والتعرض. تجنب لمس المستلزمات النظيفة بقفازات ملوثة. نوع القفاز وطريقة العناية بالضماد يتبعان السياسة المحلية.'),{flag:'gloves'}),
 C('reuse',B('Use the gloves already worn while cleaning the floor','استخدم القفازات التي ارتديتها لتنظيف الأرض'),B('Environmental contamination must not be carried to a clean or aseptic task. Remove gloves, clean hands and prepare fresh appropriate protection.','يجب عدم نقل تلوث البيئة إلى مهمة نظيفة. انزع القفازات ونظف اليدين وجهّز الوقاية المناسبة.'),{severity:'critical'})]},
 equipment:{title:B('Inspect the power lead','افحص التوصيل الكهربائي'),body:B('On closer inspection, the extension lead has damaged insulation. It supplies a non-essential charger, not life-support equipment.','بالفحص القريب، يبدو عازل وصلة الكهرباء تالفاً. وهي تغذي شاحناً غير أساسي وليست موصولة بجهاز داعم للحياة.'),choices:[
 C('isolate',B('Prevent use, keep people clear, and report for safe isolation by authorised staff','امنع استخدامها وأبعد الأشخاص وأبلغ لعزلها بأمان بواسطة المختصين'),B('The charger is taken out of service in the scenario. Do not touch damaged wiring or repair it yourself; clinical equipment support follows local procedures.','أُخرج الشاحن من الخدمة في السيناريو. لا تلمس الأسلاك التالفة ولا تصلحها بنفسك؛ اتبع الإجراء المحلي للمعدات.'),{flag:'equipment'}),
 C('use',B('Use it briefly; the charger still works','استخدمها قليلاً؛ الشاحن لا يزال يعمل'),B('Functioning equipment can still be electrically unsafe. The attempted use is stopped and recorded for debrief.','قد تعمل المعدات مع بقائها خطرة كهربائياً. أُوقفت محاولة الاستخدام وسُجلت للمراجعة.'),{severity:'critical'})]},
 oxygen:{title:B('Oxygen & fire safety','الأكسجين والسلامة من الحريق'),body:B('Khaled’s baseline SpO₂ is 97% on room air. The wall outlet is available, but oxygen is not currently prescribed or clinically required in this baseline scene.','تشبع خالد الأولي 97% بهواء الغرفة. مخرج الأكسجين متاح، لكن الأكسجين غير موصوف ولا يحتاجه في هذا المشهد الأولي.'),choices:[
 C('safe',B('Leave oxygen off; keep ignition sources away and know the emergency procedure','اترك الأكسجين مغلقاً وأبعد مصادر الاشتعال واعرف إجراء الطوارئ'),B('Use oxygen for a clinical indication with appropriate targets and local protocols. If the patient deteriorates, call for urgent help and follow emergency guidance; do not delay emergency treatment for routine paperwork.','يُستخدم الأكسجين لاستطباب مع أهداف وبروتوكولات مناسبة. عند التدهور، اطلب مساعدة عاجلة واتبع إرشادات الطوارئ؛ لا تؤخر العلاج العاجل بسبب أوراق روتينية.'),{flag:'oxygen'}),
 C('automatic',B('Turn oxygen on for every postoperative patient','افتح الأكسجين لكل مريض بعد العملية'),B('Oxygen is a treatment with indications and targets, not an automatic comfort measure.','الأكسجين علاج له استطبابات وأهداف، وليس إجراءً تلقائياً للراحة.'),{severity:'learning'})]},
 mobility:{title:B('“I can walk by myself.”','«أستطيع المشي وحدي»'),quote:B('I need the bathroom now. I will be quick.','أحتاج إلى الحمام الآن. لن أتأخر.'),choices:[
 C('assist',B('Keep him supported, arrange nurse review and assisted toileting appropriate to his tolerance','أبقِه مدعوماً ورتّب مراجعة الممرض ومساعدة مناسبة لتحمله في قضاء الحاجة'),B('Because he is dizzy, walking is deferred. The nurse assists with a safe bedside alternative after assessment. Environmental preparation supports care; it does not make an unwell patient fit to walk.','بسبب الدوار أُجّل المشي. يساعد الممرض في بديل آمن بجانب السرير بعد التقييم. تهيئة البيئة تدعم الرعاية لكنها لا تجعل المريض المتوعك قادراً على المشي.'),{flag:'mobility',requires:'mobility',effect:'mobilitySafe'}),
 C('alone',B('Let Khaled walk alone','اسمح لخالد بالمشي وحده'),B('Khaled becomes unsteady as he rises. He has not fallen. Respond immediately to this near miss.','يفقد خالد اتزانه أثناء النهوض. لم يسقط. استجب فوراً لهذا الحدث الوشيك.'),{severity:'critical',effect:'nearFall',go:'nearfall'}),
 C('walk',B('Start walking him before assessment and preparation','ابدأ المشي به قبل التقييم والتهيئة'),B('Symptoms and the transfer environment need review first. He becomes unsteady; respond now.','الأعراض وبيئة النقل تحتاجان للمراجعة أولاً. أصبح غير متزن؛ استجب الآن.'),{severity:'critical',effect:'nearFall',go:'nearfall'})]},
 nearfall:{title:B('Near fall: act now','سقوط وشيك: تصرف الآن'),quote:B('Wait… I feel faint.','انتظر… أشعر أنني سأغيب عن الوعي.'),body:B('Khaled is unsteady beside the bed. Do not leave him unsupported.','خالد غير متزن بجانب السرير. لا تتركه دون دعم.'),choices:[
 C('support',B('Stay, summon help within reach, stop the transfer and assist a safe supported position with help','ابقَ واطلب المساعدة من مكانك وأوقف النقل وساعده مع الفريق إلى وضع مدعوم آمن'),B('The nurse arrives; Khaled returns safely to a supported position. No injury is apparent. Reassess symptoms, inform the supervisor and address the contributing hazards. Avoid unsafe lifting or trying to catch his full weight alone.','وصل الممرض وعاد خالد إلى وضع مدعوم آمن، دون إصابة ظاهرة. أعد التقييم وأبلغ المشرف وعالج العوامل المساهمة. تجنب الرفع غير الآمن أو محاولة حمل وزنه كاملاً وحدك.'),{flag:'fallRecovered',effect:'recoverFall'}),
 C('leave',B('Leave him standing to find a nurse','اتركه واقفاً وابحث عن الممرض'),B('Leaving an unstable patient unsupported adds immediate risk. Stay with him and summon assistance.','ترك مريض غير متزن دون دعم يضيف خطراً فورياً. ابقَ معه واستدعِ المساعدة.'),{severity:'critical'})]},
 allergy:{title:B('Ask about allergies','اسأل عن الحساسية'),quote:B('A penicillin injection once made my lips swell and breathing difficult.','حقنة بنسلين سببت لي مرة تورماً في الشفتين وصعوبة في التنفس.'),body:B('This conflicts with the admission form’s “No known allergies” box. The analgesic has not been given.','يتعارض ذلك مع اختيار «لا توجد حساسية معروفة» في استمارة الدخول. لم يُعطَ المسكن.'),choices:[
 C('escalate',B('Record the reported drug and reaction; alert the nurse to reconcile the record','سجل الدواء والتفاعل المبلغ عنهما وأبلغ الممرض لمراجعة السجل'),B('The nurse verifies and updates the allergy record in the scenario. Do not infer that every analgesic is contraindicated; reconcile the specific history before the responsible clinician confirms the plan.','تحقق الممرض وحدّث سجل الحساسية في السيناريو. لا تستنتج أن كل المسكنات ممنوعة؛ راجع التاريخ المحدد قبل تأكيد الخطة بواسطة المختص.'),{flag:'allergy'}),
 C('ignore',B('Use the ticked box and ignore his account','اعتمد العلامة في الاستمارة وتجاهل كلامه'),B('A discrepancy between the patient’s history and the chart must be resolved. A prefilled box is not stronger evidence than an unreviewed reported reaction.','يجب حل التعارض بين تاريخ المريض والملف. الخانة المعبأة لا تبرر تجاهل تفاعل دوائي لم يُراجع.'),{severity:'critical'})]},
 medication:{title:B('An incomplete medication order','أمر دوائي غير مكتمل'),body:B('Khaled asks for pain relief. The dose on the photocopied order cannot be read. You must not infer it from a previous patient or a usual dose.','يطلب خالد تسكين الألم. الجرعة في نسخة الأمر غير مقروءة. لا تستنتجها من مريض سابق أو من جرعة معتادة.'),choices:[
 C('hold',B('Hold preparation and ask the nurse/prescriber for a complete verified order','أوقف التحضير واطلب من الممرض/الواصف أمراً مكتملاً ومتحققاً منه'),B('The discrepancy is intercepted before administration. A legible, authorised order is obtained in the simulated handover. Continue with checks and supervision; this module does not teach a drug dose.','اكتُشف التعارض قبل الإعطاء. جرى الحصول على أمر مقروء ومعتمد في التسليم الافتراضي. تابع التحقق والإشراف؛ هذه الوحدة لا تعلّم جرعة دوائية.'),{flag:'medhold'}),
 C('give',B('Give the usual dose now','أعطِ الجرعة المعتادة الآن'),B('The attempted administration is stopped. An unreadable dose is an unresolved order, even if identity and other checks are complete. Escalate instead of guessing.','أُوقفت محاولة الإعطاء. الجرعة غير المقروءة تعني أمراً لم يُحسم، حتى لو اكتملت الهوية والفحوص الأخرى. أبلغ بدلاً من التخمين.'),{severity:'critical'})]},
 medchecks:{title:B('Recheck before supervised care','أعد التحقق قبل الرعاية بإشراف'),body:B('The responsible nurse has obtained the corrected order. What must still be checked at the point of care?','حصل الممرض المسؤول على الأمر المصحح. ما الذي لا يزال يجب التحقق منه عند الرعاية؟'),requires:'medhold',choices:[
 C('checks',B('Match patient, allergies, drug, dose, route, time/last dose and indication; explain and check the record with the nurse','طابق المريض والحساسية والدواء والجرعة والطريق والوقت/آخر جرعة والاستطباب، واشرح وراجع السجل مع الممرض'),B('Checks are repeated against the authorised order and administration record. Consent, relevant observations, supervision and recording actual administration also matter. Do not sign for an unperformed action.','تُكرر المطابقة مع الأمر المعتمد وسجل الإعطاء. كذلك تُراعى الموافقة والملاحظات المهمة والإشراف وتسجيل الإعطاء الفعلي. لا توقّع على إجراء لم يتم.'),{flag:'medchecks'}),
 C('trust',B('Skip the checks because the nurse has already looked','تجاوز التحقق لأن الممرض راجع بالفعل'),B('A corrected order does not remove the need for point-of-care checks and communication.','تصحيح الأمر لا يلغي التحقق عند تقديم الرعاية والتواصل.'),{severity:'learning'})]},
 interruption:{title:B('An interruption','مقاطعة أثناء التحضير'),quote:B('Ahmed, can you quickly check Bed 5?','أحمد، هل يمكنك فحص السرير 5 بسرعة؟'),body:B('This is described as a routine request while the medication process is underway. An actual emergency would take priority with a safe handover.','هذا طلب روتيني أثناء عملية تحضير الدواء. أما الطوارئ الحقيقية فلها الأولوية مع تسليم آمن.'),requires:'medchecks',choices:[
 C('pause',B('Secure the preparation, clarify urgency, hand over if needed and restart the relevant checks on return','أمّن التحضير وحدد الاستعجال وسلّم المهمة عند الحاجة وأعد التحقق المناسب عند العودة'),B('The routine request is delegated. The responsible nurse resumes only after the checks are repeated. A pause should not turn into an assumed completed step.','وُجّه الطلب الروتيني لزميل. استأنف الممرض بعد تكرار التحقق. التوقف لا يعني أن الخطوة اكتملت.'),{flag:'interruption'}),
 C('multitask',B('Continue preparation while discussing Bed 5','واصل التحضير وأنت تناقش حالة السرير 5'),B('Divided attention makes missed or duplicated checks more likely. Make the pause explicit and resume deliberately.','تشتت الانتباه يزيد احتمال تجاوز التحقق أو تكراره. اجعل التوقف واضحاً واستأنف بوعي.'),{severity:'learning'})]},
 comfort:{title:B('Supervised pain care','رعاية الألم تحت الإشراف'),body:B('The nurse has completed the verified medication process. Khaled consents. You can assist with comfort and learn what needs reassessment.','أكمل الممرض عملية الدواء المتحقق منها ووافق خالد. يمكنك المساعدة في الراحة وتحديد ما يلزم إعادة تقييمه.'),requires:'interruption',choices:[
 C('care',B('Assist comfortable positioning; the nurse gives authorised analgesia and records the actual time','ساعده على وضع مريح؛ يعطي الممرض المسكن المعتمد ويسجل الوقت الفعلي'),B('Simulated time 09:15: the registered nurse administers and records analgesia after the checks. Plan reassessment based on the intervention and local policy, with earlier review for any deterioration.','الوقت الافتراضي 09:15: أعطى الممرض المسكن وسجله بعد التحقق. خطط لإعادة التقييم وفق التدخل والسياسة المحلية، وبصورة أبكر عند أي تدهور.'),{flag:'comfort'})]},
 sharps:{title:B('Sharps disposal checkpoint','محطة التخلص من الأدوات الحادة'),body:B('Separate skills checkpoint: after a simulated needle procedure, a used needle remains in your control. The container is within reach and below its fill line. Khaled’s analgesia was oral; this is not an extra injection.','محطة مهارية منفصلة: بعد إجراء افتراضي بإبرة، تظل الإبرة المستخدمة تحت سيطرتك. الحاوية قريبة ودون حد الامتلاء. مسكن خالد كان فموياً؛ هذه ليست حقنة إضافية.'),choices:[
 C('dispose',B('Activate the safety feature as trained and dispose directly into the sharps container','فعّل آلية الأمان حسب التدريب وتخلص منها مباشرة في حاوية الأدوات الحادة'),B('Use the designated sharps container immediately; do not routinely recap or leave the sharp on a tray. Do not overfill the container.','استخدم الحاوية المخصصة فوراً؛ لا تعِد تغطية الإبرة روتينياً ولا تتركها على صينية. لا تملأ الحاوية فوق الحد.'),{flag:'sharps'}),
 C('recap',B('Recap the used needle with both hands','أعد تغطية الإبرة المستعملة بكلتا اليدين'),B('The attempted action is stopped: two-handed recapping can expose the hand to a needlestick. Dispose safely without routine recapping.','أُوقفت المحاولة: إعادة التغطية باليدين قد تعرض اليد للوخز. تخلص من الإبرة بأمان دون إعادة تغطية روتينية.'),{severity:'critical'}),
 C('tray',B('Leave it on the tray for someone else','اتركها على الصينية لشخص آخر'),B('An exposed sharp transfers the risk to another person. Immediate safe disposal is part of the procedure.','الأداة الحادة المكشوفة تنقل الخطر لشخص آخر. التخلص الآمن الفوري جزء من الإجراء.'),{severity:'critical'})]},
 urgent:{title:B('Khaled is deteriorating','حالة خالد تتدهور'),quote:B('I feel much worse… it is harder to breathe.','أشعر أنني أسوأ بكثير… التنفس أصبح أصعب.'),body:B('At simulated 09:20 he becomes pale and clammy. New observations: BP 86/52, HR 120, RR 28, SpO₂ 92% on room air. The cause is not established. Do not assume pain, the medication, or anxiety explains it.','عند 09:20 الافتراضية أصبح شاحباً ومتعرقاً. القياسات الجديدة: ضغط 86/52، نبض 120، تنفس 28، تشبع 92% بهواء الغرفة. السبب لم يُحدد. لا تفترض أن الألم أو الدواء أو القلق يفسره.'),choices:[
 C('urgenthelp',B('Stay with him, activate urgent clinical help and begin ABCDE within your training','ابقَ معه واستدعِ المساعدة السريرية العاجلة وابدأ ABCDE ضمن تدريبك'),B('Urgent help is activated immediately. Keep him supported, monitor, and assist emergency care under local protocols and supervision. Routine sequence, documentation and identification tasks must not delay urgent care.','استُدعيت المساعدة العاجلة فوراً. حافظ على دعمه وراقبه وساعد في الرعاية الطارئة وفق البروتوكولات والإشراف. لا تؤخر الرعاية العاجلة بسبب التسلسل الروتيني أو التوثيق أو الهوية.'),{flag:'escalated'}),
 C('wait',B('Finish the routine note before calling','أكمل الملاحظة الروتينية قبل النداء'),B('These new findings demand urgent assessment. Documentation can follow or occur alongside care by another team member; it must not postpone help.','هذه النتائج الجديدة تستدعي تقييماً عاجلاً. يمكن التوثيق لاحقاً أو بالتوازي بواسطة زميل؛ يجب ألا يؤخر المساعدة.'),{severity:'critical'}),
 C('painonly',B('Give more analgesia and wait for it to work','أعطِ مزيداً من المسكن وانتظر تأثيره'),B('Do not treat this change as pain alone or give additional medication independently. Escalate now and support assessment.','لا تعتبر التغير ألماً فقط ولا تعطِ دواءً إضافياً بشكل مستقل. اطلب المساعدة الآن وساند التقييم.'),{severity:'critical'})]},
 sbar:{title:B('Give a focused SBAR handover','قدّم تسليماً منظماً باستخدام SBAR'),body:B('Urgent help is on its way. Which handover gives the team actionable information?','المساعدة العاجلة في الطريق. أي تسليم يعطي الفريق معلومات قابلة للعمل؟'),requires:'escalated',choices:[
 C('complete',B('Identify yourself and patient; report the acute change, operation, vital-sign trend, care given and request immediate bedside review','عرّف بنفسك وبالمريض واذكر التغير والعملية واتجاه العلامات والرعاية المقدمة واطلب مراجعة فورية بجانب السرير'),B('Situation: acute deterioration. Background: day 1 after colon resection. Assessment: pale, clammy, breathless; BP 104/66 → 86/52, HR 96 → 120, RR 20 → 28, SpO₂ 97% → 92% on air. Recommendation: urgent bedside review; confirm the message was received.','الحالة: تدهور حاد. الخلفية: اليوم الأول بعد استئصال جزء من القولون. التقييم: شحوب وتعرق وضيق نفس، ضغط 104/66 ← 86/52، نبض 96 ← 120، تنفس 20 ← 28، تشبع 97% ← 92% بهواء الغرفة. التوصية: مراجعة عاجلة وتأكيد استلام الرسالة.'),{flag:'sbar'}),
 C('vague',B('Say only: “Bed 4 does not look good.”','قل فقط: «حالة السرير 4 لا تبدو جيدة»'),B('That communicates concern but omits identity, urgency and evidence. Add the specific change and a clear request; do not wait to collect every detail before the first urgent call.','ينقل ذلك القلق لكنه يحذف الهوية والاستعجال والدليل. أضف التغير المحدد والطلب الواضح؛ لا تنتظر كل التفاصيل قبل النداء العاجل الأول.'),{severity:'learning'})]},
 reassess:{title:B('Reassess after team review','أعد التقييم بعد مراجعة الفريق'),body:B('At simulated 09:35 the clinical team has reviewed and started a management plan. Repeat observations are BP 108/68, HR 94, RR 20, SpO₂ 96% on the team’s prescribed oxygen. Khaled is alert, less dizzy, and reports pain 4/10. This scripted improvement follows team care; clicking “call” alone did not treat him.','عند 09:35 الافتراضية راجع الفريق الحالة وبدأ خطة تدبير. القياسات المتكررة: ضغط 108/68، نبض 94، تنفس 20، تشبع 96% على الأكسجين الذي وصفه الفريق. خالد واعٍ وأقل دواراً ويبلغ عن ألم 4/10. هذا التحسن الافتراضي بعد رعاية الفريق؛ الضغط على «طلب المساعدة» وحده لا يعالجه.'),requires:'sbar',choices:[
 C('compare',B('Compare symptoms and observations with baseline; confirm the continuing monitoring plan','قارن الأعراض والقياسات بالخط الأساسي وأكد خطة المراقبة المستمرة'),B('Record the response and oxygen context, not just the new pain score. The team retains clinical responsibility and sets review frequency. Improvement does not mean monitoring can stop.','سجل الاستجابة وسياق الأكسجين، وليس درجة الألم فقط. يحتفظ الفريق بالمسؤولية السريرية ويحدد تكرار المراجعة. التحسن لا يعني إيقاف المراقبة.'),{flag:'reassess'}),
 C('leave',B('Pain is lower, so no more review is needed','انخفض الألم، فلا حاجة لمزيد من المراجعة'),B('Pain is only one observation. After acute deterioration, ongoing monitoring and a clear care plan are essential.','الألم ملاحظة واحدة فقط. بعد التدهور الحاد، تلزم مراقبة مستمرة وخطة واضحة.'),{severity:'learning'})]},
 report:{title:B('Report the intercepted risk','بلّغ عن الخطر الذي جرى منعه'),body:B('The incomplete medication order was intercepted before administration. If your attempt also included a near fall, include that event separately.','اكتُشف الأمر الدوائي غير المكتمل قبل الإعطاء. إن تضمنت محاولتك سقوطاً وشيكاً فأدرج ذلك كحدث منفصل.'),requires:'medhold',choices:[
 C('report',B('Inform the supervisor, record clinical facts and complete the local near-miss reporting process','أبلغ المشرف ووثق الحقائق السريرية وأكمل إجراء الإبلاغ المحلي عن الأحداث الوشيكة'),B('A no-harm event can still reveal a system weakness. Use objective facts and the local reporting route. The patient record and the incident report serve different purposes; follow local policy for each.','قد يكشف الحدث دون ضرر عن ضعف في النظام. استخدم الحقائق والإجراء المحلي. للسجل السريري وتقرير الحادث غرضان مختلفان؛ اتبع سياسة كل منهما.'),{flag:'report'}),
 C('nothing',B('Nothing happened, so do not report','لم يحدث ضرر، فلا تبلّغ'),B('No injury does not mean there was no risk. Learning from intercepted errors can prevent future harm.','غياب الإصابة لا يعني غياب الخطر. التعلم من الأخطاء التي مُنعت قد يحول دون ضرر لاحق.'),{severity:'learning'}),
 C('blame',B('Write that the previous nurse was careless','اكتب أن الممرض السابق كان مهملاً'),B('Document what you observed and what was done. Blame and unsupported assumptions do not explain the safety problem reliably.','وثق ما لاحظته وما فُعل. اللوم والافتراضات غير المدعومة لا يفسران المشكلة بموثوقية.'),{severity:'learning'})]},
 exit:{title:B('Before you leave','قبل المغادرة'),body:B('The registered nurse has accepted ongoing care. Complete a final check with Khaled.','تسلّم الممرض المسؤول الرعاية المستمرة. أكمل الفحص الأخير مع خالد.'),requires:'finish',choices:[
 C('handover',B('Recheck bed, brakes, bell, pathway and comfort; confirm monitoring and who is staying with him','أعد فحص السرير والفرامل والجرس والمسار والراحة، وأكد المراقبة ومن سيبقى معه'),B('Khaled can reach the bell and knows to wait for help. The receiving nurse confirms the monitoring plan. A deteriorating or unstable patient must not be left without appropriate care.','يصل خالد إلى الجرس ويعرف أنه ينتظر المساعدة. أكد الممرض المتسلم خطة المراقبة. لا يُترك مريض متدهور أو غير مستقر دون الرعاية المناسبة.'),{flag:'exit'}),
 C('walkout',B('Leave because the documentation is finished','غادر لأن التوثيق انتهى'),B('Completed paperwork does not establish a safe environment or transfer clinical responsibility. Check and hand over.','اكتمال الأوراق لا يثبت أمان البيئة ولا ينقل المسؤولية السريرية. تحقق وسلّم الرعاية.'),{severity:'learning'})]},
 exitHand:{title:B('Clean hands on leaving','نظف يديك عند المغادرة'),body:B('You have finished patient and surrounding-environment contact and removed any gloves.','انتهيت من ملامسة المريض وبيئته ونزعت القفازات إن استُخدمت.'),requires:'exit',choices:[
 C('clean',B('Perform hand hygiene','نفّذ نظافة اليدين'),B('This completes the simulated visit. Review the decisions and the reasons behind them in your debrief.','اكتملت الزيارة الافتراضية. راجع قراراتك وأسبابها في جلسة المراجعة.'),{flag:'exitHand'})]}
};
const OBJECTS=[
 ['patient',B('Khaled','خالد'),.517,.456,'intro'],['monitor',B('Observations','القياسات'),.397,.433,'vitals'],['iv',B('IV line','الخط الوريدي'),.421,.347,'iv'],['hand',B('Hand hygiene','نظافة اليدين'),.084,.413,'hand'],['chart',B('Clinical chart','الملف السريري'),.895,.556,'chart'],['medication',B('Medication tray','صينية الدواء'),.930,.524,'medication'],['floor',B('Floor','الأرضية'),.377,.703,'floor'],['bed',B('Bed controls','ضبط السرير'),.623,.823,'bed'],['shoes',B('Footwear','الحذاء'),.462,.790,'shoes'],['bell',B('Call bell','جرس النداء'),.597,.470,'bell'],['sharps',B('Sharps container','حاوية الأدوات الحادة'),.907,.414,'sharps'],['gloves',B('PPE','الوقاية الشخصية'),.948,.401,'gloves'],['equipment',B('Power lead','وصلة الكهرباء'),.931,.882,'equipment'],['oxygen',B('Oxygen outlet','مخرج الأكسجين'),.560,.397,'oxygen'],['door',B('Handover & leave','التسليم والمغادرة'),.232,.436,'exit']
];
const SOURCES=[
 ['WHO · Hand hygiene','https://www.who.int/campaigns/world-hand-hygiene-day'],
 ['CDC · Safe injection practices','https://www.cdc.gov/injection-safety/hcp/clinical-guidance/index.html'],
 ['Resuscitation Council UK · ABCDE approach','https://www.resus.org.uk/library/abcde-approach']
];
