(() => {
'use strict';
const R=window.QUALITY_CYCLE_REFERENCE;
const $=(s)=>document.querySelector(s);
const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='nursing-quality-cycle-demo-v1', QMS='tobruk-qms-prototype-v01';
const stages=['received','assigned','reviewed','preview_approved'];
const stageNames={received:'وصلت فكرة افتراضية',assigned:'مرتبطة بمهمة تجريبية',reviewed:'مراجعة تنفيذ تجريبية',preview_approved:'معاينة مجازة تجريبيًا — لم تُنشر'};
let tab=['updates','calendar','transparency','continuity','demo'].includes(location.hash.slice(1))?location.hash.slice(1):'updates';
let source=null,sourceError='',feed=null,feedError='',actor='quality',storageOK=true;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch{storageOK=false;return fallback;}}
let state=read(KEY,{schemaVersion:1,cases:[],events:[]});
if(state.schemaVersion!==1||!Array.isArray(state.cases)||!Array.isArray(state.events))state={schemaVersion:1,cases:[],events:[]};
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{storageOK=false;notice('التخزين المحلي غير متاح؛ لم نحفظ التغيير. لا تدخل بيانات حقيقية.');return false;}}
function event(action,id){state.events.push({at:new Date().toISOString(),actor,action,id});write(KEY,state);}
function notice(message){const box=$('#status');box.textContent=message;box.style.display='block';clearTimeout(notice.timer);notice.timer=setTimeout(()=>box.style.display='none',5000);}
function sc(id){return R.demoScenarios.find(s=>s.id===id);}
function qs(){return read(QMS,null);}
function taskFor(c){return qs()?.tasks?.find(t=>t.id===c.taskId);}
function sourceTasks(){return Array.isArray(source?.tasks)?source.tasks:[];}
function formatDate(date){const d=new Date(date);return Number.isNaN(d.getTime())?String(date||'غير محدد'):d.toLocaleString('ar-LY');}
function download(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function headerInfo(){return `<div class="path"><span>بوابة الكلية: جمع الرأي</span><span>الجودة: فرز وتحليل</span><span>الخطة: مهمة ومسؤول</span><span>التنفيذ: مخرج موثق</span><span>الاعتماد: شاهد يُراجع</span><span>للطلبة: استجابة آمنة</span></div>`;}
function updates(){
 const items=(feed?.items||[]).filter(x=>x&&x.approvedOn&&x.approvalRef&&x.id&&x.theme);
 return headerInfo()+`<section class="card"><h2>نتائج مجمعة واستجابات معلنة</h2><p>هذا القسم مخصص للملخصات التي أُجيز نشرها، وليس لملفات الاستبانات الخام. نعرض موضوع الملاحظة والاستجابة وحالتها وما سنراجعه لاحقًا.</p><div class="row"><a class="btn" href="https://forms.gle/1SRA82yXSH1QpRkz5" target="_blank" rel="noopener noreferrer">الشكاوى والملاحظات — النموذج الموجود</a><button data-go="demo">شاهد مثالًا افتراضيًا للربط</button></div><small>النموذج الموجود خدمة خارجية؛ هذه الصفحة لا تستقبل ردوده تلقائيًا. الربط المؤسسي المحمي لم يُفعّل بعد. الملاحظات المفتوحة لا تُعامل كعينة استطلاع ممثلة لجميع الطلبة.</small></section>`+
 (feedError?`<div class="note">${esc(feedError)}</div>`:feed?items.length?items.map(x=>publicCard(x,false)).join(''):`<div class="empty">${esc(feed.notice)}</div>`:'<div class="empty">جارٍ قراءة سجل الملخصات المجازة…</div>')+
 `<div class="card"><h3>ماذا سيظهر في كل بطاقة؟</h3><p>الفترة والمنهج المختصر ← ما سمعناه بصورة مجمعة ← ما قررناه ونفذناه ← الحالة الفعلية ← ما لم يُحل بعد وموعد المتابعة.</p><p>لا قوائم لترتيب المدرسين أو المقررات، ولا اقتباس لتعليق يمكن التعرف على صاحبه. ويظل التقرير التفصيلي متاحًا للجهة المخولة لمعالجة السبب الحقيقي.</p></div>`;
}
function publicCard(x,demo){return `<article class="card ${demo?'demo':''}"><span class="badge">${demo?'مثال افتراضي فقط — ليس نتيجة حقيقية':'ملخص مجاز للنشر'}</span><h3>${esc(x.theme)}</h3><small>${esc(x.period||'')} · ${esc(x.method||'')}</small><p><b>ما سمعناه:</b> ${esc(x.heard)}</p><p><b>استجابتنا:</b> ${esc(x.action)}</p><p><b>الحالة:</b> ${esc(x.status)}</p><p><b>المتابعة:</b> ${esc(x.nextReview)}</p><p><b>حدود القراءة:</b> ${esc(x.limitations||'')}</p>${!demo?`<small>أجيز النشر: ${esc(x.approvedOn)} · مرجع الإجازة: ${esc(x.approvalRef)}</small>`:''}</article>`;}
function calendar(){
 const count=R.calendars.reduce((n,c)=>n+c.rows,0);
 let html=`<div class="card"><h2>خطة واحدة، لا منظومة عمل موازية</h2><p><code>${R.plan.code}</code> · الإصدار ${R.plan.version} · ${R.plan.year}</p><p>${esc(R.plan.status)}. نهاية المدة: ${R.plan.end}.</p><p>${esc(R.calendarNote)}</p><div class="row"><span class="badge">14 تقويمًا تفصيليًا</span><span class="badge">${count} سطرًا تقويميًا</span><span class="badge">20 بندًا لأدوات الاستطلاع</span><span class="badge">20 نوع تقرير</span><a href="${R.plan.url}" target="_blank" rel="noopener">مصدر الخطة — للمخولين</a></div></div>`;
 html+=`<div class="note">${source?`القراءة المشتركة من سجل الاعتماد، آخر تحديث للمصدر: ${esc(formatDate(source.updatedAt))}. تعرض المهام هنا دون نسخها إلى خطة ثانية.`:sourceError?esc(sourceError):'جارٍ قراءة سجل الاعتماد…'}</div>`;
 html+=`<div class="grid">${R.calendars.map(c=>`<article class="card"><span class="badge">${c.id} · ${c.rows} سطرًا</span><h3>${esc(c.title)}</h3><p><b>المالك:</b> ${esc(c.owner)}</p><p>${esc(c.example)}</p><small>ملخص التوقيت: ${esc(c.timing)}</small><p><b>المخرج:</b> ${esc(c.output)}</p><small>موضع استخراج الجدول في النسخة المفحوصة: ${c.table+1}؛ المعرّف تنظيمي للربط وليس رقم شاهد اعتماد.</small></article>`).join('')}</div>`;
 html+=`<h2>نقاط تنتظر تثبيتًا أو قرارًا</h2>${R.decisions.map(d=>`<details class="card"><summary>${esc(d.title)}</summary><p>${esc(d.detail)}</p></details>`).join('')}`;
 html+=`<h2>أدوات الاستطلاع في الخطة</h2><div class="note">هذه أوصاف توقيت من الخطة، لا روابط مفتوحة أو تعليمات نشر تلقائي. منع التكرار وتحديد المستفيدين شرط قبل التفعيل.</div><div class="scroll"><table><thead><tr><th>الأداة</th><th>التوقيت في الخطة</th><th>ضابط التشغيل</th></tr></thead><tbody>${R.surveys.map(s=>`<tr><td>${s[0]} · ${esc(s[1])}</td><td>${esc(s[2])}</td><td>${esc(s[3])}</td></tr>`).join('')}</tbody></table></div>`;
 if(source)html+=`<h2 style="margin-top:24px">المهام الموجودة في سجل الاعتماد</h2><p>قراءة مباشرة، لا تُغيَّر حالاتها بمجرد عرضها أو إنشاء مثال تجريبي.</p><div class="scroll"><table><thead><tr><th>المهمة</th><th>الجهة</th><th>الفترة المصدرية</th><th>الحالة المسجلة</th></tr></thead><tbody>${sourceTasks().map(t=>`<tr><td><code>${esc(t.id)}</code><br>${esc(t.title)}</td><td>${esc(t.unit||'تحتاج تحديدًا')}</td><td>${esc(t.period||t.due||'لم تثبت')}</td><td>${esc(t.sourceStatus||t.status||'غير محددة')}</td></tr>`).join('')}</tbody></table></div>`;
 return html;
}
function transparency(){return `<div class="card"><h2>الشفافية لا تعني نشر البيانات الشخصية</h2><p>المقابلة التالية تربط الموضوعات بدليل الاعتماد المؤسسي 2023، مع فصل النشر العام عن الأدلة التي تعرض للمراجعين المخولين. ليست حكم استيفاء جديدًا لأي مؤشر.</p></div><div class="scroll"><table><thead><tr><th>المرجع والموضوع</th><th>ما يناسب النشر العام</th><th>ما يبقى داخليًا</th></tr></thead><tbody>${R.transparency.map(t=>`<tr><td><code>${esc(t.refs)}</code><br>${esc(t.topic)}</td><td>${esc(t.public)}</td><td>${esc(t.internal)}</td></tr>`).join('')}</tbody></table></div><section class="card"><h3>بوابة إجازة النشر المقترحة</h3><p>يعد قسم الجودة ملخصًا من التقرير المتحقق، ثم يراجع مخاطر الخصوصية، ثم تعتمد الجهة المخولة النشر، ثم ينشر الإعلام النسخة المصرح بها فقط. إذا تغير النص بعد الإجازة، تعاد مراجعته. تحفظ نسخة المنشور وتاريخها ودليل الإجازة.</p><h3>قائمة الفحص</h3>${R.privacyChecks.map(t=>`<p>✓ ${esc(t)}</p>`).join('')}<div class="note">اقتراح تحفظي للأرقام، وليس حكمًا قانونيًا أو ضمانًا للسرية: عدم عرض نسبة لمجموعة تقل عن 10 مشاركين، ولا توزيع يجعل عددًا أقل من 5 أو متممه قابلاً للاستنتاج. حتى الأعداد الأعلى تحتاج مراجعة سياق وإمكان الربط. عند الخطر ندمج الفئات أو نؤجل الرقم وننشر وصفًا عامًا أمينًا.</div><p>لا تُنقل أسماء المقررات إلى النشرة العامة، لكن لا تُمحى من التحليل الداخلي إذا كانت لازمة لمعالجة المشكلة. والاستبيان يصف تجربة المشاركين، وليس إثباتًا تلقائيًا للمسؤولية أو سوء الأداء.</p><p><a href="${R.universityGuide.url}" target="_blank" rel="noopener">دليل الجامعة — ص10، 12، 22–23، 55–58</a> · <a href="https://qaa.ly/wp-content/uploads/2024/06/دليل-معايير-الاعتماد-المؤسسي-لمؤسسات-التعليم-العالي-الاصدار-الرابع-2023.pdf" target="_blank" rel="noopener">دليل الاعتماد المؤسسي 2023</a></p></section>`;}
function continuity(){return `<section class="card"><h2>ما يبقى عندما يتغير المسؤول؟</h2><p>الخطة والتقويم والأدوار والوثائق وحالات المتابعة، لا اسم الشخص أو ذاكرة المحادثة. دور قسم الجودة يدير الإدخال الرسمي والربط؛ الجهات المالكة تؤكد صحة المخرجات؛ اعتماد الوثيقة أو القرار يتم لدى صاحب الصلاحية.</p><div class="grid"><article><h3>مصدر واحد للحقيقة</h3><p>هوية ثابتة للفترة والمهمة والوثيقة وإصدارها والشاهد. إنشاء مهمة دورية يستخدم مفتاحًا فريدًا من الإجراء والدور والفترة، لمنع التكرار عند إعادة الاستيراد.</p></article><article><h3>التسليم يشمل الجودة والعميد</h3><p>المهام المفتوحة، المواعيد، النسخ الحالية، الاستجابات غير المغلقة، صلاحيات الحسابات ومكان الأصول. كلمات المرور لا تدخل محاضر التسليم.</p></article><article><h3>نسخ قابلة للاستعادة</h3><p>تصدير قاعدة البيانات والملفات الفعلية ومعرفاتها وسجل التغييرات ومخطط البيانات وبصمات التحقق. نسخة الروابط وحدها لا تحفظ محتوى الملفات.</p></article><article><h3>اختبار مستقل</h3><p>يختبر موظف جديد العثور على مهمة وتقديم مخرج وتتبع استكماله، ويختبر IT الاستعادة في بيئة منفصلة. يسجل زمن الاستعادة والفقد المقبول وفق قرار الجامعة.</p></article></div></section><section class="card"><h3>ما يعمل الآن وما ينتظر خادم الجامعة</h3><p><b>الآن:</b> روابط متبادلة، قراءة مشتركة لملخص الاعتماد، فهرسة التقويمات، وتجربة محلية من الفكرة إلى المهمة ومعاينة الاستجابة. البيانات التجريبية لا تنتقل بين الأجهزة.</p><p><b>لاحقًا على خادم الجامعة:</b> تسجيل دخول وصلاحيات على الخادم، استقبال آمن، ملفات مقيدة، سجل تدقيق محمي، مهام دورية، إجازة نشر فعلية، نسخ احتياطية واستعادة مؤسسية. اسم «داخلي» أو كلمة مرور في واجهة ثابتة لا يحمي البيانات.</p><p>لا تُرفع الردود الخام أو بيانات الطلبة أو مفاتيح الربط إلى GitHub العام. صفحة الطلبة تقرأ جدول نشر مستقلًا يحتوي الحقول المجازة فقط، ولا تتصل بجدول الاستجابات الخام.</p><p>الذكاء الاصطناعي أداة مساعدة اختيارية؛ الاستيراد والتوثيق والمراجعة والتصدير لها مسارات يدوية موثقة.</p></section><div class="tools"><h3>اختبار نقل بيانات التجربة</h3><p>التصدير التالي لحالات افتراضية فقط، وليس نسخة احتياطية لبيانات الكلية.</p><button id="export-demo">تصدير التجربة JSON</button><label>استعادة ملف التجربة فقط <input type="file" id="import-demo" accept="application/json,.json"></label><small>عند الاستعادة تُلغى إجازات المعاينة ويلزم فحص الخصوصية من جديد.</small></div>`;}
function example(c){const s=sc(c.scenario);return {theme:s.theme,period:'دورة افتراضية لا تمثل نتائج كلية التمريض',method:'مثال تصميم؛ لا عينة أو نسب حقيقية',heard:s.heard,action:s.action,status:'نُفذ في المحاكاة؛ الأثر لم يُتحقق منه',nextReview:s.next,limitations:'لا تُستخدم هذه البطاقة كإعلان عن إنجاز واقعي. المعاينة المحلية ليست نشرًا للطلبة.'};}
function demo(){
 let html=`<div class="note"><b>تجربة محلية فقط.</b> لا يوجد إرسال للكلية أو نشر حقيقي. نستعمل موضوعات افتراضية ثابتة، ولا نستقبل أسماء أو تعليقات شخصية. اختيار الدور أدناه لتجربة الواجهة وليس مصادقة.</div><div class="tools"><label>الدور التجريبي <select id="actor" class="wide"><option value="quality" ${actor==='quality'?'selected':''}>قسم الجودة — فرز ومراجعة</option><option value="dean" ${actor==='dean'?'selected':''}>العميد — إجازة معاينة النشر</option></select></label><div class="row"><a class="btn" href="../quality-system-prototype/">فتح المنظومة التجريبية</a><button id="refresh-demo">تحديث حالة المهام</button></div><p>ابدئي المنظومة مرة واحدة، ثم أنشئي فكرة هنا، واربطيها بمهمة. انتقلي لدور الموظف لتقديمها، ثم للجودة لقبول مخرجها، وعودي هنا لمراجعة بطاقة الاستجابة.</p></div><h2>مدخل البوابة: فكرة افتراضية</h2><div class="grid">${R.demoScenarios.map(s=>`<article class="card demo"><h3>${esc(s.theme)}</h3><p>${esc(s.heard)}</p><button data-create="${s.id}" ${state.cases.some(c=>c.scenario===s.id)?'disabled':''}>إنشاء مثال للمتابعة</button></article>`).join('')}</div>`;
 html+=`<h2>صندوق الجودة وسلسلة المتابعة</h2>${state.cases.length?'':'<div class="empty">لم تُنشأ حالات تجريبية بعد.</div>'}`;
 for(const c of state.cases){const s=sc(c.scenario);if(!s)continue;const task=taskFor(c),canReview=task?.status==='accepted';
 html+=`<article class="card demo"><span class="badge">${esc(stageNames[c.stage]||c.stage)}</span><h3>${esc(s.theme)}</h3><p><code>${esc(c.id)}</code> · ${esc(R.calendars.find(k=>k.id===s.calendar)?.title)}</p>`;
 if(c.stage==='received')html+=`<label>اختاري الإجراء الموجود في سجل الاعتماد لربط المثال به <select class="wide" id="plan-${s.id}"><option value="">اختيار صريح — لا ربط آلي بالعنوان</option>${sourceTasks().map(t=>`<option value="${esc(t.id)}">${esc(t.id+' · '+t.title)}</option>`).join('')}</select></label><button data-assign="${s.id}" ${actor!=='quality'||!source?'disabled':''}>ربط وإضافة مهمة تجريبية للمنظومة</button>`;
 if(c.taskId)html+=`<p>الإجراء المرجعي: <code>${esc(c.planActionId)}</code> ← المهمة: <code>${esc(c.taskId)}</code> ← حالة مخرجها في المنظومة: <b>${esc(task?.status||'المهمة غير موجودة في هذا المتصفح')}</b></p><p>مؤشرات مرشحة للمراجعة: ${esc(s.indicators.join('، '))}. لم يُضف شاهد رسمي ولم تتغير نسبة الاعتماد.</p>`;
 if(c.stage==='assigned')html+=`<button data-review="${s.id}" ${actor!=='quality'||!canReview?'disabled':''}>توثيق مراجعة المخرج التجريبي</button><small> يتاح بعد قبول الجودة للمهمة داخل المنظومة، وليس بمجرد إرسال الموظف.</small>`;
 if(['reviewed','preview_approved'].includes(c.stage))html+=publicCard(example(c),true);
 if(c.stage==='reviewed')html+=`<h3>فحص الخصوصية قبل إجازة المعاينة</h3>${R.privacyChecks.map((text,i)=>`<label class="check"><input type="checkbox" data-check="${s.id}" value="${i}"><span>${esc(text)}</span></label>`).join('')}<button data-preview="${s.id}" ${actor!=='dean'?'disabled':''}>إجازة المعاينة في المحاكاة فقط</button><p class="muted">دور الجودة يعدّ البطاقة؛ دور العميد هنا يختبر إجازة النشر. النشر الحقيقي يحتاج حسابًا مخولًا وإثبات صلاحية.</p>`;
 if(c.stage==='preview_approved')html+=`<div class="note">تمت إجازة المعاينة محليًا فقط. ملف الملخصات المنشورة العام لم يتغير، ولا يرى الزوار هذه الحالة على أجهزتهم.</div><button data-package="${s.id}">تصدير بطاقة المثال للمراجعة</button>`;
 html+='</article>';
 }
 return html+`<h2>سجل التجربة</h2><div class="timeline">${state.events.slice().reverse().map(e=>`<p>${esc(formatDate(e.at))} · ${esc(e.actor==='dean'?'العميد — محاكاة':'الجودة/البوابة — محاكاة')} · ${esc(e.action)} · <code>${esc(e.id)}</code></p>`).join('')||'<p>لا أحداث بعد.</p>'}</div>`;
}
function render(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));
 $('#content').innerHTML=({updates,calendar,transparency,continuity,demo}[tab])();
 if(!storageOK)$('#content').insertAdjacentHTML('afterbegin','<div class="note">التخزين المحلي غير متاح. العرض ممكن لكن متابعة التجربة بين الصفحات لن تعمل حتى تسمح إعدادات المتصفح بالتخزين.</div>');
 bind();
}
function change(next){tab=next;history.replaceState(null,'','#'+tab);render();}
function checkActor(want){if(actor!==want){notice('هذا الإجراء غير متاح للدور التجريبي المحدد.');return false;}return true;}
function assign(id){
 if(!checkActor('quality'))return;const c=state.cases.find(x=>x.scenario===id),s=sc(id);if(!c||c.stage!=='received')return;
 const planId=$('#plan-'+id)?.value,plan=sourceTasks().find(t=>t.id===planId);if(!plan){notice('اختاري إجراءً قائمًا أولًا؛ لن ننشئ خطة موازية.');return;}
 const q=qs();if(!q||!Array.isArray(q.tasks)||!Array.isArray(q.audit)){notice('افتحي المنظومة التجريبية أولًا واختاري دورًا، ثم عودي هنا.');return;}
 const taskId='QC-DEMO-'+id;
 if(!q.tasks.some(t=>t.id===taskId))q.tasks.push({id:taskId,title:'[مثال افتراضي] '+s.theme,ownerRole:s.owner,due:'توقيت تجريبي؛ يثبت بعد التقويم المعتمد',status:'assigned',priority:'medium',evidence:'مخرج افتراضي ومراجعة الاستجابة، لا بيانات حقيقية',requestedBy:'quality',qualityCycleId:c.id,planActionId:plan.id,calendarId:s.calendar});
 q.audit.unshift({time:new Date().toISOString(),actor:'قسم الجودة',action:'ربط مثال من بوابة المشاركة',target:taskId+' / '+plan.id});
 if(!write(QMS,q))return;c.stage='assigned';c.taskId=taskId;c.planActionId=plan.id;event('ربط بالإجراء القائم وإنشاء مهمة تجريبية',c.id);render();
}
function bind(){
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>change(b.dataset.go));
 $('#actor')?.addEventListener('change',e=>{actor=e.target.value;render();});
 $('#refresh-demo')?.addEventListener('click',()=>{render();notice('أعيدت قراءة مهام هذا المتصفح.');});
 document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>{const id=b.dataset.create;if(state.cases.some(c=>c.scenario===id))return;const c={id:'QC-DEMO-'+id,scenario:id,stage:'received',createdAt:new Date().toISOString()};state.cases.push(c);event('إنشاء فكرة افتراضية، دون إرسال حقيقي',c.id);render();});
 document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>assign(b.dataset.assign));
 document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{if(!checkActor('quality'))return;const c=state.cases.find(x=>x.scenario===b.dataset.review);if(!c||taskFor(c)?.status!=='accepted')return;c.stage='reviewed';c.reviewedAt=new Date().toISOString();event('مراجعة المخرج التجريبي وإعداد بطاقة عامة',c.id);render();});
 document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{if(!checkActor('dean'))return;const c=state.cases.find(x=>x.scenario===b.dataset.preview);if(!c||c.stage!=='reviewed')return;const checks=[...document.querySelectorAll('[data-check="'+c.scenario+'"]')];if(checks.length!==R.privacyChecks.length||checks.some(i=>!i.checked)){notice('يلزم إكمال فحص الخصوصية الخماسي قبل إجازة المعاينة.');return;}c.stage='preview_approved';c.previewAt=new Date().toISOString();event('إجازة معاينة تجريبية؛ لا نشر على الإنترنت',c.id);render();});
 document.querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>{const c=state.cases.find(x=>x.scenario===b.dataset.package);if(c?.stage==='preview_approved')download('DEMO-NOT-FOR-PUBLICATION-'+c.scenario+'.json',{schemaVersion:1,mode:'DEMO_NOT_FOR_PUBLICATION',caseId:c.id,planActionId:c.planActionId,card:example(c),notice:'لا اعتماد حقيقي ولا نشر؛ يلزم تقرير فعلي ومراجعة مخولين.'});});
 $('#export-demo')?.addEventListener('click',()=>download('quality-cycle-DEMO-backup.json',{schemaVersion:1,mode:'DEMO_ONLY',exportedAt:new Date().toISOString(),cases:state.cases.map(c=>({scenario:c.scenario,stage:c.stage,planActionId:c.planActionId||''}))}));
 $('#import-demo')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>50000)throw Error('الملف أكبر من حد ملفات التجربة.');const x=JSON.parse(await file.text());if(x.schemaVersion!==1||x.mode!=='DEMO_ONLY'||!Array.isArray(x.cases)||x.cases.length>3)throw Error('ليس ملف تجربة صالحًا.');const seen=new Set();for(const c of x.cases){if(!sc(c.scenario)||seen.has(c.scenario)||!stages.includes(c.stage))throw Error('بيانات تجربة غير صالحة.');seen.add(c.scenario);}if(!confirm('استبدال حالات التجربة المحلية فقط؟ ستُلغى إجازات المعاينة السابقة.'))return;state={schemaVersion:1,cases:x.cases.map(c=>({id:'QC-DEMO-'+c.scenario,scenario:c.scenario,stage:'received',createdAt:new Date().toISOString()})),events:[]};event('استعادة أفكار التجربة؛ إعادة الربط والمراجعة مطلوبة','RESTORE-DEMO');render();notice('استُعيدت الأفكار فقط؛ لا اعتماد أو استيفاء من ملف الاستعادة.');}catch(err){notice(err.message||'تعذرت قراءة الملف.');}});
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>change(b.dataset.tab));
window.addEventListener('hashchange',()=>{const h=location.hash.slice(1);if(['updates','calendar','transparency','continuity','demo'].includes(h)){tab=h;render();}});
window.addEventListener('storage',e=>{if(e.key===QMS&&tab==='demo')render();if(e.key===KEY){state=read(KEY,state);render();}});
render();
Promise.allSettled([
 fetch('../accreditation/public-progress.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(!Array.isArray(d.criteria)||!Array.isArray(d.tasks))throw Error();source=d;}).catch(()=>{sourceError='تعذرت قراءة سجل الاعتماد. لا نعرض أصفارًا ولا نفترض فقد الشواهد؛ أعيدي المحاولة لاحقًا.';}),
 fetch('public-updates.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(d.schemaVersion!==1||!Array.isArray(d.items))throw Error();feed=d;}).catch(()=>{feedError='تعذرت قراءة سجل الملخصات المجازة. لم نعرض بيانات تجريبية بدلاً من نتائج حقيقية.';})
]).then(render);
})();
