'use strict';
window.ROM_DATA={
source:'3. Range of Motion-Terms of movement.docx',
reference:'https://openstax.org/books/anatomy-and-physiology-2e/pages/9-5-types-of-body-movements',
groups:[['Elbow angle','زاوية المرفق'],['Ankle: up / down','الكاحل: أعلى / أسفل'],['Shoulder: up / down','الكتف: أعلى / أسفل'],['Sole: out / in','باطن القدم: خارج / داخل'],['Arm: away / toward','الذراع: ابتعاد / اقتراب'],['Shoulder rotation','دوران الكتف'],['Forearm rotation','دوران الساعد'],['Shoulder: back / forward','الكتف: خلف / أمام']],
terms:[
{id:'flexion',group:0,name:['Flexion','الثني'],definition:['Decrease the angle at a joint; bend it.','تقليل الزاوية عند المفصل؛ ثني المفصل.'],observe:['Watch the forearm bend toward the upper arm. The upper arm stays still in this example.','راقب الساعد وهو ينثني نحو العضد. يبقى العضد ثابتًا في هذا المثال.'],cue:['Follow the angle between the upper arm and forearm, not where the fingers happen to point.','تابع الزاوية بين العضد والساعد، لا الاتجاه الذي تشير إليه الأصابع.'],confusion:['A smaller elbow angle is flexion, not extension.','نقصان زاوية المرفق ثني، وليس بسطًا.'],original:'Flexion –decreasing the angle of the joint. Bending the joint.'},
{id:'extension',group:0,name:['Extension','البسط'],definition:['Increase the angle at a joint; straighten it.','زيادة الزاوية عند المفصل؛ بسط المفصل.'],observe:['The bent forearm moves away from the upper arm as the elbow straightens.','يبتعد الساعد المثني عن العضد مع استقامة المرفق.'],cue:['Start from a bent elbow and look for an increasing angle.','ابدأ بمرفق مثني وراقب زيادة الزاوية.'],confusion:['Straightening does not mean forcing beyond the straight position shown.','البسط لا يعني دفع المفصل إلى ما بعد الاستقامة الموضحة.'],original:'Extension- increasing the angle of the joint. Straightening the joint.'},
{id:'dorsiflexion',group:1,name:['Dorsiflexion','الثني الظهري للقدم'],definition:['Bring the top of the foot toward the front of the lower leg.','قرّب ظهر القدم نحو مقدمة الساق.'],observe:['The forefoot lifts toward the shin; the lower leg stays still.','يرتفع مقدم القدم نحو الساق، بينما تبقى الساق ثابتة.'],cue:['Watch the relationship between the top of the foot and the shin.','راقب العلاقة بين ظهر القدم ومقدمة الساق.'],confusion:['Lifting the forefoot differs from turning the sole inward.','رفع مقدم القدم يختلف عن توجيه باطنها للداخل.'],original:'Dorsiflexion-decreasing the angle of the ankle joint.'},
{id:'plantar',group:1,name:['Plantar flexion','الثني الأخمصي للقدم'],definition:['Point the foot downward, away from the front of the lower leg.','وجّه القدم إلى أسفل، بعيدًا عن مقدمة الساق.'],observe:['The forefoot points away from the shin rather than lifting toward it.','يتجه مقدم القدم بعيدًا عن الساق بدل ارتفاعه نحوها.'],cue:['Follow the whole foot at the ankle; bending only the toes is not this demonstration.','تابع حركة القدم عند الكاحل؛ ثني أصابع القدم وحدها ليس الحركة المقصودة.'],confusion:['This is not eversion: the sole is not being turned away from the other foot.','هذا ليس قلبًا للخارج؛ لا يُوجَّه باطن القدم بعيدًا عن القدم الأخرى.'],original:'Plantar flexion-increasing the angle of the ankle.'},
{id:'elevation',group:2,name:['Elevation','الرفع'],definition:['Move a body part in a superior direction—upward.','تحريك جزء من الجسم باتجاه علوي؛ إلى أعلى.'],observe:['Watch both shoulders rise toward the ears while the head stays in place.','راقب ارتفاع الكتفين نحو الأذنين مع ثبات الرأس.'],cue:['The shoulder shrug illustrates upward movement without raising the arms sideways.','يوضح هز الكتفين للأعلى حركة الرفع دون إبعاد الذراعين جانبًا.'],confusion:['Shoulder elevation and arm abduction are different movements.','رفع الكتف وإبعاد الذراع حركتان مختلفتان.'],original:'Elevation-moving a body part in a superior direction.'},
{id:'depression',group:2,name:['Depression','الخفض'],definition:['Move a body part in an inferior direction—downward.','تحريك جزء من الجسم باتجاه سفلي؛ إلى أسفل.'],observe:['Watch the raised shoulders lower while the head stays still.','راقب نزول الكتفين المرفوعين مع ثبات الرأس.'],cue:['The starting shoulders are raised; the displayed action is their lowering.','يبدأ الكتفان مرفوعين؛ الفعل المعروض هو خفضهما.'],confusion:['Here depression names a movement direction, not a mood.','المقصود هنا اتجاه حركة، وليس حالة مزاجية.'],original:'Depression-moving a body part in a inferior direction.'},
{id:'eversion',group:3,name:['Eversion','قلب باطن القدم للخارج'],definition:['Turn the sole away from the body midline and the other foot.','وجّه باطن القدم بعيدًا عن الخط الناصف للجسم والقدم الأخرى.'],observe:['The model’s right foot rolls so its sole faces outward; compare it with the other foot.','تميل قدم النموذج اليمنى بحيث يتجه باطنها للخارج؛ قارنها بالقدم الأخرى.'],cue:['Judge the direction of the sole, not just the toe tip.','احكم من اتجاه باطن القدم، وليس طرف الأصابع فقط.'],confusion:['This is a foot-roll movement, not simply pointing the toes down.','هذه حركة قلب للقدم، وليست مجرد توجيه الأصابع لأسفل.'],original:'Eversion- rotating the ankle so that the sole of the foot points away from the other.',note:'foot'},
{id:'inversion',group:3,name:['Inversion','قلب باطن القدم للداخل'],definition:['Turn the sole toward the body midline and the other foot.','وجّه باطن القدم نحو الخط الناصف للجسم والقدم الأخرى.'],observe:['The same right foot rolls the other way: its sole faces toward the other foot.','تميل القدم اليمنى نفسها بالاتجاه الآخر؛ يتجه باطنها نحو القدم الأخرى.'],cue:['Use the other foot as a reference for “inward.”','استخدم القدم الأخرى مرجعًا لمعنى «للداخل».'],confusion:['Inversion concerns the sole; dorsiflexion concerns the foot approaching the shin.','القلب للداخل يتعلق بباطن القدم؛ الثني الظهري يتعلق باقتراب القدم من الساق.'],original:'Inversion- rotating the ankle so that the sole of the foot points towards the other.',note:'foot'},
{id:'abduction',group:4,name:['Abduction','الإبعاد'],definition:['Move a limb away from the midline of the body.','تحريك طرف بعيدًا عن الخط الناصف للجسم.'],observe:['The right arm moves sideways away from the trunk. The body midline is fixed.','تتحرك الذراع اليمنى جانبًا بعيدًا عن الجذع. يبقى الخط الناصف للجسم ثابتًا.'],cue:['Compare the arm with the body midline, not with the screen edge.','قارن الذراع بالخط الناصف للجسم، وليس بحافة الشاشة.'],confusion:['Moving the whole arm sideways is not the same as rotating it around its own long axis.','تحريك الذراع جانبًا ليس دورانها حول محورها الطولي.'],original:'Abduction-moving a limb away from the center line (medial line ) of the body.'},
{id:'adduction',group:4,name:['Adduction','التقريب'],definition:['Move a limb toward the midline of the body.','تحريك طرف نحو الخط الناصف للجسم.'],observe:['The arm begins away from the trunk and returns toward the side.','تبدأ الذراع بعيدة عن الجذع ثم تعود نحو جانبه.'],cue:['Toward the midline is the opposite of away from it.','نحو الخط الناصف هو عكس الابتعاد عنه.'],confusion:['Entry 10 repeats “Abduction,” but its definition describes adduction. See the clarification.','يكرر البند 10 كلمة Abduction لكن تعريفه يصف التقريب. راجع التوضيح.'],original:'Abduction-moving a limb towards the center line (medial line ) of the body.',note:'adduction'},
{id:'lateral',group:5,name:['Lateral rotation','الدوران الوحشي (الخارجي)'],definition:['Rotate a limb away from the body midline around its long axis.','تدوير الطرف للخارج بعيدًا عن الخط الناصف حول محوره الطولي.'],observe:['The upper arm turns at the shoulder. With the elbow bent, the forearm swings outward while the elbow stays beside the trunk.','يدور العضد عند الكتف. ومع ثني المرفق يتحرك الساعد للخارج ويبقى المرفق قرب الجذع.'],cue:['The bent forearm makes the upper-arm rotation visible. It is not a sideways lift of the whole arm.','يجعل الساعد المثني دوران العضد واضحًا. ليست الحركة رفع الذراع كلها جانبًا.'],confusion:['Lateral rotation is not forearm supination: watch which body segment turns.','الدوران الخارجي ليس استلقاء الساعد؛ راقب الجزء الذي يدور.'],original:'Lateral Rotation-rotating limb away from the center line (medial line) of the body.'},
{id:'medial',group:5,name:['Medial rotation','الدوران الإنسي (الداخلي)'],definition:['Rotate a limb toward the body midline around its long axis.','تدوير الطرف للداخل نحو الخط الناصف حول محوره الطولي.'],observe:['The upper arm turns inward at the shoulder, bringing the bent forearm toward the abdomen.','يدور العضد للداخل عند الكتف فيقترب الساعد المثني من البطن.'],cue:['Keep the example’s elbow beside the trunk; follow the swing of the bent forearm.','يبقى المرفق في هذا المثال قرب الجذع؛ تابع حركة الساعد المثني.'],confusion:['Rotation is not elbow flexion—the elbow angle remains unchanged here.','هذا دوران وليس ثني المرفق؛ تبقى زاوية المرفق ثابتة هنا.'],original:'Medial Rotation-rotating limb towards the center line (medial line) of the body.'},
{id:'pronation',group:6,name:['Pronation','كبّ الساعد'],definition:['Rotate the forearm so the palm faces down with the elbow bent.','تدوير الساعد لتتجه راحة اليد لأسفل مع ثني المرفق.'],observe:['The palm turns from up to down. The elbow angle stays the same.','تدور الراحة من أعلى إلى أسفل مع بقاء زاوية المرفق كما هي.'],cue:['Watch the palm surface turning; the wrist does not need to bend.','راقب دوران سطح الراحة؛ لا تحتاج إلى ثني الرسغ.'],confusion:['Turning the forearm is different from rotating the upper arm at the shoulder.','دوران الساعد يختلف عن دوران العضد عند الكتف.'],original:'Pronation-rotating the forearm so that the palm faces down if the forearm is flexed.'},
{id:'supination',group:6,name:['Supination','استلقاء الساعد'],definition:['Rotate the forearm so the palm faces up with the elbow bent.','تدوير الساعد لتتجه راحة اليد لأعلى مع ثني المرفق.'],observe:['The palm turns from down to up without changing the elbow angle.','تدور الراحة من أسفل إلى أعلى دون تغيير زاوية المرفق.'],cue:['Remember the palm-up finish in this bent-elbow example.','تذكر النهاية والراحة لأعلى في مثال المرفق المثني.'],confusion:['Palm up is this example’s end position; the animation also shows the movement into it.','الراحة لأعلى وضع النهاية هنا؛ يعرض الرسم الحركة التي تؤدي إليه أيضًا.'],original:'Supination-rotating the forearm so that the palm faces up if the forearm is flexed.'},
{id:'retraction',group:7,name:['Retraction','السحب للخلف'],definition:['Move the shoulder girdle backward; the shoulder blades move back and toward the spine.','تحريك حزام الكتف للخلف؛ يتحرك لوحا الكتف للخلف ونحو العمود الفقري.'],observe:['Use the top-view inset: the shoulders move backward around the rib cage.','استخدم المنظر العلوي المكبّر؛ يتحرك الكتفان للخلف حول القفص الصدري.'],cue:['Anterior means front, posterior means back. This example moves backward, not upward.','الأمامي يعني جهة الأمام والخلفي جهة الخلف. يتحرك المثال للخلف وليس للأعلى.'],confusion:['The source combines “anterior” with “towards the back.” Those directions conflict.','يجمع المصدر بين «أمامي» و«نحو الخلف»، وهما اتجاهان متعارضان.'],original:'Retraction-anterior movement (towards the back of the body)of the arm at the shoulder.',note:'retraction'},
{id:'protraction',group:7,name:['Protraction','الدفع للأمام'],definition:['Move the shoulder girdle forward around the rib cage.','تحريك حزام الكتف للأمام حول القفص الصدري.'],observe:['Use the top view: the shoulders move forward while the trunk stays in place.','استخدم المنظر العلوي؛ يتحرك الكتفان للأمام ويبقى الجذع ثابتًا.'],cue:['Forward shoulder movement is different from bending the elbow or lifting the shoulder.','حركة الكتف للأمام تختلف عن ثني المرفق أو رفع الكتف.'],confusion:['The source says “posterior/towards the back,” which conflicts with protraction.','يذكر المصدر «خلفي/نحو الخلف»، وهذا يتعارض مع الدفع للأمام.'],original:'Protraction-posterior movement (towards the back of the body) of the arm at the shoulder.',note:'protraction'}
],
clarifications:{
adduction:['Entry 10 repeats Abduction although the definition says toward the midline. The displayed term and answer key use Adduction, supported by OpenStax §9.5. The original wording is retained below.','يكرر البند 10 كلمة Abduction رغم أن التعريف يقول نحو الخط الناصف. يستخدم العرض ومفتاح الإجابة Adduction (التقريب) وفق OpenStax، قسم 9.5. النص الأصلي محفوظ أدناه.'],
retraction:['Entry 15 combines anterior with “towards the back,” an internal contradiction. The animation uses backward/posterior shoulder movement for Retraction, supported by OpenStax §9.5.','يجمع البند 15 بين anterior و«نحو الخلف»، وهو تعارض داخل النص. يستخدم الرسم حركة الكتف الخلفية لـ Retraction وفق OpenStax، قسم 9.5.'],
protraction:['Entry 16 gives posterior/backward for Protraction. The animation uses forward/anterior shoulder movement, supported by OpenStax §9.5. The original line has not been erased or silently changed.','يعطي البند 16 معنى خلفي لـ Protraction. يستخدم الرسم الحركة الأمامية للكتف وفق OpenStax، قسم 9.5. لم يُحذف السطر الأصلي أو يُغيّر دون توضيح.'],
foot:['Entries 7–8 describe “rotating the ankle.” Anatomical clarification: inversion/eversion involve joints of the hindfoot, rather than the ankle hinge alone. The animation shows the sole turning in/out, not a precise joint model.','يصف البندان 7–8 «تدوير الكاحل». توضيح تشريحي: تشمل حركتا القلب مفاصل مؤخر القدم، لا مفصل الكاحل الرِّزّي وحده. يوضح الرسم اتجاه الباطن وليس نموذجًا مفصليًا دقيقًا.']
},
extraQuestions:[
{q:['With the elbow bent, the palm turns downward while the upper arm stays still. Which term fits?','مع ثني المرفق تدور الراحة لأسفل والعضد ثابت. ما المصطلح؟'],choices:[12,13,10,0],correct:12},
{q:['The upper arm stays next to the trunk. Its long-axis rotation swings the bent forearm outward. Which movement is this?','يبقى العضد بجانب الجذع ويدور حول محوره فيحرك الساعد المثني للخارج. ما الحركة؟'],choices:[10,8,13,0],correct:10},
{q:['A raised shoulder returns downward without the arm being brought in from the side. What is this?','يعود كتف مرفوع إلى أسفل، دون تقريب ذراع كانت مبعدة جانبًا. ما الحركة؟'],choices:[5,9,1,14],correct:5},
{q:['The arm returns toward the body after a sideways lift. Which term names the return?','تعود الذراع نحو الجسم بعد إبعادها جانبًا. ما اسم حركة العودة؟'],choices:[9,8,10,15],correct:9},
{q:['The sole faces toward the other foot. Which term fits, rather than lifting the foot toward the shin?','يتجه باطن القدم نحو القدم الأخرى. ما المصطلح، بدلًا من رفع القدم نحو الساق؟'],choices:[7,6,2,3],correct:7},
{q:['The shoulders move forward around the rib cage. Which term matches the clarified terminology?','يتحرك الكتفان للأمام حول القفص الصدري. ما المصطلح وفق التوضيح التشريحي؟'],choices:[15,14,4,5],correct:15},
{q:['In the clarified terminology, what is the opposite of Protraction?','في المصطلحات الموضحة، ما عكس Protraction؟'],choices:[14,15,10,5],correct:14},
{q:['Which term describes an increasing elbow angle, without rotating the forearm?','أي مصطلح يصف زيادة زاوية المرفق دون دوران الساعد؟'],choices:[1,0,13,12],correct:1}
]
};
