import {HandScene} from './hands.mjs';
import {steps,surfaces,rationale,review,bi} from './content.mjs';
import {fresh,action,scrub,missed} from './engine.mjs';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
let lang=1,mode='learn',idx=0,playing=false,slow=false,elapsed=0,level=0,state=fresh(),drag=null,lastFrame=0,practicePhase=2.1,gestureTime=0,angular=0,strokeTravel=0,reversals=0,lastDirection=0,transition=0;
const tx=x=>x[lang], scene=new HandScene($('#scene'));let demoEnd=false;
const messages={removed:bi('Watch and jewelry removed. Turn on the water.','أُزيلت الساعة والحلي. افتح الماء.'),waterOn:bi('Water is on and comfortably warm. Move hands into the stream.','الماء مفتوح ودافئ. مرّر اليدين تحت الماء.'),waterOff:bi('Water is off. You can turn it on again at any time.','أُغلق الماء. يمكنك فتحه مجددًا في أي وقت.'),turnWaterOn:bi('Turn on the faucet first.','افتح الصنبور أولًا.'),wetFirst:bi('Wet your hands first.','بلّل يديك أولًا.'),wet:bi('Hands and wrists are wet. Apply soap.','تبللت اليدان والرسغان. ضع الصابون.'),soap:bi('Soap applied. Drag over the hands to scrub.','وُضع الصابون. اسحب فوق اليدين للفرك.'),rinsed:bi('Rinsed. Take a paper towel to dry.','تم الشطف. خذ منشفة ورقية للتجفيف.'),rinseFirst:bi('Rinse the soap away first. The water is still usable.','اشطف الصابون أولًا. ما زال الماء متاحًا.'),dry:bi('Hands and wrists dried. Use the fresh towel to close the faucet.','جُففت اليدان والرسغان. استخدم المنشفة الجديدة لإغلاق الصنبور.'),safe:bi('Faucet closed with a towel barrier. Open your debrief.','أُغلق الصنبور بحاجز ورقي. افتح مراجعة أدائك.'),contaminated:bi('Bare hands touched the faucet. Rewash: water → wet → soap.','لامست اليد النظيفة الصنبور مباشرة. أعد الغسل: ماء ← تبليل ← صابون.'),needSoap:bi('Apply soap after wetting, then practise the rubbing movement.','ضع الصابون بعد التبليل ثم تدرب على حركة الفرك.'),complete:bi('Movement practised. Continue when you are ready.','تدرّبت على الحركة. انتقل حين تكون مستعدًا.'),circle:bi('Trace a small circle over the hands; keep contact as you turn.','ارسم دائرة صغيرة فوق اليدين وحافظ على التلامس أثناء الدوران.'),stroke:bi('Rub back and forth over the hands, with several changes of direction.','افرك ذهابًا وإيابًا فوق اليدين مع تكرار تغيير الاتجاه.')};
const textMap={brand:bi('Faculty of Nursing · Tobruk University','كلية التمريض · جامعة طبرق'),'brand-sub':bi('Clinical skills studio','مختبر المهارات السريرية'),'intro-title':bi('Learn the movement.\nThen make it yours.','تعلّم الحركة.\nثم جرّبها بيدك.'),'intro-text':bi('Medical handwashing. Watch Ahmed perform the procedure, then move the hands by scrubbing and dragging. Notice contact and cover every surface.','غسل اليدين الطبي — شاهد أحمد يطبق الإجراء، ثم حرّك اليدين بالفرك والسحب. ركّز على التلامس وتغطية جميع الأسطح.'),'intro-note':bi('A deliberately slow teaching demonstration based on your instructor’s document. Screen practice does not replace supervised practice at the sink.','عرض تعليمي بطيء وفق دليل المدرّس. تدريب الشاشة لا يغني عن التطبيق عند المغسلة.'),'intro-art-text':bi('WATCH · SCRUB · REMEMBER','شاهد · افرك · تذكّر'),start:bi('Watch the demonstration ↗','شاهد العرض ↗'),prev:bi('← Previous','السابق ←'),next:bi('Next →','→ التالي'),replay:bi('↻ Replay movement','↻ أعد الحركة'),slow:bi('½ Slow motion','½ عرض بطيء'),why:bi('Why?','لماذا؟'),try:bi('Try it yourself ↗','جرّب بنفسك ↗'),'watch-note':bi('Intentionally slowed for learning. H8 specifies 10–30 seconds of friction; the demonstration is not a procedure timer.','عُرضت الحركات ببطء للتعلّم. تحدد H8 فركًا لمدة 10–30 ثانية؛ العرض ليس مؤقّتًا للإجراء.'),'practice-prev':bi('Previous movement','الحركة السابقة'),'practice-next':bi('Next movement','الحركة التالية'),'practice-why':bi('Why?','لماذا؟'),finish:bi('My debrief','مراجعة أدائي'),'level-title':bi('Prompts:','التلميحات:'),'back-watch':bi('Watch again','شاهد مجددًا'),'debrief-tag':bi('A SHORT REFLECTION','مراجعة مختصرة'),'debrief-title':bi('What did your hands cover?','ما الأسطح التي تدرّبت عليها؟'),'coverage-note':bi('Amber = missed or incompletely practised surfaces. A learning record, not a measurement of microbes or real hand hygiene.','الكهرماني = أسطح لم تُمارس أو لم يكتمل التدريب عليها. سجل تعليمي، وليس قياسًا للميكروبات أو لنظافة يديك الحقيقية.'),again:bi('Practise again','تدرّب مجددًا'),memory:bi('Try from memory','جرّب من الذاكرة'),footer:bi('Medical handwashing · Educational prototype for faculty review','غسل اليدين الطبي · نموذج تعليمي للمراجعة')};
function localize(){document.documentElement.lang=lang?'ar':'en';document.documentElement.dir=lang?'rtl':'ltr';$('#language').textContent=lang?'English':'العربية';for(const [id,t] of Object.entries(textMap)){const el=$('#'+id);el.textContent=tx(t);if(id==='intro-title')el.style.whiteSpace='pre-line'}const names={watch:bi('⌚ Watch','⌚ الساعة'),faucet:bi('Faucet','الصنبور'),water:bi('Water / hands','الماء / اليدان'),soap:bi('Soap','الصابون'),towel:bi('Towel','المنشفة')};all('[data-action]').forEach(b=>b.textContent=tx(names[b.dataset.action]));all('[data-level]').forEach((b,i)=>{b.textContent=tx([bi('Guided','بإرشاد'),bi('Less help','إرشاد أقل'),bi('From memory','من الذاكرة')][i]);b.classList.toggle('active',i===level)});if(mode==='debrief')debrief();else update();}
function update(){let st=steps[idx];$('#mode-label').textContent=tx(mode==='practice'?bi('TRY IT YOURSELF','جرّب بنفسك'):bi('WATCH / SLOW DEMONSTRATION','شاهد / عرض تعليمي بطيء'));$('#movement-title').textContent=mode==='practice'&&level===2?tx(bi('Your hands. Your sequence.','يداك. تسلسلك.')):tx(st.title);$('#counter').textContent=`${idx+1} / ${steps.length}`;$('#caption').textContent=mode==='practice'&&level>0?'':tx(st.caption);$('#play').textContent=tx(playing?bi('Ⅱ Pause','Ⅱ إيقاف'):bi('▶ Play','▶ تشغيل'));$('#slow').setAttribute('aria-pressed',slow);$('#stage-tag').textContent=tx(bi('AHMED · CLOSE-UP TECHNIQUE','أحمد · عرض الحركة عن قرب'));$('#review-flag').hidden=st.ref!==8;$('#gesture-hint').textContent=mode==='practice'&&st.ref>=5&&st.ref<=8&&level===0?tx(st.gesture==='circle'?bi('Draw small circles over the hands','حرّك إصبعك بدوائر صغيرة فوق اليدين'):bi('Swipe back and forth over the hands','اسحب ذهابًا وإيابًا فوق اليدين')):'';$('#area-picker').hidden=mode!=='practice'||level!==2;$('#area-picker-label').textContent=tx(bi('Choose the next area yourself','اختر بنفسك السطح التالي'));$('#choose-area').innerHTML='<option value="">'+tx(bi('Choose a movement…','اختر حركة…'))+'</option>'+steps.filter(s=>s.ref>=5&&s.ref<=9).map(s=>'<option value="'+s.id+'">'+tx(s.title)+'</option>').join('');$('#prev').disabled=idx===0;$('#next').disabled=idx===steps.length-1;$('#prep-inset').hidden=idx>3&&idx!==21;$('#prep-inset').innerHTML=(idx<=3||idx===21)?`<svg viewBox="0 0 115 175"><rect x="12" y="153" width="95" height="4" rx="2" fill="#b4c8bd"/><circle cx="39" cy="27" r="14" fill="#dfaa86"/><path d="M25 25Q21 5 41 10Q57 13 52 29L48 19L30 18" fill="#374b43"/><path d="M27 45L51 45L60 97L23 97Z" fill="#fafcf8" stroke="#7d9c91"/><path d="M28 99L26 153M47 99L49 153" stroke="#395b52" stroke-width="11"/><path d="M48 52L57 74L78 82" fill="none" stroke="#dfaa86" stroke-width="9" stroke-linecap="round"/><path d="M70 90L111 90L108 107L73 107Z" fill="#c8d8d3" stroke="#839e94"/><path d="M90 89L90 69L102 69L102 75" fill="none" stroke="#849d9a" stroke-width="4"/><path d="M84 107L84 151" stroke="#a2b6ad" stroke-width="5"/><text x="55" y="169" text-anchor="middle" font-size="8" fill="#35594d">${tx(bi('Uniform clear of sink','الزي بعيد عن الحوض'))}</text></svg>`:'';}
function choose(i){idx=Math.max(0,Math.min(steps.length-1,i));elapsed=0;transition=0;practicePhase=0;gestureTime=0;angular=0;strokeTravel=0;reversals=0;lastDirection=0;drag=null;demoEnd=false;state.motion=null;update();}
function watch(){mode='watch';$('#intro').hidden=true;$('#debrief').hidden=true;$('#trainer').hidden=false;$('#watch-controls').hidden=false;$('#practice-controls').hidden=true;$('#watch-bottom').hidden=false;$('#levels').hidden=true;choose(0);playing=true;scene.resize();update();}
function practice(reset=true){mode='practice';if(reset)state=fresh();$('#intro').hidden=true;$('#debrief').hidden=true;$('#trainer').hidden=false;$('#watch-controls').hidden=true;$('#practice-controls').hidden=false;$('#watch-bottom').hidden=true;$('#levels').hidden=false;playing=false;choose(0);$('#feedback').textContent='';localize();scene.resize()}
function feedback(code){$('#feedback').textContent=messages[code]?tx(messages[code]):code}
function act(a){const result=action(state,a);feedback(result);if(result==='removed')choose(2);if(result==='waterOn')choose(3);if(result==='wet')choose(3);if(result==='soap')choose(5);if(result==='rinsed')choose(21);if(result==='dry')choose(22);if(result==='safe')choose(23);if(result==='contaminated'){state.coverage={};state.dry=false;state.rinsed=false;state.wet=false;state.towel=false;choose(3)}update();}
function why(){const st=steps[idx];$('#why-ref').textContent=`TOBRUK INSTRUCTOR · H${st.ref+1}`;$('#why-title').textContent=tx(st.title);$('#why-text').textContent=tx(rationale[st.ref]);$('#why-review').textContent=[7,8].includes(st.ref)?tx(review):'';$('#rationale').showModal()}
function debrief(){mode='debrief';playing=false;$('#trainer').hidden=true;$('#intro').hidden=true;$('#debrief').hidden=false;const absent=missed(state),done=surfaces.filter(x=>(state.coverage[x.id]||0)>=1);const sec=(name,body)=>`<section><h2>${tx(name)}</h2>${body}</section>`;let html=sec(bi('Completed well','أُنجز جيدًا'),`<p>${done.length?done.map(s=>tx(s.title)).join(' · '):tx(bi('No friction movement fully practised yet.','لم يكتمل التدريب على أي حركة فرك بعد.'))}</p><p>${state.removed?tx(bi('Watch removed. ','أُزيلت الساعة. ')):''}${state.rinsed?tx(bi('Rinsing completed. ','تم الشطف. ')):''}${state.dry?tx(bi('Drying completed.','تم التجفيف.')):''}</p>`);
html+=sec(bi('Missed areas','الأسطح غير المكتملة'),absent.length?absent.map(s=>`<button data-retry="${s.id}">${tx(bi('Retry: ','أعد: '))}${tx(s.title)}</button>`).join(''):`<p>${tx(bi('All listed friction surfaces practised.','تدرّبت على جميع أسطح الفرك المدرجة.'))}</p>`);
let issues=state.issues.map(k=>tx(k==='soapBeforeWet'?bi('Soap attempted before wetting.','محاولة وضع الصابون قبل التبليل.'):bi('Drying attempted before rinsing.','محاولة التجفيف قبل الشطف.')));if(!state.removed)issues.push(tx(bi('Watch/jewelry removal was omitted.','لم تُزل الساعة والحلي.')));if(!state.rinsed)issues.push(tx(bi('Rinsing not completed.','لم يكتمل الشطف.')));if(!state.dry)issues.push(tx(bi('Drying not completed.','لم يكتمل التجفيف.')));html+=sec(bi('Sequence issues','ملاحظات التسلسل'),`<p>${[...new Set(issues)].join(' ')||tx(bi('No recorded sequence issues.','لا توجد ملاحظات تسلسل مسجلة.'))}</p>`);
html+=sec(bi('Recontamination','إعادة التلوث'),`<p>${state.recontamination.length?tx(bi('Bare-hand faucet contact was recorded. ','سُجلت ملامسة الصنبور بيد نظيفة دون حاجز. ')):''}${state.safe?tx(bi('Faucet finally closed using a towel barrier.','أُغلق الصنبور أخيرًا بحاجز ورقي.')):tx(bi('Safe faucet closure is still incomplete.','لم يكتمل إغلاق الصنبور بأمان.'))}</p>${!state.safe?`<button data-retry="close">${tx(bi('Retry the finish','أعد خطوات الإنهاء'))}</button>`:''}`);$('#results').innerHTML=html;all('[data-retry]').forEach(b=>b.onclick=()=>{practice(false);const i=steps.findIndex(s=>s.id===b.dataset.retry);if(i<21){state.wet=true;state.soap=true;state.dry=false;state.rinsed=false;state.coverage[b.dataset.retry]=0;feedback(tx(bi('Focused retry: hands are already wet and soaped.','إعادة مركزة: اليدان مبللتان وعليهما الصابون.')))}else{state.water=true;state.rinsed=false;state.dry=false;state.soap=true;state.towel=false;feedback(tx(bi('Finish again: rinse → towel → faucet.','أعد الإنهاء: الشطف ← المنشفة ← الصنبور.')))}choose(i<21?i:21)});coverageMap();}
function coverageMap(){const cv=$('#coverage-map'),c=cv.getContext('2d');c.clearRect(0,0,680,240);for(let h=0;h<2;h++){c.save();c.translate(185+h*310,145);c.fillStyle='#e7b391';c.strokeStyle='#bc8d70';c.lineWidth=2;c.beginPath();c.roundRect(-45,-44,90,92,25);c.fill();c.stroke();for(let f=0;f<4;f++){c.beginPath();c.roundRect(-42+f*23,-102-(f===1||f===2?12:0),17,73,9);c.fill();c.stroke()}c.beginPath();c.roundRect(36,-30,21,52,9);c.fill();c.stroke();c.fillRect(-27,44,54,42);const ids=['palms',h?'backR':'backL','fingers',h?'tipsR':'tipsL',h?'knucklesR':'knucklesL',h?'wristR':'wristL',h?'armR':'armL',h?'fingerR':'fingerL'];const positions=[[0,8],[24,28],[-20,-42],[0,-101],[0,-31],[0,55],[0,77],[47,-12]];ids.forEach((id,i)=>{c.fillStyle=(state.coverage[id]||0)>=1?'#367d69':'#c58131';c.beginPath();c.arc(...positions[i],7,0,Math.PI*2);c.fill()});c.restore()}c.fillStyle='#31594d';c.font='16px sans-serif';c.textAlign='center';c.fillText(tx(bi('Left','اليسرى')),185,227);c.fillText(tx(bi('Right','اليمنى')),495,227)}
$('#choose-area').onchange=e=>{if(e.target.value)choose(steps.findIndex(s=>s.id===e.target.value))};
$('#language').onclick=()=>{lang=1-lang;localize()};$('#start').onclick=watch;$('#try').onclick=()=>practice();$('#back-watch').onclick=watch;$('#play').onclick=()=>{if(demoEnd)choose(0);playing=!playing;update()};$('#prev').onclick=()=>choose(idx-1);$('#next').onclick=()=>choose(idx+1);$('#replay').onclick=()=>{choose(idx);playing=true;update()};$('#slow').onclick=()=>{slow=!slow;update()};$('#why').onclick=why;$('#practice-why').onclick=why;$('#close-why').onclick=()=>$('#rationale').close();$('#no-text').onclick=()=>{$('#trainer').classList.toggle('text-hidden');$('#no-text').setAttribute('aria-label',tx(bi('Toggle text visibility','إظهار النصوص أو إخفاؤها')))};$('#practice-next').onclick=()=>choose(idx+1);$('#practice-prev').onclick=()=>choose(idx-1);$('#finish').onclick=debrief;$('#again').onclick=()=>{level=0;practice()};$('#memory').onclick=()=>{level=2;practice()};all('[data-level]').forEach(b=>b.onclick=()=>{level=+b.dataset.level;localize()});all('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));
const canvas=$('#scene');
canvas.addEventListener('pointerdown',e=>{if(mode!=='practice')return;canvas.setPointerCapture(e.pointerId);const b=canvas.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;drag={x,y,startX:x,startY:y,last:performance.now(),angle:Math.atan2(y-b.height*.5,x-b.width*.5),moved:0};});
canvas.addEventListener('pointermove',e=>{if(!drag||mode!=='practice')return;const b=canvas.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top,dx=x-drag.x,dy=y-drag.y,dist=Math.hypot(dx,dy),now=performance.now(),dt=Math.min(.12,(now-drag.last)/1000);drag.moved+=dist;drag.last=now;
if(x<b.width*.06||x>b.width*.94||y<b.height*.14||y>b.height*.93){drag.x=x;drag.y=y;return}
const st=steps[idx];state.motion={x:(x/b.width-.5)/.18,y:(y/b.height-.52)/.18};if(st.ref>=5&&st.ref<=8){if(!state.soap){feedback('needSoap');drag.x=x;drag.y=y;return}let angle=Math.atan2(y-b.height*.52,x-b.width*.5),dangle=angle-drag.angle;while(dangle>Math.PI)dangle-=Math.PI*2;while(dangle<-Math.PI)dangle+=Math.PI*2;drag.angle=angle;
if(dist>1){gestureTime+=dt;practicePhase+=Math.min(dist/55,.3);strokeTravel+=dist;let dir=Math.abs(dx)>Math.abs(dy)?Math.sign(dx):Math.sign(dy);if(dist>2){if(lastDirection&&dir!==lastDirection)reversals++;lastDirection=dir;}angular+=Math.min(Math.abs(dangle),.4);let earned=st.gesture==='circle'?Math.min(gestureTime/4.5,angular/(Math.PI*5)):Math.min(gestureTime/4.5,strokeTravel/(b.width*3),reversals/6);if(st.pose==='finger')earned=Math.min(earned,(practicePhase-2)/16);const before=state.coverage[st.id]||0;scrub(state,st.id,Math.max(0,earned-before));if((state.coverage[st.id]||0)>=1)feedback('complete')}
}else if(st.pose==='wet'&&drag.moved>70){if(!state.wet)act('water')}else if(st.pose==='rinse'&&drag.moved>100){if(!state.rinsed)act('water')}
if(drag){drag.x=x;drag.y=y}
});
canvas.addEventListener('pointerup',e=>{if(!drag)return;let d=drag;drag=null;if(d.moved<14){let best=null,dist=Infinity;for(const [key,p] of Object.entries(scene.hit)){const z=Math.hypot(d.x-p.x,d.y-p.y);if(z<dist){dist=z;best=key}}if(dist<65&&best)act(best)}else if(steps[idx].gesture==='circle'&&angular<2)feedback('circle')});canvas.addEventListener('pointercancel',()=>drag=null);
function frame(now){let dt=lastFrame?Math.min((now-lastFrame)/1000,.08):0;lastFrame=now;if(mode==='watch'){if(playing&&!$('#rationale').open){elapsed+=dt*(slow?.45:1);if(elapsed>=steps[idx].duration){if(idx<steps.length-1)choose(idx+1);else{elapsed=steps[idx].duration;playing=false;demoEnd=true;update()}}}scene.render(steps[idx],elapsed,{});$('#progress i').style.width=(elapsed/steps[idx].duration*100)+'%'}else if(mode==='practice'){transition+=dt;let st=steps[idx];let t=st.ref>=5&&st.ref<=8?Math.min(2.1,transition)+Math.max(0,practicePhase):transition;scene.render(st,t,{...state,practice:true});$('#progress i').style.width=((state.coverage[st.id]||0)*100)+'%'}requestAnimationFrame(frame)}
localize();requestAnimationFrame(frame);
// Explicit deterministic review hooks: used by the local visual/contact test harness.
window.handwash={get state(){return state},get step(){return steps[idx]},watch,practice,choose,act,renderAt:(i,t)=>{playing=false;idx=i;elapsed=t;mode='watch';update();scene.render(steps[i],t,{})},get scene(){return scene},setLang:n=>{lang=n;localize()},debrief};
