import {fresh,transition,missing,checkpoint,TARGET_SECONDS} from './engine.mjs';
import {lessons,demo,reviews} from './content.mjs';
import {panorama,closeScene} from './scene.mjs';
const $=s=>document.querySelector(s),app=$('#app');
const stageNames=['Learn','Watch','Practice with me','Do it yourself','Debrief'];
let zoom=false;
let stage=0,lesson=0,s=fresh(),station='room',yaw=1150,back=false,handY=335,hint=0,lastInput=Date.now(),timer=null,demoIndex=-1,playing=false,slow=false,demoBefore=null,demoStart=0,demoElapsed=0,demoDuration=0,returnDebrief=false,rationale=[],installEvent;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('tobruk-skills360-v2',JSON.stringify({stage,lesson,s,station,rationale}));}catch{}}
function modal(title,html){$('#modalBody').innerHTML=`<h2>${title}</h2>${html}`;$('#modal').showModal();}
$('#closeModal').onclick=()=>$('#modal').close();
$('#help').onclick=()=>modal('Move naturally',`<p>Drag an empty part of the room to look around. Tap a station to approach. At the sink, tap objects to handle them. Rub directly over the hands; turn them over with the curved arrow. Drag the green bar below your wrists to move both hands.</p><p>Water contact: move hands into the stream, or tap the stream. A paper towel can dry hands, then protect them at the faucet. Gloves: take from the box, then drag the held glove onto the bare hand (a tap also works). Peel from the base of the first palm, then slide under the other cuff. Tap alternatives are available for reliable phone use.</p><p>Keyboard: Tab through objects, Enter to interact; hold Space on a hand surface to rub. Left/right arrows turn the room.</p><p>Install: Android browser menu → Install app / Add to Home screen. iPhone: Share → Add to Home Screen. Wait for “Ready offline” before disconnecting. Progress stays on this device.</p>`);
$('#review').onclick=async()=>{let source=await fetch('./source.json').then(r=>r.json());modal('FACULTY REVIEW REQUIRED',`<p class="review-note">Educational prototype · instructor validation required before assessed use.</p>${reviews.map(([h,p])=>`<h3>${h}</h3><p>${p}</p>`).join('')}<h3>Primary curricular sources</h3><p>${source.sources.join('<br>')}</p><details><summary>Original procedure and rationale transcription</summary>${source.items.map(x=>`<h3>${x.id}</h3><p>${esc(x.original)}</p><p><em>${esc(x.rationale)}</em></p>`).join('')}</details><h3>Comparison references</h3><p><a href="https://cdn.who.int/media/docs/default-source/patient-safety/how-to-handwash-poster.pdf?sfvrsn=7004a09d_7" target="_blank" rel="noreferrer">WHO: How to handwash</a> · <a href="https://www.cdc.gov/clean-hands/hcp/clinical-safety/index.html" target="_blank" rel="noreferrer">CDC: clinical hand hygiene</a></p><p>These references inform the review register; they do not silently replace the instructor’s procedure. External reference links need internet; all teaching content above works offline.</p>`);};
function nav(){ $('#stages').innerHTML=stageNames.map((n,i)=>`<button data-stage="${i}" class="${i===stage?'active':''}" ${i===stage?'aria-current="step"':''}>${n.toUpperCase()}</button>`).join('');$('#stages').querySelectorAll('button').forEach(b=>b.onclick=()=>setStage(+b.dataset.stage));}
function stopDemo(){playing=false;clearInterval(timer);timer=null;}
function setStage(n){stopDemo();zoom=false;stage=n;returnDebrief=false;if(n===0)setupLesson();if(n===1){s=fresh();demoIndex=-1;station='sink';back=false;handY=335;}if(n===2||n===3){s=fresh(n===2?'practice':'independent');station='room';yaw=1150;hint=0;handY=335;back=false;lastInput=Date.now();}render();save();}
function setupLesson(){s=fresh();station='sink';handY=335;back=false;let t=lessons[lesson].interaction;if(t==='height'){s.water=true;s.watch=false;}if(t==='coverage'){s.water=true;s.wet=true;s.soap=true;}if(t==='faucet'){s=checkpoint('faucet');}if(t==='glove'||t==='disposal'){s=checkpoint('removal');station='gloves';if(t==='disposal'){s.gloves=0;s.removed=2;}}if(t==='contact'){station='patient';s.gloves=2;s.watch=false;}}
function render(){nav();if(stage===0)renderLearn();else if(stage===4)renderDebrief();else renderLab();}
function scene(){return station==='room'?panorama(yaw):closeScene(station,s,{back,handY,elbow:stage===0&&lesson===1});}
function renderLearn(){let l=lessons[lesson];app.innerHTML=`<section class="learn"><div class="lesson-copy"><p class="eyebrow">YOUR FIRST CLINICAL SKILLS</p><p class="stage-tag">${l.tag}</p><h1>${l.title}</h1><p>${l.body}</p>${l.interaction==='height'?'<label for="height">Move hands relative to elbows</label><input id="height" type="range" min="170" max="370" value="335" aria-label="Hand height">':''}${l.interaction==='faucet'?'<div class="lesson-toggle"><button id="bare">Bare fingers</button><button id="barrier">With paper towel</button></div>':''}<p class="lesson-why">${l.why}</p><span class="lesson-count">${lesson+1} / ${lessons.length} short lessons</span><div class="lesson-actions"><button id="previous">← Back</button><button class="primary" id="next">${lesson===lessons.length-1?'Watch Ahmed →':'Next →'}</button></div></div><div class="visual"><div id="scene" tabindex="0" aria-label="Interactive clinical scene">${scene()}</div><div class="mini-caption" id="lessonFeedback">Explore the illustration. Your actions change what you see.</div></div></section>`;
 $('#previous').onclick=()=>{lesson=Math.max(0,lesson-1);setupLesson();render();};$('#next').onclick=()=>{if(lesson===lessons.length-1)setStage(1);else{lesson++;setupLesson();render();save();}};
 if($('#height'))$('#height').oninput=e=>{handY=+e.target.value;s=transition(s,'position',{low:handY>260});paint();feedback(s.low?'Hands below elbows: water travels toward fingertips.':'Hands too high: compare the direction of flow.');};
 if($('#bare')){$('#bare').onclick=()=>{s=checkpoint('faucet');act('faucet');};$('#barrier').onclick=()=>{s=checkpoint('faucet');s.towel=true;act('faucet');feedback('The towel separates clean fingers from the faucet.');};}bindScene();}
function renderLab(){let watching=stage===1;app.innerHTML=`<section class="lab-shell"><div class="scene-top"><span class="location" id="location">${location()}</span><div class="hud">${!watching&&station!=='room'?'<button id="zoom">'+(zoom?'Full station':'Focus hands')+'</button>':''}${!watching&&station!=='room'?'<button id="room">Look around ↗</button>':''}${stage===2?'<button id="hint">A little help</button>':''}</div></div><div id="scene" tabindex="0" aria-label="Interactive clinical scene">${scene()}</div><div class="caption" id="feedback" role="status" aria-live="polite"></div><div id="rubLabel" class="rub-label" hidden></div>${watching?`<div class="watch-title" id="watchTitle">Ahmed’s complete demonstration · Handwashing → Clean gloving → Final handwash</div><div class="watchbar"><button id="play" class="primary">▶ Play</button><button id="replay">↶ Replay last movement</button><button id="slow">Slow: off</button><button id="why">Why?</button><button id="practice">Practise →</button></div>`:`<div class="scene-bottom"><p id="task">${returnDebrief?'Targeted retraining · practise this part, then return to your debrief.':'“Ahmed, please prepare to assist Mr Khaled with his morning care.”'}</p><div class="actions"><button id="finish">${returnDebrief?'Return to debrief':'Finish attempt'}</button><button id="retry" hidden>TRY THIS MOVEMENT AGAIN</button>${stage===2?'<button id="rationale">Why?</button>':''}</div></div>`}</section>`;
 if($('#zoom'))$('#zoom').onclick=()=>{zoom=!zoom;renderLab();};if($('#room'))$('#room').onclick=()=>{station='room';zoom=false;renderLab();};if($('#hint'))$('#hint').onclick=showHint;
 if(watching){$('#play').onclick=togglePlay;$('#replay').onclick=replay;$('#slow').onclick=()=>{slow=!slow;$('#slow').textContent='Slow: '+(slow?'on':'off');};$('#why').onclick=()=>{if(demoIndex<0){feedback('Press Play to begin. Why? explains the current movement.');return;}pauseDemo();modal('Why this movement?',`<p>${demo[demoIndex][3]}</p><button id="continueDemo" class="primary">Continue demonstration</button>`);$('#continueDemo').onclick=()=>{$('#modal').close();togglePlay();};};$('#practice').onclick=()=>setStage(2);}
 else{$('#finish').onclick=()=>{stage=4;render();save();};$('#retry').onclick=()=>{act('retryRemoval');};if($('#rationale'))$('#rationale').onclick=()=>modal('Connect action and reason',`<p>${s.message||'Removing a watch exposes skin; friction loosens dirt; a towel prevents bare contact with the faucet; inside-out glove removal contains the used surface.'}</p><label>In your own words, why does this matter?<textarea id="reflection" rows="3" style="width:100%;margin:12px 0" placeholder="Your explanation…"></textarea></label><button id="keepReflection">Save reflection</button>`);if($('#rationale'))$('#rationale').addEventListener('click',()=>{$('#keepReflection').onclick=()=>{if($('#reflection').value.trim())rationale.push($('#reflection').value.trim());save();$('#modal').close();};});}
 bindScene();if(s.freeze)$('#retry').hidden=false;}
function location(){return (stage===1?'WATCH · ':stage===3?'INDEPENDENT · ':'PRACTICE · ')+({room:'Skills laboratory',sink:'Hand-hygiene station',gloves:'Clean glove station',patient:'Khaled Salem'}[station]);}
function paint(){let el=$('#scene');if(el)el.innerHTML=scene();if($('#location'))$('#location').textContent=location();bindScene();}
function feedback(message,title=''){let el=stage===0?$('#lessonFeedback'):$('#feedback');if(el)el.innerHTML=title?`<b>${esc(title)}</b><p>${esc(message)}</p>`:esc(message);}
function act(action,payload={}){lastInput=Date.now();let before=s;s=transition(s,action,payload);s.lastAction=action;paint();
 if(action==='rub'){if(stage!==3&&$('#rubLabel')){$('#rubLabel').hidden=false;$('#rubLabel').textContent=`Active friction · ${Math.floor(s.seconds)} s / ${TARGET_SECONDS} s`;}return;}
 if(s.message&&(stage!==3||s.freeze))feedback(s.message,s.freeze?'Contamination event':'');
 else if(stage!==3&&stage!==1){let messages={water:'Water is running.',warm:'Warm water and gentle flow selected.',wet:'Hands and wrists are wet.',soap:'Lather is on your hands. Rub directly on the skin.',rinse:'Soap rinsed away.',dry:'Hands and wrists are dry. Use the paper towel on the faucet: touch the towel, then the handle, or drag it there.',towel:'Paper towel in hand.',watch:'Watch removed. Skin is accessible.',don:'The glove slides onto the hand.',fit:'Fingers interlace; the gloves fit smoothly.',care:'The outer glove surfaces are now used. Return to the glove station.',removeFirst:'The first glove peels inside-out; its used surface is contained.',removeSecond:'Bare fingers stayed under the cuff. Both gloves are off.',bag:'Removed gloves are contained in the bag. Tap its top to seal.',seal:'The bag is sealed.',dispose:'Bag disposed. Complete the final handwash at the sink.',retryRemoval:'Removal checkpoint restored. Try just this movement again.'};feedback(messages[action]||'');}
 if(action==='faucet'&&!s.message&&stage!==3)feedback(s.complete?'Both skills complete, including final handwashing.':'Faucet closed through the paper towel. The clean glove station is ready.');
 if(s.freeze&&$('#retry'))$('#retry').hidden=false;else if($('#retry'))$('#retry').hidden=true;
 if(s.events.length>before.events.length&&s.events.at(-1)?.type==='contamination')$('#scene').classList.add('contact-flash');
 if(action==='faucet'&&!s.clean&&before.clean){$('#scene').classList.add('contact-flash');}
 if(s.complete&&stage===2)feedback('You completed the two skills. Finish this attempt for feedback, then try independently.');save();}
function object(id,point={}){if(stage===1)return;
 if(['sink','gloves','patient'].includes(id)){station=id;render();return;}
 const map={watch:'watch',soap:'soap',temperature:'warm',box:'takeGlove',heldGlove:'don',interlace:'fit',cloth:'care',firstCuff:'removeFirst',innerCuff:'removeSecond',outerGlove:'outer',bin:'dispose'};
 if(map[id]){act(map[id],point);return;}
 if(id==='turnHands'){back=!back;paint();return;}
 if(id==='towelBarrier'){barrierSelected=true;feedback('Paper towel ready as a barrier. Touch the faucet, or drag the towel onto it.');return;}
 if(id==='faucet'){act(s.water?'faucet':'water',{bare:!barrierSelected});barrierSelected=false;return;}
 if(id==='stream'){act(s.soap||s.rinsed?'rinse':'wet');return;}
 if(id==='towel'){act(s.dry?'towel':'dry');return;}
 if(id==='bag'){act(s.bag?'seal':'bag');return;}
 if(id==='uniform'){act('stance',{safe:!s.stance});return;}
}
let pointer=null,keyRub=null,barrierSelected=false;
function bindScene(){let el=$('#scene');if(!el)return;
 el.querySelectorAll('[data-object]').forEach(g=>{let b=g.getBBox();let r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',b.x-Math.max(0,(90-b.width)/2));r.setAttribute('y',b.y-Math.max(0,((g.dataset.object==='moveHands'?30:90)-b.height)/2));r.setAttribute('width',Math.max(90,b.width));r.setAttribute('height',Math.max(g.dataset.object==='moveHands'?30:90,b.height));r.setAttribute('fill','transparent');r.setAttribute('class','hitbox');g.insertBefore(r,g.firstChild);});
 if(zoom&&station!=='room'){$('#worldSvg')?.setAttribute('viewBox','300 220 420 420');el.querySelector('[data-object=turnHands]')?.setAttribute('transform','translate(-270 170)');}
 el.onpointerdown=e=>{if(stage===1)return;lastInput=Date.now();let t=e.target.closest('[data-object],[data-area]');pointer={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,time:performance.now(),id:t?.dataset.object,area:t?.dataset.area,moved:0,startHand:handY};el.setPointerCapture(e.pointerId);};
 el.onpointermove=e=>{if(!pointer||stage===1)return;let p=pointer,dx=e.clientX-p.lastX,dy=e.clientY-p.lastY,dist=Math.hypot(dx,dy);p.moved+=dist;
 if(station==='room'&&!p.id){yaw=(yaw-dx*2.2+2400)%2400;paint();}
 else if(p.id==='moveHands'){handY=Math.max(180,Math.min(370,p.startHand+(e.clientY-p.y)*1.3));s.low=handY>260;paint();}
 else if(p.id==='towelBarrier'){let towel=$('#heldTowel');if(towel)towel.style.translate=`${(e.clientX-p.x)*1.5}px ${(e.clientY-p.y)*1.5}px`;}
 else if(p.area&&dist>1){let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-area]');let area=target?.dataset.area||p.area;let dt=Math.min((performance.now()-p.time)/1000,.15);act('rub',{area,seconds:dt});}
 p.lastX=e.clientX;p.lastY=e.clientY;p.time=performance.now();};
 el.onpointerup=e=>{let p=pointer;pointer=null;if(!p)return;if(station==='room'&&p.moved>12)return;
 if(p.id==='towelBarrier'&&p.moved>12){let r=$('#worldSvg').getBoundingClientRect();let point=$('#worldSvg').createSVGPoint();point.x=e.clientX;point.y=e.clientY;let v=point.matrixTransform($('#worldSvg').getScreenCTM().inverse());if(v.x>400&&v.x<580&&v.y<280){act('faucet');barrierSelected=false;}else{feedback('Bring the towel to the faucet handle.');}return;}
 if(p.id==='moveHands'){act('position',{low:handY>260});if(handY<280&&s.water)act(s.soap?'rinse':'wet');return;}
 if(p.area){if(p.moved<5&&stage!==3)feedback('Rub back and forth directly on the skin. Turn the hands to reach the other side.');return;}
 if(p.id){let pt=$('#worldSvg').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;let svgPoint=pt.matrixTransform($('#worldSvg').getScreenCTM().inverse());object(p.id,{x:svgPoint.x,y:svgPoint.y});}};el.onpointercancel=()=>pointer=null;
 el.onkeydown=e=>{let t=e.target.closest('[data-object],[data-area]');if(station==='room'&&['ArrowLeft','ArrowRight'].includes(e.key)){yaw=(yaw+(e.key==='ArrowRight'?100:-100)+2400)%2400;paint();return;}if((e.key==='Enter'||e.key===' ')&&t){e.preventDefault();if(t.dataset.object)object(t.dataset.object);else if(!keyRub){const area=t.dataset.area;keyRub=setInterval(()=>act('rub',{area,seconds:.1}),100);}}};
 el.onkeyup=()=>{clearInterval(keyRub);keyRub=null;};}
window.addEventListener('keyup',()=>{clearInterval(keyRub);keyRub=null;});
window.addEventListener('blur',()=>{pointer=null;clearInterval(keyRub);keyRub=null;if(playing)pauseDemo();});
function showHint(){if(stage!==2)return;hint++;let msg;if(station==='room'){msg=['Think about infection prevention before approaching Khaled.','What should happen to your hands before patient contact?','Look for the hand-hygiene area.'][Math.min(hint-1,2)];if(hint>=4){yaw=0;paint();$('#scene').classList.add('hint-glow');}}else if(station==='sink'){msg=!s.water?'What provides running water?':!s.wet&&!s.rinsed?'Bring your hands into contact with the running water.':!s.soap&&!s.rinsed?'What helps loosen dirt from wet skin?':missing(s).length?'Consider surfaces you have not yet rubbed. Turn the hands to inspect both sides.':s.seconds<30?'Continue active friction; coverage and time both matter.':!s.rinsed?'What removes the lather?':!s.dry?'How will you dry your hands?':'How can you handle the faucet without bare contact?';}else msg=s.removed===1?'Where can bare fingers touch without touching the used outer surface?':s.used?'Keep the used surfaces away from your bare skin.':s.gloves<2?'Inspect the glove box and your uncovered hand.':'Make the gloves comfortable before the brief care contact.';feedback(msg,'A little help');lastInput=Date.now();}
setInterval(()=>{if(stage===2&&!$('#modal').open&&Date.now()-lastInput>28000){showHint();}},3000);
function beginMovement(index){if(index>=demo.length){stopDemo();$('#play').textContent='↶ Watch again';feedback('Demonstration complete. Practise the same two skills in the lab.');return;}demoIndex=index;demoBefore=structuredClone(s);demoElapsed=0;demoDuration=(demo[index][1]==='rub'?4000:2600);station=demo[index][0];let a=demo[index][1];back=demo[index][4]==='backs';handY=a==='wet'||a==='rinse'?260:335;paint();$('#watchTitle').textContent=demo[index][2];feedback(demo[index][3]);$('#scene').dataset.movement=a;$('#scene').classList.add('demo-moving');let target={watch:'watch',water:'faucet',warm:'temperature',soap:'soap',dry:'towel',faucet:'faucet',takeGlove:'box',care:'cloth',bag:'bag',seal:'bag',dispose:'bin'}[a];if(target)$('#scene').querySelector(`[data-object=${target}]`)?.classList.add('demo-target');demoStart=performance.now();}
function completeMovement(){const d=demo[demoIndex],a=d[1];if(a==='rub'){for(let h of ['left','right'])for(let n=0;n<2;n++)s=transition(s,'rub',{area:h+'.'+d[4],seconds:1});}else s=transition(s,a,a==='position'?{low:true}:{});paint();}
function tickDemo(){let now=performance.now();demoElapsed+=(now-demoStart)/(slow?2:1);demoStart=now;if(demoElapsed>=demoDuration){completeMovement();beginMovement(demoIndex+1);} }
function pauseDemo(){stopDemo();$('#play').textContent='▶ Play';$('#scene').classList.remove('demo-moving');}
function togglePlay(){if(playing){pauseDemo();return;}playing=true;if(demoIndex<0||demoIndex>=demo.length-1&&s.complete){s=fresh();beginMovement(0);}else{demoStart=performance.now();$('#scene').classList.add('demo-moving');}$('#play').textContent='Ⅱ Pause';timer=setInterval(tickDemo,80);}
function replay(){stopDemo();if(demoIndex<0)return;s=structuredClone(demoBefore);beginMovement(demoIndex);playing=true;$('#play').textContent='Ⅱ Pause';timer=setInterval(tickDemo,80);}
function audit(){const note=(action,why)=>{if(!s.events.some(e=>e.action===action))s.events.push({type:'technique',action,why});};if(s.watch)note('Watch remained in place','H2 removes the watch to expose skin for cleaning.');if(!s.warm)note('Water adjustment not observed','H3 specifies adjusting flow and warm water.');if(!s.low)note('Hands remained above elbows','H4 requires hands lower than elbows.');if(!s.disposed)note('Containment / disposal not completed','The full module includes bagging, sealing and disposal.');if(!s.complete)note('Final handwashing not completed','G14 includes careful handwashing and drying after glove removal.');}
function renderDebrief(){audit();const groups=[['What you did well','well'],['Sequence issues','sequence'],['Technique issues','technique'],['Contamination events','contamination'],['Self-corrections','correction']];let events=s.events;app.innerHTML=`<section class="debrief"><p class="eyebrow">REFLECT / UNDERSTAND / TRY AGAIN</p><h1>Your clinical decisions</h1><p>${s.complete?'Both skills completed, including final handwashing.':'This attempt ended before the full two-skill cycle was complete. The record below includes what you actually did.'} No percentage score.</p><div class="debrief-grid">${groups.map(([title,type])=>{let items=events.filter(e=>e.type===type);let unique=[...new Map(items.map(e=>[e.action,e])).values()];return `<article><h3>${title}</h3><ul>${unique.length?unique.map(e=>`<li><b>${esc(e.action)}</b>${e.why?' — '+esc(e.why):''}</li>`).join(''):'<li>No observations recorded in this category.</li>'}</ul></article>`;}).join('')}<article><h3>Rationale understanding</h3><p>${rationale.length?'Your written reflections (not automatically graded):':'Not yet demonstrated. Completing an action does not prove understanding.'}</p>${rationale.map(x=>`<p>${esc(x)}</p>`).join('')}<label for="debriefReflection">Why must bare fingers avoid the used glove exterior?</label><textarea id="debriefReflection" rows="3" style="width:100%;margin:10px 0"></textarea><button id="saveReflection">Save my explanation</button></article></div>${events.filter(e=>e.type==='contamination').map(e=>`<div class="chain"><p><b>Your action:</b> ${esc(e.action)}</p><p>↓ <b>What happened:</b> ${e.action==='stance'?'The uniform contact area was marked.':'Contamination transferred at the contact point.'}</p><p>↓ <b>Why:</b> ${esc(e.why)}</p></div>`).join('')}<h2 style="margin-top:28px">Targeted retraining</h2><p>These are simulation checkpoints. A checkpoint resets the learning scene; it is not a real clinical decontamination action.</p><div class="actions"><button data-retry="wash">Handwashing technique</button><button data-retry="faucet">Final faucet movement</button><button data-retry="removal">Glove removal only</button><button id="independent" class="primary">Do it yourself →</button></div></section>`;
 app.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{s=checkpoint(b.dataset.retry,'practice',events);station=b.dataset.retry==='removal'?'gloves':'sink';stage=2;returnDebrief=true;render();});$('#independent').onclick=()=>setStage(3);$('#saveReflection').onclick=()=>{let v=$('#debriefReflection').value.trim();if(v){rationale.push(v);save();renderDebrief();}};save();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('#install').hidden=false;});$('#install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;$('#install').hidden=true;}};
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;const names=await caches.keys();$('#offline').textContent=names.some(n=>n.startsWith('tobruk-skills360-v2-'))?'Ready offline':'Open once online';}).catch(()=>$('#offline').textContent='Offline setup unavailable');}
try{let p=JSON.parse(localStorage.getItem('tobruk-skills360-v2'));if(p&&[0,2,3,4].includes(p.stage)&&p.s){({stage,lesson,s,station,rationale}=p);}}catch{}if(stage===0)setupLesson();render();
