let sceneView='angled',nurseSide=1,demoCount=0,paused=false;
const makeGate=()=>({ready:false,choices:[-1,-1,-1],attempts:[],stops:0});
let gatePractice=D.groups.map(makeGate),gateTest=D.groups.map(makeGate);
const gate=()=> (mode==='test'?gateTest:gatePractice)[P[topic].group];
const gateReady=()=>mode==='learn'||gate().ready;
const gateItems=[
{label:['Patient assessment','تقييم المريض'],options:[['Position and movement restrictions checked with the clinical team','مراجعة الوضعية وقيود الحركة مع الفريق السريري'],['Assume any patient can follow this picture','افتراض أن أي مريض يمكن تحريكه وفق الرسم']],reason:['The source contains no patient-specific contraindication or capability assessment. Resolve that before handling.','لا يتضمن المصدر تقييمًا خاصًا بالمريض لموانع الحركة أو قدرته. احسم ذلك قبل المناولة.']},
{label:['Assistance and equipment','المساعدة والوسائل'],options:[['Required assistance and equipment selected and ready under the local plan','المساعدة والوسائل المطلوبة محددة وجاهزة وفق الخطة المحلية'],['The drawn hands mean I should do it alone','اليدان المرسومتان تعنيان أن أنفذ وحدي']],reason:['Landmarks are not a staffing plan. Appropriate handling assistance/equipment must be determined, not assumed.','المعالم ليست خطة عاملين. يجب تحديد المساعدة والوسائل المناسبة، لا افتراضها.']},
{label:['Setup and monitoring','الإعداد والمراقبة'],options:[['Bed/workspace secure; breathing, lines, limb clearance and comfort plan checked','السرير ومكان العمل آمنان؛ مراجعة التنفس والأنابيب وخلو الأطراف والراحة'],['Check those only after completing the move','فحص ذلك بعد إكمال الحركة فقط']],reason:['The classroom sequence omits these assessments. The added checkpoint keeps unresolved hazards from being mistaken for readiness.','يغفل التسلسل الصفّي هذه التقييمات. تمنع النقطة المضافة اعتبار المخاطر غير المحسومة جاهزيةً.']}
];
function render(){if((mode==='train'||mode==='test')&&!testReview&&!gateReady()){renderGate();return;}renderCore();if($('scene'))installMovementTools();if(mode==='test'&&testReview){const box=document.createElement('div');box.className='scopeNote';box.innerHTML='<h3>'+tr().gateRecord+'</h3>'+gateTest.map((g,i)=>`<p>${bi(D.groups[i])}: ${g.attempts.length} · ${tr().safeStops}: ${g.stops}</p>`).join('')+`<p>${tr().coordRecord}: ${testing.reduce((a,r)=>a+r.countErrors,0)}</p>`;$('content').append(box);}}
function renderGate(){shell();const g=gate();$('content').innerHTML=`<section class="movementPanel"><span class="eyebrow">${bi(D.groups[P[topic].group])}</span><h1>${tr().gateTitle}</h1><p>${tr().gateHelp}</p>${paused?`<div class="feedback wrong"><b>${tr().stopText}</b></div>`:''}<div class="gateGrid">${gateItems.map((x,i)=>`<fieldset><legend>${bi(x.label)}</legend>${x.options.map((v,j)=>`<label class="option"><input type="radio" name="gate${i}" value="${j}" ${g.choices[i]===j?'checked':''}>${bi(v)}</label>`).join('')}</fieldset>`).join('')}</div><button id="gateSubmit" class="primary">${tr().gateSubmit}</button><div id="gateFeedback" role="status"></div><p class="small">${tr().supportNote}</p><button id="backLearning">${tr().nav[0]}</button></section>`;
for(let i=0;i<gateItems.length;i++)document.querySelectorAll(`[name=gate${i}]`).forEach(el=>el.onchange=()=>g.choices[i]=+el.value);
$('gateSubmit').onclick=()=>{const bad=g.choices.map((v,i)=>v!==0?i:-1).filter(i=>i>=0);g.attempts.push({choices:g.choices.slice(),errors:bad});if(bad.length){$('gateFeedback').innerHTML=`<div class="feedback wrong"><b>${tr().gateMissing}</b>${bad.map(i=>`<p>${bi(gateItems[i].reason)}</p>`).join('')}</div>`;return;}g.ready=true;paused=false;render();};$('backLearning').onclick=()=>setMode('learn');}
function installMovementTools(){const scene=$('scene'),container=scene.parentElement,group=P[topic].group;container.insertAdjacentHTML('beforebegin',`<div class="sceneTools"><span class="groupLabel">${bi(D.groups[group])}</span><div><button id="viewToggle">${tr().view}: ${tr().views[sceneView==='angled'?0:1]}</button><button id="nurseToggle">${tr().nurse}: ${tr().nurseSides[nurseSide===1?0:1]}</button><button id="safetyStop" class="stopButton">${tr().stop}</button></div></div>`);
$('viewToggle').onclick=()=>{sceneView=sceneView==='angled'?'top':'angled';$('viewToggle').textContent=tr().view+': '+tr().views[sceneView==='angled'?0:1];draw();};$('nurseToggle').onclick=()=>{nurseSide*=-1;$('nurseToggle').textContent=tr().nurse+': '+tr().nurseSides[nurseSide===1?0:1];draw();};
$('safetyStop').onclick=()=>{playing=false;drag=null;lastInput=-999;if(mode==='learn'){const old=document.getElementById('safetyMessage');if(!old)container.insertAdjacentHTML('afterend',`<div id="safetyMessage" class="feedback wrong" role="status">${tr().stopText}</div>`);return;}gate().ready=false;gate().stops++;gate().choices=[-1,-1,-1];record().ready=false;record().count=0;paused=true;render();};
if(P[topic].count){container.insertAdjacentHTML('afterend',`<section id="countPanel" class="countPanel"><div><b>${tr().count}</b><p>${tr().countHelp}</p></div><div id="countButtons"></div><p id="countMessage" role="status"></p></section>`);if(mode!=='learn'){[1,2,3].forEach(n=>{const btn=document.createElement('button');btn.textContent=String(n);btn.dataset.count=n;btn.onclick=()=>{const r=record();if(!r.ready){$('countMessage').textContent=tr().stateLocked;return;}if(n!==r.count+1){r.countErrors++;$('countMessage').textContent=tr().countWrong;return;}r.count=n;$('countMessage').textContent=n===3?tr().countReady:'';syncCount();syncMovementGates();};$('countButtons').append(btn);});}}
if(topic===0)container.insertAdjacentHTML('afterend',`<div class="small prepLink">${tr().preparation} <a href="https://nourabobaker-create.github.io/tobruk-nursing-simulation/handwash-learning-03/" target="_blank" rel="noopener">${tr().goWash}</a></div>`);
const r=record(),n=group===0?7:group===1?6:4;container.insertAdjacentHTML('afterend',`<div class="sequenceProgress"><span>${tr().currentGroup}: ${group+1}/3</span><span>${tr().progress}: ${topic-D.ranges[group][0]+1}/${n}</span></div>`);syncCount();syncMovementGates();draw();}
function syncCount(){if(!$('countPanel'))return;if(mode==='learn'){$('countButtons').textContent=playing&&demoCount<3?String(Math.max(1,Math.floor(demoCount)+1)):progress>0?'3':'1 · 2 · 3';$('countMessage').textContent=progress>0?tr().countReady:'';}else{document.querySelectorAll('[data-count]').forEach(btn=>{const n=+btn.dataset.count;btn.classList.toggle('countDone',n<=record().count);btn.setAttribute('aria-pressed',String(n<=record().count));});}}
function syncMovementGates(){if(!$('progress')||mode==='learn')return;const ok=record().ready&&gateReady()&&!paused&&(!P[topic].count||record().count===3);$('progress').disabled=!ok;$('motionLabel').textContent=ok?tr().drag:record().ready&&P[topic].count?tr().countHelp:tr().stateLocked;}
function update(){updateCore();syncCount();syncMovementGates();}
