(function(){
'use strict';
if(window.HubFeedback)return;
const C=window.HubFeedbackConfig||{},base='/tobruk-nursing-simulation/';
const style=document.createElement('style');style.textContent='.hub-feedback{font:inherit;font-size:14px;line-height:1.7;margin-top:16px;color:#526b60;text-align:start}.hub-feedback summary{cursor:pointer;display:list-item;width:fit-content;max-width:100%;text-decoration:underline;text-underline-offset:4px;padding:7px 2px}.hub-feedback[open]{border-top:1px solid #dbe7e1;padding-top:8px}.hub-feedback p{font-size:14px!important;line-height:1.8;margin:8px 0!important;max-width:780px}.hub-feedback a{display:inline-block;background:#eaf4ef;color:#174b3b;padding:9px 13px;border:1px solid #bdcfc4;border-radius:9px;text-decoration:none;font-weight:bold;margin:5px 0}.hub-feedback summary:focus-visible,.hub-feedback a:focus-visible{outline:3px solid #b7903c;outline-offset:3px}.hub-feedback-context{font-size:12px!important;overflow-wrap:anywhere;color:#53675d}.hub-feedback-global{max-width:1100px;margin:18px auto;padding:0 20px}.hub-feedback[hidden]{display:none!important}';document.head.append(style);
const ar=()=>document.documentElement.lang!=='en', t=(a,e)=>ar()?a:e;
const clean=s=>String(s||'').replace(/[^a-zA-Z0-9_./-]/g,'').slice(0,100);
function context(el){const topic=clean(el.dataset.feedbackTopic||'hub-page'),part=clean(el.dataset.feedbackPart||'page');const path=location.pathname.startsWith(base)?location.pathname.slice(base.length):'clinical-discovery/';return 'topic='+topic+' | part='+part+' | page='+clean(path)+' | version='+clean(C.version||'unversioned');}
function formLink(el){if(!C.ready||!/^entry\.\d+$/.test(C.contextEntry||''))return null;try{const u=new URL(C.formUrl);if(u.protocol!=='https:'||u.hostname!=='docs.google.com'||!/^\/forms\/d\/e\/[^/]+\/viewform$/.test(u.pathname))return null;u.searchParams.set('usp','pp_url');u.searchParams.set(C.contextEntry,context(el));return u.href;}catch(e){return null;}}
function make(el){const wasOpen=el.querySelector('details')?.open||false;el.replaceChildren();const d=document.createElement('details');d.className='hub-feedback';d.open=wasOpen;const s=document.createElement('summary');s.textContent=t('شيء غير واضح؟ أو فكرة تحب إضافتها؟','Something unclear, or something to add?');d.append(s);const lead=document.createElement('p');lead.textContent=t('ملاحظة اختيارية عن هذا الجزء تحديدًا. لا نطلب اسمك أو رقمك الدراسي أو بريدك. لا تكتب بيانات أشخاص أو مرضى.','Optional feedback about this exact part. We do not ask for your name, student number or email. Do not include personal or patient information.');d.append(lead);const label=el.dataset[ar()?'feedbackLabelAr':'feedbackLabelEn']||el.dataset.feedbackLabel||t('هذه الصفحة','This page');const pos=document.createElement('p');pos.className='hub-feedback-context';pos.textContent=t('الموضع: ','Location: ')+label+' · '+t('النسخة ','Version ')+(C.version||'—');d.append(pos);const href=formLink(el),a=document.createElement(href?'a':'p');if(href){a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';a.textContent=t('افتح نموذج الملاحظة الخاص ↗','Open the private feedback form ↗');}else{a.textContent=t('لم يُفعّل الاستلام بعد. لا توجد ملاحظات تُرسل من هذا الرابط حاليًا.','Receiving is not enabled yet. This link is not currently sending feedback.');}d.append(a);const note=document.createElement('p');note.textContent=t('يُفتح Google Forms ويُملأ موضع الملاحظة فقط. لا تصل مشاركة للفريق إلا عندما تضغط «إرسال» داخل النموذج. الردود غير منشورة؛ ويعالج Google البيانات التقنية وفق سياسته. هذا ليس دعمًا فوريًا أو قناة لحالة مرضية حقيقية.','Google Forms opens with the location filled in. Nothing is submitted to the team until you choose Submit in the form. Responses are not published; Google processes technical data under its policy. This is not immediate support or a channel for a real patient situation.');d.append(note);el.append(d);el.dataset.feedbackMounted='1';}
function mount(root=document){root.querySelectorAll('[data-feedback-topic]').forEach(make);}
function pageFeedback(){const el=document.querySelector('[data-hub-page-feedback]');if(!el)return;const panel=document.querySelector('.panel.active');el.dataset.feedbackTopic=clean(panel?.id||'student-hub');el.dataset.feedbackPart='page';const h=panel?.querySelector('h1,h2,h3');el.dataset.feedbackLabel=h?.textContent?.trim().slice(0,100)||document.title;make(el);}
function refresh(){mount();pageFeedback();}
window.HubFeedback=Object.freeze({mount,refresh});
function start(){mount();pageFeedback();new MutationObserver(refresh).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.addEventListener('hashchange',pageFeedback);document.addEventListener('click',e=>{if(e.target.closest('[data-route],#langBtn,#homeBtn'))setTimeout(pageFeedback,50);});}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
