'use strict';
// Small raw-DEFLATE decoder for browsers without the native decompression stream.
// Its output is bounded by the expected module size; it does not execute data itself.
function inflateModule(input,size){let bit=0,out=new Uint8Array(size),pos=0;
function read(n){let v=0;for(let i=0;i<n;i++){if(bit>=input.length*8)throw Error('Truncated compressed module');v|=((input[bit>>3]>>(bit&7))&1)<<i;bit++;}return v;}
function tree(lengths){let counts=Array(16).fill(0),next=Array(16).fill(0),tables=Array.from({length:16},()=>new Map()),max=0;for(let n of lengths)if(n){counts[n]++;max=Math.max(max,n);}let code=0;for(let i=1;i<16;i++){code=(code+counts[i-1])<<1;next[i]=code;}lengths.forEach((n,s)=>{if(!n)return;let c=next[n]++,rev=0;for(let j=0;j<n;j++){rev=(rev<<1)|(c&1);c>>=1;}tables[n].set(rev,s);});return {tables,max};}
function sym(t){let code=0;for(let i=1;i<=t.max;i++){code|=read(1)<<(i-1);let s=t.tables[i].get(code);if(s!==undefined)return s;}throw Error('Invalid compressed code');}
function put(v){if(pos>=out.length)throw Error('Module exceeds declared size');out[pos++]=v;}
const lb=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258],le=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],db=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],de=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];let final=0;
while(!final){final=read(1);const type=read(2);if(type===0){bit=(bit+7)&~7;let len=read(16),neg=read(16);if((len^neg)!==65535)throw Error('Invalid stored block');while(len--)put(read(8));continue;}let lit,dist;
if(type===1){lit=tree(Array.from({length:288},(_,i)=>i<144?8:i<256?9:i<280?7:8));dist=tree(Array(32).fill(5));}
else if(type===2){const nl=read(5)+257,nd=read(5)+1,nc=read(4)+4,order=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],lens=Array(19).fill(0);for(let i=0;i<nc;i++)lens[order[i]]=read(3);const ct=tree(lens),all=[];while(all.length<nl+nd){let s=sym(ct);if(s<16)all.push(s);else{let count,value;if(s===16){if(!all.length)throw Error('Invalid repeat');count=read(2)+3;value=all.at(-1);}else if(s===17){count=read(3)+3;value=0;}else{count=read(7)+11;value=0;}if(all.length+count>nl+nd)throw Error('Code lengths overflow');while(count--)all.push(value);}}lit=tree(all.slice(0,nl));dist=tree(all.slice(nl));}
else throw Error('Invalid compression block');
while(true){let s=sym(lit);if(s<256){put(s);continue;}if(s===256)break;if(s>285)throw Error('Invalid match length');const j=s-257,len=lb[j]+read(le[j]),di=sym(dist);if(di>29)throw Error('Invalid distance');const distance=db[di]+read(de[di]);if(distance>pos)throw Error('Match before start');for(let k=0;k<len;k++)put(out[pos-distance]);}}
if(pos!==size)throw Error('Module size mismatch');return out;}
if(typeof module!=='undefined'&&module.exports)module.exports=inflateModule;
else(async()=>{try{const resources=await Promise.all(['gloving-0.txt','gloving-1.txt','gloving-2a.txt','gloving-2b.txt','gloving-2c.txt','gloving-3.txt','gloving-4.txt','logos.json'].map(async p=>{let r=await fetch(p);if(!r.ok)throw Error(p+' '+r.status);return r.text();}));const data=Uint8Array.from(atob(resources.slice(0,7).join('').replace(/\s/g,'')),c=>c.charCodeAt(0));const raw=inflateModule(data,101353);const html=new TextDecoder('utf-8',{fatal:true}).decode(raw).replace('"__SUITE_LOGOS__"',resources[7]);document.open();document.write(html);document.close();}catch(e){console.error(e);document.getElementById('loaderStatus').textContent='Unable to load Clean Gloving. Check your connection and reload. تعذر التحميل؛ تحقق من الاتصال وأعد التحميل. '+e.message;}})();
