import {Simulation,pair,labels,required,VERSION} from './engine.js';
import {Room} from './scene.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang=localStorage.getItem('tobruk-lab-language')||'en',selected='',scenario='side',mode='learn',started=false,showLabels=true,highlight='',lastHint=0;
const t=p=>typeof p==='string'?p:(p?.[lang]||p?.en||'');
const text=(en,ar)=>lang==='ar'?ar:en;
const cases={side:{title:pair('Supine → side-lying','من الاستلقاء الظهري إلى الجانبي'),subtitle:pair('Prepare · turn · support','جهّز · قلّب · ادعم'),term:'Side-lying',task:pair('Help the manikin turn toward you and rest with supported alignment.','ساعد الدمية على التقليب نحوك والاستقرار مع محاذاة مدعومة.')},prone:{title:pair('Supine → prone','من الاستلقاء الظهري إلى الانبطاح'),subtitle:pair('A staged turn with face and arm checks','تقليب على مراحل مع فحص الوجه والذراع'),term:'Prone',task:pair('Practise a proposed staged prone turn. Protect the arm and face at the intermediate pause.','تدرّب على التقليب المقترح إلى الانبطاح على مراحل. احمِ الذراع والوجه أثناء التوقف الوسطي.')},slide:{title:pair('Toward the side of the bed','التحريك نحو جانب السرير'),subtitle:pair('Coordinate two small aligned slides','نسّق إزاحتين صغيرتين مع المحاذاة'),term:'Lateral repositioning',task:pair('Move the manikin a small distance toward you in two coordinated stages, keeping the body aligned and clear of the edge.','حرّك الدمية مسافة صغيرة نحوك على مرحلتين منسقتين، مع الحفاظ على المحاذاة والابتعاد عن الحافة.')}};
const objects={patient:pair('Patient / manikin','المريض / الدمية'),body:pair('Movement & grip','الحركة والإمساك'),farArm:pair('Far arm','الذراع البعيدة'),nearArm:pair('Near arm','الذراع القريبة'),leg:pair('Far leg','الساق البعيدة'),head:pair('Head & face','الرأس والوجه'),bed:pair('Bed controls','أدوات السرير'),sink:pair('Hand hygiene','نظافة اليدين'),pillows:pair('Pillows','الوسائد'),sheet:pair('Aid & helper','الوسيلة والمساعد'),curtain:pair('Privacy curtain','ستارة الخصوصية'),stance:pair('Your stance','وقفتك'),bell:pair('Call bell','زر النداء'),support_arm:pair('Support the arm','دعم الذراع'),support_leg:pair('Support the legs','دعم الساقين'),support_back:pair('Support the back','دعم الظهر')};
const sim=new Simulation(scenario,mode);window.addEventListener('error',()=>{$('location').textContent=text('Please reload if controls stop responding','أعد التحميل إذا توقفت أدوات التحكم');});
const room=new Room($('scene'),()=>sim.s,updateHotspots);room.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const hotspotElements={};
for(const id of Object.keys(objects)){const b=document.createElement('button');b.className='hotspot';b.dataset.object=id;b.innerHTML='<i>+</i><span></span>';b.onclick=()=>{if(id.startsWith('support_')){dispatch('place',id.slice(8));select(id);}else select(id,true);};$('hotspots').append(b);hotspotElements[id]=b;}
function updateHotspots(spots){const detail=['patient','body','farArm','nearArm','leg','head'].includes(selected),s=sim.s;for(const el of Object.values(hotspotElements))el.hidden=true;
 const placed=[];
 for(const spot of spots){const el=hotspotElements[spot.id];if(!el)continue;const p=room.project(spot.p),dist=Math.hypot(spot.p[0]-room.camera.x,spot.p[2]-room.camera.z);
  if(!started||!showLabels||p.z<.2||p.x<14||p.x>room.w-14||p.y<55||p.y>room.h-20)continue;
  if(spot.detail&&(!detail||dist>2.4))continue;
  if(spot.support&&(!s.held||s.progress<1||s.supports[spot.id.slice(8)]||!sim.supportKeys().includes(spot.id.slice(8))))continue;
  if(s.held&&!spot.support&&spot.id!=='pillows'&&spot.id!=='body')continue;
  let x=p.x,y=p.y;if(spot.detail){const offsets={farArm:[40,-30],nearArm:[-30,26],body:[0,-32],head:[0,-30],leg:[20,22]};x+=(offsets[spot.id]||[0,0])[0];y+=(offsets[spot.id]||[0,0])[1];}
  const mini=dist>2.8||(!spot.detail&&detail&&!['patient','bed','stance'].includes(spot.id));
  x=Math.max(mini?18:55,Math.min(room.w-(mini?18:55),x));y=Math.max(56,Math.min(room.h-23,y));
  if(!mini){for(let i=0;i<3&&placed.some(q=>Math.abs(q[0]-x)<90&&Math.abs(q[1]-y)<33);i++)y+=34;}
  if(y>room.h-25)continue;placed.push([x,y]);el.hidden=false;el.style.left=x+'px';el.style.top=y+'px';el.className='hotspot'+(spot.id===selected?' selected':'')+(spot.support?' support':'')+(mini?' mini':'')+(spot.id===highlight?' highlight':'');el.querySelector('span').textContent=t(objects[spot.id]);el.setAttribute('aria-label',t(objects[spot.id]));el.title=t(objects[spot.id]);
 }
 const c=$('stanceCanvas');if(c)room.drawStance(c,{...s,...room.preview});
}
function staticLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-en]').forEach(el=>{const v=el.dataset[lang];if(v!==undefined)el.textContent=v.replaceAll('\\n','\n');});$('language').innerHTML=lang==='en'?'العربية <span>EN</span>':'English <span>ع</span>';$('language').setAttribute('aria-label',lang==='en'?'Switch to Arabic':'التبديل إلى الإنجليزية');$('scene').setAttribute('aria-label',text('3D room. Drag to look around. W A S D to walk. Arrow keys move or turn. Select labelled objects.','غرفة ثلاثية الأبعاد. اسحب للنظر. استخدم W A S D للمشي أو مفاتيح الأسهم للحركة. اختر العناصر المسماة.'));renderCases();updateHeader();renderInspector();if(sim.last&&!$('coach').hidden)showFeedback(sim.last);}
function renderCases(){$('caseOptions').innerHTML=Object.entries(cases).map(([id,c],i)=>`<button class="case-option ${scenario===id?'chosen':''}" data-case="${id}" aria-pressed="${scenario===id}"><span class="case-number">0${i+1}</span><span><strong>${esc(t(c.title))}</strong><small>${esc(t(c.subtitle))}</small></span></button>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{scenario=b.dataset.case;renderCases();});document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('chosen',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode);b.onclick=()=>{mode=b.dataset.mode;renderCases();};});}
function updateHeader(){const s=sim.s;$('scenarioTitle').textContent=t(cases[s.scenario].title);$('modeLabel').textContent=text(`${s.mode==='learn'?'PRACTICE':'CHALLENGE'} · MODULE 05`,`${s.mode==='learn'?'الممارسة':'التحدي'} · الوحدة ٠٥`);$('hintBtn').hidden=s.mode==='challenge';const phases=[pair('Meet and prepare','تعارف وتحضير'),pair('Prepare the body','تجهيز الجسم'),pair('Coordinate the team','تنسيق الفريق'),pair('Control the movement','ضبط الحركة'),pair('Support the new position','دعم الوضع الجديد'),pair('Reassess and finish','إعادة التقييم والإنهاء'),pair('Attempt complete','اكتملت المحاولة')];const guide=[pair('Approach the manikin. Establish a shared plan and prepare for safe contact.','اقترب من الدمية. ضع خطة مشتركة واستعد للمس الآمن.'),pair('Prepare the room, assistance and individual limbs. Independent preparation may occur in different orders.','جهّز الغرفة والمساعدة والأطراف. يمكن تغيير ترتيب إجراءات التحضير المستقلة.'),pair('Check your stance and grip. Agree on a count, then move together.','تحقق من الوقفة والإمساك. اتفق على العد ثم تحركوا معاً.'),pair('Use the movement handle. Keep the body aligned and pause when prompted.','استخدم مقبض الحركة. حافظ على المحاذاة وتوقف عند الحاجة.'),pair('Collect pillows and place them at the unsupported areas.','خذ الوسائد وضعها في المواضع غير المدعومة.'),pair('Review the patient and return the environment to a safe resting state.','أعد فحص المريض وأعد البيئة إلى وضع آمن للراحة.'),pair('Open your debrief or begin a fresh attempt.','افتح مراجعة المحاولة أو ابدأ محاولة جديدة.')];const ph=sim.phase();$('goal').innerHTML=`<strong>${esc(text('CURRENT FOCUS','التركيز الحالي'))} · ${esc(t(phases[ph]))}</strong>${esc(t(s.mode==='challenge'?cases[s.scenario].task:guide[ph]))}`;}
function select(id,approach=false){selected=id;highlight='';room.selected=id;if(approach)room.focus(id.startsWith('support_')?'body':id);renderInspector();$('location').textContent=t(objects[id]||pair('ROOM 01','الغرفة ٠١')).toUpperCase();}
function action(key,en,ar,{value,done=false,warn=false}={}){return `<button class="action${done?' done':''}${warn?' warn':''}" data-action="${key}"${value!==undefined?` data-value="${esc(value)}"`:''}>${esc(text(en,ar))}</button>`;}
function range(key,en,ar,left,right,value=sim.s[key],max=100){return `<div class="range-row"><label class="range-label" for="range-${key}"><span>${esc(text(en,ar))}</span><output id="out-${key}">${Math.round(value)}${key==='move'?'%':''}</output></label><input type="range" id="range-${key}" data-range="${key}" min="0" max="${max}" value="${value}" step="1"><div class="range-ends"><span>${esc(t(left))}</span><span>${esc(t(right))}</span></div></div>`;}
function partButtons(){return `<div class="part-grid">${['farArm','nearArm','leg','head'].map(k=>`<button data-select="${k}">${esc(t(objects[k]))}${lang==='ar'?`<span class="term">${esc(objects[k].en)}</span>`:''}</button>`).join('')}</div>`;}
function renderInspector(){const s=sim.s;let body='',sub='',term='',ref='';
 if(!selected){$('objectContent').innerHTML=`<div class="empty-state"><div class="object-kicker">${esc(text('YOUR CLINICAL SPACE','مساحتك السريرية'))}</div><h2 class="object-title">${esc(text('Look. Approach. Act.','انظر. اقترب. نفّذ.'))}</h2><div class="empty-visual">↗</div><p class="object-sub">${esc(t(cases[s.scenario].task))}</p><ol><li>${esc(text('Drag the room to look around. Walk with the arrows or W A S D.','اسحب الغرفة للنظر. امشِ بالأسهم أو W A S D.'))}</li><li>${esc(text('Tap an object in the room. Its controls appear here.','المس عنصراً في الغرفة؛ تظهر أدواته هنا.'))}</li><li>${esc(text('Manipulate limbs and movement handles. Observe the result.','حرّك الأطراف ومقابض الحركة وراقب النتيجة.'))}</li></ol><span class="review-pill">${esc(text('Training manikin · proposed adaptations','دمية تدريب · تعديلات مقترحة'))}</span></div>`;return;}
 const title=objects[selected]||pair('Clinical skills','المهارات السريرية');
 if(selected==='patient'){
  sub=text('An adult male training manikin. Begin with communication and a movement assessment.','دمية تدريب لرجل بالغ. ابدأ بالتواصل وتقييم الحركة.');term='Patient preparation';
  body=`<div class="object-actions">${action('talk','Explain & obtain agreement','اشرح واحصل على الموافقة',{done:s.talk})}${action('assess','Assess movement & assistance','قيّم الحركة والمساعدة',{done:s.assess})}${action('comfort','Recheck alignment & comfort','أعد فحص المحاذاة والراحة',{done:s.comfort})}</div><div class="section-label">${esc(text('INTERACT WITH THE BODY','تفاعل مع الجسم'))}</div>${partButtons()}<button class="action" data-select="body">${esc(text('Approach the movement zone','اقترب من منطقة التحريك'))}</button>`;ref='S5 / S6 step 1 + A01 / A05';
 }
 if(['farArm','nearArm','leg','head'].includes(selected)){
  const spec={farArm:[pair('Move the far arm across the chest. Support it throughout.','حرّك الذراع البعيدة عبر الصدر مع دعمها طوال الحركة.'),pair('Alongside','بجانب الجسم'),pair('Across chest','عبر الصدر')],nearArm:[pair('Keep the near arm supported and clear of the rolling trunk. For the second prone stage, move it fully clear.','أبقِ الذراع القريبة مدعومة وبعيدة عن الجذع المتقلب. قبل المرحلة الثانية للانبطاح أبعدها تماماً.'),pair('Trapped / under side','منحشرة / تحت الجانب'),pair('Supported & clear','مدعومة وبعيدة')],leg:[s.scenario==='slide'?pair('Align the legs with the trunk before the lateral slide.','حاذِ الساقين مع الجذع قبل الإزاحة الجانبية.'):pair('For this unrestricted manikin, guide the far leg across the near leg. Do not force a joint.','لهذه الدمية دون قيود، وجّه الساق البعيدة عبر القريبة. لا تجبر المفصل.'),pair('Unprepared','غير مجهزة'),s.scenario==='slide'?pair('Aligned','على استقامة'):pair('Prepared across','مجهزة عبر القريبة')],head:[pair('Rotate the head gently so the face stays clear during the prone transition. Inspect its position again afterward.','أدر الرأس بلطف ليبقى الوجه دون ضغط أثناء الانتقال إلى الانبطاح، وافحصه مجدداً بعد الحركة.'),pair('Face up / neutral','الوجه لأعلى / محايد'),pair('Turned & face clear','ملتفت والوجه دون ضغط')]};
  const d=spec[selected];sub=t(d[0]);term=objects[selected].en;body=range(selected,text('Position control',''),text('','التحكم بالوضع'),d[1],d[2])+`<div class="tech-note">${esc(text('Near and far are anchored to your working side of the bed. Looking around does not reverse the labels.','القريب والبعيد مرتبطان بجانب عملك من السرير. تغيير اتجاه النظر لا يعكس التسميات.'))}</div>${partButtons()}<button class="action" data-select="body">${esc(text('Return to movement & grip','العودة إلى الحركة والإمساك'))}</button>`;ref=selected==='nearArm'?'S5 / S6 steps 3,9 · R19':selected==='head'?'S5 / S6 step 13 · R20':'S5 / S6 limb preparation';
  const failures=s.log.filter(e=>e.key===selected&&!e.ok).length;if(s.mode==='learn'&&failures>=2)body+=`<button class="secondary" data-demo="${selected}">${esc(text('Show this movement','اعرض هذه الحركة'))}</button>`;
 }
 if(selected==='bed'){
  sub=text('Set up for work, then return the bed low at the end of care.','جهّز السرير للعمل ثم أعده منخفضاً عند انتهاء الرعاية.');term='Bed safety';
  body=`<div class="object-actions">${action('brakes','Lock wheel brakes','ثبّت مكابح العجلات',{done:s.brakes})}${action('rail','Secure far-side protection','أمّن الجانب البعيد',{done:s.rail})}</div>${range('height','Bed height','ارتفاع السرير',pair('Low for rest','منخفض للراحة'),pair('High','مرتفع'))}<div class="tech-note">${esc(text('Use a comfortable working height. In this manikin model the working zone is 55–85 and the resting zone is 0–40. These are interface units, not centimetres.','استخدم ارتفاعاً مريحاً للعمل. نطاق العمل في النموذج ٥٥–٨٥ ونطاق الراحة ٠–٤٠. هذه وحدات للواجهة وليست سنتيمترات.'))}</div>`;ref='A02 / A05 · proposed safety additions';
 }
 if(selected==='sink'){
  sub=text('Use the sink station for the hand-hygiene prerequisite.','استخدم محطة المغسلة لمتطلب نظافة اليدين.');term='Hand hygiene';
  body=`<div class="tech-note">${esc(text('The full handwashing technique is mapped for Module 1. This button records completion of that prerequisite; it does not certify your handwashing performance.','رُسمت تقنية غسل اليدين الكاملة للوحدة الأولى. يسجل هذا الزر إكمال المتطلب السابق ولا يعتمد أداءك في غسل اليدين.'))}</div><div class="object-actions">${action('hygiene',s.contact&&s.progress>=1?'Record post-contact hand hygiene':'Record completed hand hygiene',s.contact&&s.progress>=1?'سجّل نظافة اليدين بعد اللمس':'سجّل إكمال نظافة اليدين',{done:s.post||s.hygiene&&!s.contact})}</div><div class="help-step"><b>${esc(text('Before contact and after care','قبل اللمس وبعد الرعاية'))}</b><p>${esc(text('Gloves do not replace hand hygiene. This task has no simulated body-fluid exposure requiring routine gloves.','القفازات لا تستبدل نظافة اليدين. لا تتضمن المهمة تعرضاً افتراضياً لسوائل الجسم يتطلب القفازات بشكل روتيني.'))}</p></div>`;ref='S5 / S6 step 1 · A06';
 }
 if(selected==='sheet'){
  sub=text('The friction-reducing sheet is already positioned under the manikin. Confirm the plan and bring the trained helper to the far side.','ملاءة تقليل الاحتكاك موجودة تحت الدمية بالفعل. تحقق من الخطة وأحضر المساعد المدرب إلى الجانب البعيد.');term='Assistance & handling aid';body=`<div class="object-actions">${action('helper','Bring trained helper','أحضر مساعداً مدرباً',{done:s.helper})}${action('sheet','Inspect prepared sheet & plan','افحص الملاءة المجهزة والخطة',{done:s.sheet})}</div><div class="tech-note">${esc(text('Proposed adaptation: this prototype does not reward manual shoulder pulling or lifting a dependent adult by hand. Faculty must approve the local device, staffing and exact method.','تعديل مقترح: لا يعتمد النموذج شد الكتف يدوياً أو رفع بالغ معتمد على الآخرين باليدين. يجب اعتماد الجهاز والمساعدة والطريقة محلياً.'))}</div>`;ref='R13 / R17 / R21 · NIOSH E2';
 }
 if(selected==='curtain'){sub=text('Preserve dignity before the maneuver.','احفظ الكرامة قبل المناورة.');term='Privacy';body=`<div class="object-actions">${action('privacy','Close the bedside curtain','أغلق ستارة السرير',{done:s.privacy})}</div>`;ref='A02';}
 if(selected==='bell'){sub=text('Place the call bell where the patient can reach it after repositioning.','ضع زر النداء في مكان يستطيع المريض الوصول إليه بعد التحريك.');term='Call bell';body=`<div class="object-actions">${action('bell','Place within reach','ضعه في المتناول',{done:s.bell})}</div>`;ref='A05';}
 if(selected==='stance'){
  sub=text('See your posture as you adjust your feet, knees and trunk. The red area identifies strain from poor alignment.','راقب وضعيتك أثناء ضبط القدمين والركبتين والجذع. تحدد المنطقة الحمراء الإجهاد الناتج عن سوء المحاذاة.');term='Body mechanics';body=`<canvas id="stanceCanvas" class="stance-canvas" width="270" height="215" aria-label="Nurse posture preview with lumbar highlight"></canvas>${range('feet','Stable foot placement','وضع ثابت للقدمين',pair('Narrow','ضيّق'),pair('Very wide','واسع جداً'))}${range('knees','Knee flexion','ثني الركبتين',pair('Locked','مستقيمتان'),pair('Deep bend','ثني عميق'))}${range('twist','Trunk twist','التواء الجذع',pair('Facing movement','مواجهة الحركة'),pair('Twisted','ملتوي'))}<div class="tech-note">${esc(text('The control values are demonstration units. Aim for a balanced stance, slightly flexed knees and no twist. Good mechanics support an assessed handling plan; they do not replace equipment.','قيم التحكم وحدات للعرض. اتخذ وقفة متوازنة وركبتين مثنيتين قليلاً دون التواء. تدعم ميكانيكا الجسم خطة التحريك المقيّمة ولا تستبدل المعدات.'))}</div>`;ref='S4 steps 1,4 · A04';
 }
 if(selected==='body'){
  const cap=s.scenario==='side'||s.pauseChecked?100:50;sub=text('Place your hands, coordinate the team, then move the handle gradually. Release to pause.','ضع يديك ونسّق الفريق ثم حرّك المقبض تدريجياً. اتركه للتوقف.');term=s.scenario==='slide'?'Lateral slide':'Controlled turn';
  body=`<div class="section-label">${esc(text('HAND PLACEMENT','موضع اليدين'))}</div><div class="object-actions">${action('grip','Grasp upper & lower sheet zones','أمسك منطقتي الملاءة العليا والسفلى',{value:'sheet',done:s.grip==='sheet'})}${action('grip','Pull directly at shoulder / hip','اسحب الكتف / الورك مباشرة',{value:'shoulder',warn:true})}${action('grip','Lift with hands under the body','ارفع باليدين تحت الجسم',{value:'under',warn:true})}</div>`;
  if(s.progress===.5&&s.scenario!=='side'&&!s.pauseChecked){body+=`<div class="tech-note">${esc(text(s.scenario==='prone'?'Pause here. Clear the near arm fully and turn the head before the second half.':'Pause here. Inspect the lower-body alignment before regripping for the second small slide.',s.scenario==='prone'?'توقف هنا. أبعد الذراع القريبة تماماً وأدر الرأس قبل النصف الثاني.':'توقف هنا. افحص محاذاة الجزء السفلي قبل إعادة الإمساك للإزاحة الصغيرة الثانية.'))}</div>${s.scenario==='prone'?partButtons():''}<div class="object-actions">${action('checkPause',s.scenario==='prone'?'Inspect arm & face clearance':'Inspect legs & trunk alignment',s.scenario==='prone'?'افحص خلو الذراع والوجه':'افحص محاذاة الساقين والجذع')}</div>`;}
  body+=`<div class="counter"><strong aria-label="Count ${s.count}">${[1,2,3].map(n=>n<=s.count?n:'·').join(' ')}</strong><button data-action="count">${esc(text('Count aloud','عُدّ بصوت مسموع'))}</button></div>`;
  body+=range('move',s.scenario==='slide'?'Slide the supported body':'Turn the supported body',s.scenario==='slide'?'أزح الجسم المدعوم':'قلّب الجسم المدعوم',pair('Starting position','وضع البداية'),pair(cap===50?'Intermediate pause':'Final position',cap===50?'توقف وسطي':'الوضع النهائي'),s.progress*100,cap);
  body+=`<div class="status-line">${esc(text(`Movement: ${Math.round(s.progress*100)}% · a new count is required after each preparation change.`,`الحركة: ${Math.round(s.progress*100)}٪ · يلزم عد جديد بعد كل تغيير في التحضير.`))}</div><button class="action" data-select="stance">${esc(text('Check my stance','افحص وقفتي'))}</button>`;ref='S5 / S6 steps 5–6,11–12,14–17 · R17 / R20 / R21';
 }
 if(selected==='pillows'||selected.startsWith('support_')){
  term='Positioning support';sub=text('Pick up a pillow, then touch the appropriate support target on the manikin. The pillow changes the visible support.','خذ وسادة ثم المس موضع الدعم المناسب على الدمية. تغيّر الوسادة الدعم المرئي.');body=`<div class="object-actions">${s.held?action('putdown','Return pillow to trolley','أعد الوسادة إلى العربة'):action('pickup','Pick up a pillow','خذ وسادة')}</div>`;
  if(s.held){body+=`<div class="tech-note">${esc(text('A pillow is in your hands. Return to the bedside and place it at the arm, leg or back target.','توجد وسادة بين يديك. عد إلى جانب السرير وضعها عند موضع الذراع أو الساق أو الظهر.'))}</div><button class="action" data-select="body">${esc(text('Approach the patient with pillow','اقترب من المريض بالوسادة'))}</button>`;}
  if(s.progress>=1)body+=`<div class="section-label">${esc(text('SUPPORT TARGETS','مواضع الدعم'))}</div><div class="object-actions">${sim.supportKeys().map(k=>action('place',s.scenario==='prone'&&k==='leg'?'Support the ankles / toes':objects['support_'+k].en,s.scenario==='prone'&&k==='leg'?'ادعم الكاحلين / أصابع القدم':objects['support_'+k].ar,{value:k,done:s.supports[k]})).join('')}</div>`;
  ref='S5 / S6 step 7 · R18 / A05';
 }
 $('objectContent').innerHTML=`<div class="object-kicker">${esc(text('AT THE BEDSIDE','بجانب السرير'))}</div><h2 class="object-title">${esc(t(title))}</h2>${lang==='ar'?`<span class="term">${esc(term)}</span>`:''}<p class="object-sub">${esc(sub)}</p>${body}<div class="source-ref">${esc(text('Curriculum reference: ','مرجع المنهج: ')+ref)}</div>`;
 bindInspector();
}
function bindInspector(){document.querySelectorAll('#objectContent [data-action]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action,b.dataset.value));document.querySelectorAll('#objectContent [data-select]').forEach(b=>b.onclick=()=>select(b.dataset.select,true));document.querySelectorAll('#objectContent [data-demo]').forEach(b=>b.onclick=()=>{const k=b.dataset.demo;sim.s.assisted.push(k);dispatch(k,k==='head'?75:100);showFeedback({category:'incomplete',text:pair('Demonstration shown for this one movement. It is recorded as assisted. Try it yourself on your next attempt.','عُرضت هذه الحركة فقط. سُجلت بمساعدة. جرّبها بنفسك في المحاولة التالية.')});});
 document.querySelectorAll('#objectContent [data-range]').forEach(input=>{const key=input.dataset.range;input.oninput=()=>{const v=Number(input.value);$('out-'+key).textContent=Math.round(v)+(key==='move'?'%':'');if(key==='move'){// Do not preview a load unless every prerequisite is satisfied.
    const s=sim.s;if(s.count===3&&s.brakes&&s.rail&&s.helper&&s.sheet&&sim.isReadyLimbs()&&sim.isReadyStance()&&s.grip==='sheet'&&s.height>=55&&s.height<=85&&!s.held)room.preview.progress=Math.max(s.progress,v/100);
   }else room.preview[key]=v;};input.onchange=()=>{room.preview={};dispatch(key==='move'?'move':key,key==='move'?Number(input.value)/100:Number(input.value));};});}
function dispatch(key,value){const scroll=$('objectContent').scrollTop,focusId=document.activeElement?.id;const result=sim.do(key,value);room.preview={};updateHeader();if(result.debrief){showDebrief();return;}showFeedback(result);renderInspector();$('objectContent').scrollTop=scroll;if(focusId?.startsWith('range-'))$(focusId)?.focus({preventScroll:true});return result;}
function showFeedback(e){if(!e?.category)return;const s=sim.s;$('coach').hidden=false;$('coach').dataset.type=e.category;$('coachCategory').textContent=t(labels[e.category]);let content=t(e.text);if(s.mode==='challenge'&&e.category!=='safety')content=text('Action recorded. Continue the task; the detailed rationale is saved for your debrief.','سُجّل الإجراء. تابع المهمة؛ حُفظ المبرر المفصل لمراجعة المحاولة.');$('coachText').textContent=content;}
function start(){sim.reset(scenario,mode);selected='';highlight='';started=true;room.preview={};room.focus('room');$('coach').hidden=true;$('welcome').close();updateHeader();renderInspector();}
function openWelcome(){scenario=sim.s.scenario;mode=sim.s.mode;renderCases();$('welcome').showModal();}
function info(kind){let html='';if(kind==='help'){html=`<div class="eyebrow">${esc(text('ROOM CONTROLS','التحكم بالغرفة'))}</div><h2>${esc(text('Find your way around','استكشف المكان'))}</h2>`;const rows=[['Look around','Drag an empty part of the room. Arrow left/right also turn the view.','انظر حولك','اسحب جزءاً فارغاً من الغرفة. الأسهم يميناً ويساراً تغيّر اتجاه النظر أيضاً.'],['Walk','W A S D, the on-screen arrow pad or mouse wheel. Bed collisions keep you outside the mattress.','امشِ','استخدم W A S D أو الأسهم على الشاشة أو عجلة الفأرة. تمنع حدود السرير المرور داخل الفراش.'],['Approach and interact','Tap an object label or a station shortcut. Adjust the controls while watching the physical change.','اقترب وتفاعل','المس تسمية عنصر أو اختصار محطة. اضبط الأدوات وأنت تراقب التغير الجسدي.'],['Control the maneuver','Prepare each limb. Choose stance and grip. Count three times, then drag the movement handle.','اضبط المناورة','جهّز كل طرف. اضبط الوقفة والإمساك. عُدّ ثلاث مرات ثم اسحب مقبض الحركة.'],['Keyboard and touch','Tab to object buttons and controls. Use left/right keys on a selected slider. Every drag has a keyboard control.','لوحة المفاتيح واللمس','انتقل بزر Tab إلى العناصر والأدوات. استخدم الأسهم على شريط التحكم المحدد. لكل سحب بديل بلوحة المفاتيح.']];html+=rows.map(r=>`<div class="help-step"><b>${esc(text(r[0],r[2]))}</b><p>${esc(text(r[1],r[3]))}</p></div>`).join('');}
 if(kind==='faculty'){html=`<div class="eyebrow">${esc(text('SOURCE TRANSPARENCY','شفافية المصادر'))}</div><h2>${esc(text('Faculty review before student release','مراجعة التدريس قبل إتاحته للطلاب'))}</h2><p>${esc(text('The two Turning and Moving documents contain the same 17 procedure steps. The scored copy adds assessment columns. Neither includes rationales. All rationales in this module are identified educational additions.','تحتوي نسختا التقليب والتحريك على الخطوات الإجرائية الـ١٧ نفسها. تضيف النسخة التقييمية أعمدة الدرجات. لا تتضمن أي منهما المبررات؛ مبررات هذه الوحدة إضافات تعليمية موضحة.'))}</p><span class="review-pill">${esc(text('Manikin demonstration · not a validated competency assessment','عرض على دمية · ليس تقييماً معتمداً للكفاءة'))}</span>`;
  const rows=[['R15 · Safety preparation','Added assessment, consent, brakes, height, privacy, far-side protection and final checks. These are not listed in the source checklist.','أُضيف التقييم والموافقة والمكابح والارتفاع والخصوصية وحماية الجانب البعيد والفحوص النهائية. لا ترد هذه في قائمة المصدر.'],['R17 / R21 · Handling method','Source: hands at shoulder/hip or under the body. Proposed representation: prepared friction-reducing sheet, trained helper and controlled whole-body movements. Exact local method and staffing need approval.','المصدر: اليدان عند الكتف والورك أو تحت الجسم. التمثيل المقترح: ملاءة مجهزة لتقليل الاحتكاك ومساعد مدرب وحركات مضبوطة للجسم كوحدة. تحتاج الطريقة والمساعدة إلى اعتماد محلي.'],['R19 / R20 · Prone transition','The source places the near arm under the side and turns the head after the roll. The prototype blocks arm entrapment and requires face clearance before the final prone stage. Faculty must demonstrate and validate this adaptation.','يضع المصدر الذراع القريبة تحت الجانب ويدير الرأس بعد التقليب. يمنع النموذج انحشار الذراع ويشترط خلو الوجه قبل المرحلة النهائية. يلزم عرض التعديل واعتماده من التدريس.'],['R18 · Supports','The source specifies arm/leg pillows after side-lying. Head, back, comfort and finishing checks are explicit proposed additions.','يحدد المصدر وسائد الذراع والساق بعد الوضع الجانبي. فحوص الرأس والظهر والراحة والإنهاء إضافات مقترحة.'],['A06 · Hand hygiene','Hand hygiene is an acknowledged prerequisite here. Full visible washing, timing and coverage are designed for Module 1 and are not certified by this prototype.','نظافة اليدين متطلب يُسجل هنا. خُطط لتقنية الغسل المرئية والوقت والتغطية في الوحدة الأولى، ولا يعتمدها هذا النموذج.']];
  html+=rows.map(r=>`<div class="review-row"><h3>${esc(r[0])}</h3><p>${esc(text(r[1],r[2]))}</p></div>`).join('');html+=`<p>${esc(text('The complete curriculum map contains 78 mapped entries and 28 faculty-review items across all six modules. English–Arabic terminology also needs faculty review.','تحتوي خريطة المنهج الكاملة على ٧٨ بنداً و٢٨ موضوعاً للمراجعة عبر الوحدات الست. تحتاج المصطلحات الإنجليزية والعربية أيضاً إلى مراجعة التدريس.'))}</p><p><a href="curriculum-review.html" target="_blank" rel="noopener">${esc(text('Open the full source map and review register','افتح خريطة المصادر وسجل المراجعة الكامل'))} ↗</a></p><p><a href="https://www.cdc.gov/niosh/docs/2006-117/pdfs/2006-117.pdf" target="_blank" rel="noopener">NIOSH · Safe lifting and movement</a></p>`;
 }
 if(kind==='curriculum'){const modules=[['Medical handwashing','الغسل الطبي لليدين','Visible hand surfaces, water, soap, friction, rinsing, drying and contamination.','أسطح اليدين والماء والصابون والفرك والشطف والتجفيف والتلوث.'],['Clean gloving','ارتداء القفازات النظيفة','Donning and peeling with inner/outer-surface contamination tracking.','ارتداء ونزع مع تتبع تلوث السطح الداخلي والخارجي.'],['Range of motion','مدى الحركة','Sixteen movements with a starting pose, joint manipulation and final pose.','ست عشرة حركة مع وضع بداية وتحريك المفصل ووضع نهائي.'],['Body mechanics','ميكانيكا الجسم','Visible posture during lifting, reaching, pivoting, trolley movement and sitting.','وضعية مرئية أثناء الرفع والوصول والدوران وتحريك العربة والجلوس.'],['Turning and moving','تقليب المريض وتحريكه','Three connected manikin practices with physical preparation and feedback.','ثلاثة تدريبات على دمية مع تحضير جسدي وتغذية راجعة.'],['Patient positioning','وضعيات المريض','Build positions using bed angles, body orientation, joints and supports.','كوّن الوضعيات بزوايا السرير واتجاه الجسم والمفاصل والدعامات.']];html=`<div class="eyebrow">${esc(text('A CONNECTED CURRICULUM','منهج مترابط'))}</div><h2>${esc(text('Six skills. One shared lab.','ست مهارات في مختبر واحد.'))}</h2><p>${esc(text('Module 5 is the implemented proof of concept. The other modules have source maps and interaction designs; they are not yet playable.','الوحدة الخامسة هي النموذج المنفّذ. للوحدات الأخرى خرائط مصادر وتصاميم تفاعل، لكنها غير قابلة للتشغيل بعد.'))}</p>`+modules.map((m,i)=>`<div class="module-row"><span>0${i+1}</span><div><strong>${esc(text(m[0],m[1]))}</strong><p>${esc(text(m[2],m[3]))}</p></div><small>${esc(i===4?text('PLAYABLE','قابلة للتشغيل'):text('MAPPED','مخططة'))}</small></div>`).join('');}
 $('infoBody').innerHTML=html;$('infoDialog').showModal();}
function showDebrief(){const data=sim.export(),s=sim.s,om=data.omitted,events=s.log;const unique=(category)=>[...new Map(events.filter(e=>e.category===category).map(e=>[e.key,e])).values()];const eventsHtml=(arr,empty)=>arr.length?arr.map(e=>`<div class="debrief-event"><b>${esc(t(labels[e.category]))}</b><p>${esc(t(e.text))}</p><small>${esc(text('Source / proposal: ','المصدر / المقترح: ')+e.source)}</small></div>`).join(''):`<p>${esc(empty)}</p>`;
 const good=[...new Map(events.filter(e=>e.ok&&!['count','pickup','putdown','pause'].includes(e.key)).map(e=>[e.key,e])).values()];const title=text(s.complete?'Your movement, understood.':'Pause and reflect.',s.complete?'افهم أثر حركتك.':'توقف وراجع.');
 const finalText=s.complete?text('The manikin reached the intended posture and the finishing checks were completed. Review the decisions and corrections from this attempt.','وصلت الدمية إلى الوضع المطلوب واكتملت فحوص الإنهاء. راجع القرارات والتصحيحات في هذه المحاولة.'):text('This attempt has unfinished outcomes. You can return to the same room or start a clean attempt.','توجد نتائج غير مكتملة في هذه المحاولة. يمكنك العودة إلى الغرفة نفسها أو بدء محاولة جديدة.');
 const section=(title,content,wide=false)=>`<section class="debrief-section${wide?' wide':''}"><h3>${esc(t(title))}</h3>${content}</section>`;
 $('debriefBody').innerHTML=`<div class="debrief-top"><div><div class="eyebrow">${esc(text('EDUCATIONAL DEBRIEF','مراجعة تعليمية'))} · ${esc(t(cases[s.scenario].title))}</div><h2>${esc(title)}</h2><p>${esc(finalText)}</p></div><span class="review-pill">${esc(text(s.mode==='learn'?'Practice attempt':'Challenge attempt',s.mode==='learn'?'محاولة ممارسة':'محاولة تحدٍ'))}</span></div><div class="debrief-grid">${section(pair('What you did well','ما أديته جيداً'),good.length?`<ul>${good.map(e=>`<li>${esc(t(e.text))}</li>`).join('')}</ul>`:`<p>${esc(text('No completed actions recorded yet.','لم تسجل إجراءات مكتملة بعد.'))}</p>`)}${section(pair('Steps omitted / unfinished','الخطوات المحذوفة أو غير المكتملة'),om.length?`<ul>${om.map(o=>`<li><b>${esc(t(o.label))}</b><br>${esc(t(o.why))}</li>`).join('')}</ul>`:`<p>${esc(text('No required outcomes remain unfinished.','لم تبقَ نتائج مطلوبة غير مكتملة.'))}</p>`)}${section(pair('Sequence problems and why they matter','مشكلات التسلسل وأهميتها'),eventsHtml(unique('sequence'),text('No sequencing problems recorded.','لم تسجل مشكلات في التسلسل.')))}${section(pair('Technique problems and why they matter','مشكلات الطريقة وأهميتها'),eventsHtml(unique('technique'),text('No technique errors recorded.','لم تسجل أخطاء في الطريقة.')))}${section(pair('Safety-critical errors','أخطاء مؤثرة في السلامة'),eventsHtml(unique('safety'),text('No safety stops recorded.','لم تسجل توقفات للسلامة.')),true)}${section(pair('Acceptable alternatives / unnecessary actions','بدائل مقبولة / إجراءات غير ضرورية'),eventsHtml([...unique('alternative'),...unique('unnecessary')],text('None recorded.','لم يسجل شيء.')))}${section(pair('What to do differently next time','ما الذي تغيره في المرة المقبلة'),`<p>${esc(text('Prepare before loading. Use the whole-body handling plan, a stable stance and a shared count. Recheck the new position and every support. Practise again without guidance when ready.','جهّز قبل نقل الوزن. استخدم خطة تحريك الجسم كوحدة ووقفة ثابتة وعداً مشتركاً. أعد فحص الوضع الجديد وكل دعامة. أعد الممارسة دون إرشاد عندما تستعد.'))}</p>${s.assisted.length?`<p>${esc(text('Demonstrated with assistance: ','عُرض بمساعدة: ')+s.assisted.map(k=>t(objects[k]||k)).join(', '))}</p>`:''}`)}</div><div class="debrief-buttons"><button class="primary" id="retryBtn">${esc(text('Try again · fresh attempt','حاول مجدداً · محاولة جديدة'))}</button><button class="secondary" id="continueBtn">${esc(text('Return to the room','العودة إلى الغرفة'))}</button><button class="secondary" id="exportBtn">${esc(text('Download debrief','تنزيل المراجعة'))}</button><button class="text-button" id="caseBtn">${esc(text('Choose another scenario','اختر حالة أخرى'))}</button></div><p class="status-line">${esc(text('No numerical grade. Successful clicks alone do not demonstrate a completed maneuver. This is a faculty-review prototype.','لا توجد درجة رقمية. النقرات الناجحة وحدها لا تثبت إكمال المناورة. هذا نموذج قيد مراجعة التدريس.'))}</p>`;
 $('retryBtn').onclick=()=>{$('debriefDialog').close();scenario=s.scenario;mode=s.mode;start();};$('continueBtn').onclick=()=>{$('debriefDialog').close();};$('caseBtn').onclick=()=>{$('debriefDialog').close();openWelcome();};$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(sim.export(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Tobruk-${s.scenario}-debrief.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};$('debriefDialog').showModal();}
document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-station]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.station==='room'){room.focus('room');selected='';renderInspector();}else select(b.dataset.station,true);});
let walkTimer;document.querySelectorAll('[data-walk]').forEach(b=>{const step=()=>{let k=b.dataset.walk;room.target=null;if(k==='turnLeft')room.camera.yaw+=.065;else if(k==='turnRight')room.camera.yaw-=.065;else room.walk(k==='left'?-.065:k==='right'?.065:0,k==='forward'?.065:k==='back'?-.065:0);};b.onpointerdown=e=>{e.preventDefault();step();clearInterval(walkTimer);walkTimer=setInterval(step,40);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>clearInterval(walkTimer);b.onclick=e=>{if(e.detail===0)step();};});
$('language').onclick=()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('tobruk-lab-language',lang);staticLanguage();if($('debriefDialog').open){$('debriefDialog').close();showDebrief();}};
$('startBtn').onclick=start;$('homeBtn').onclick=openWelcome;$('helpBtn').onclick=()=>info('help');$('facultyBtn').onclick=()=>info('faculty');$('curriculumBtn').onclick=()=>info('curriculum');$('infoClose').onclick=()=>$('infoDialog').close();$('coachClose').onclick=()=>$('coach').hidden=true;
$('debriefBtn').onclick=()=>dispatch('finish');$('hintBtn').onclick=()=>{highlight=sim.hint();lastHint=Date.now();if(highlight==='finish'){showFeedback({category:'correct',text:pair('You are ready to review the attempt.','أنت جاهز لمراجعة المحاولة.')});return;}const id=highlight;select(id.startsWith('support_')?'pillows':id,true);highlight=id;setTimeout(()=>{if(Date.now()-lastHint>4800)highlight='';},5000);};
$('labelsBtn').onclick=()=>{showLabels=!showLabels;$('labelsBtn').setAttribute('aria-pressed',showLabels);};$('motionBtn').onclick=()=>{room.reduced=!room.reduced;$('motionBtn').setAttribute('aria-pressed',room.reduced);};$('fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen?.():$('workspace').requestFullscreen?.();
const introLanguage=document.createElement('button');introLanguage.className='secondary';introLanguage.style.cssText='position:absolute;right:18px;top:12px;z-index:2;min-height:32px;padding:5px 10px;font-size:11px';introLanguage.textContent=lang==='en'?'العربية':'English';introLanguage.onclick=()=>{$('language').click();introLanguage.textContent=lang==='en'?'العربية':'English';};$('welcome').append(introLanguage);$('welcome').addEventListener('cancel',e=>{if(!started)e.preventDefault();});
staticLanguage();$('welcome').showModal();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
