const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.HANDWASH_CHROME||'/tmp/tobruk-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8000/handwash-prototype/');await p.waitForFunction(()=>window.handwash);await p.click('#start');await p.click('#try');
for(let wrongFirst of [false,true]){await p.evaluate(()=>handwash.practice());if(wrongFirst){await p.click('[data-action=soap]');assert.match(await p.locator('#feedback').innerText(),/بلّل/)}await p.click('[data-action=faucet]');await p.click('[data-action=water]');await p.click('[data-action=soap]');assert(await p.evaluate(()=>handwash.state.soap&&handwash.state.wet));}
// Real pointer scrubbing, not a direct state mutation.
let b=await p.locator('#scene').boundingBox();await p.mouse.move(b.x+b.width*.32,b.y+b.height*.53);await p.mouse.down();for(let n=0;n<310;n++){await p.mouse.move(b.x+b.width*(.5+.18*Math.sin(n/7)),b.y+b.height*.53);await p.waitForTimeout(17)}await p.mouse.up();assert((await p.evaluate(()=>handwash.state.coverage.palms))>=1);
await p.click('[data-action=water]');await p.click('[data-action=towel]');await p.click('[data-action=faucet]');assert(await p.evaluate(()=>handwash.state.safe));await p.click('#finish');assert(await p.locator('[data-retry=backL]').isVisible());await p.click('[data-retry=backL]');assert(await p.evaluate(()=>handwash.step.id==='backL'&&handwash.state.soap));assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await p.evaluate(()=>handwash.setLang(0));assert.equal(await p.locator('html').getAttribute('dir'),'ltr');await p.evaluate(()=>handwash.setLang(1));assert.equal(await p.locator('html').getAttribute('dir'),'rtl');
// Check every demonstration movement at phone size and collect label-free contact frames.
await p.evaluate(()=>handwash.watch());fs.mkdirSync('/tmp/handwash-qa',{recursive:true});for(let i=0;i<24;i++){await p.evaluate(i=>handwash.renderAt(i,4.8),i);await p.waitForTimeout(60);assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));if([5,6,8,11,13,15,17,19].includes(i)){await p.evaluate(()=>document.querySelector('#trainer').classList.add('text-hidden'));await p.locator('#stage').screenshot({path:`/tmp/handwash-qa/phone-${i}.png`});}}
// All fingertip end positions are on the opposing palm's contact plane (pad radius ~.08).
const contact=await p.evaluate(()=>{handwash.renderAt(11,5);const s=handwash.scene;return s.left.fingers.map(f=>{const q=f.tip.getWorldPosition(s.left.root.position.clone());return s.right.root.worldToLocal(q).z})});for(let z of contact)assert(z>.22&&z<.34,`fingertip contact z=${z}`);
for(const size of [{width:360,height:800},{width:768,height:1024},{width:1440,height:900}]){await p.setViewportSize(size);await p.waitForTimeout(100);assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));}
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:['normal water-wet-soap UI','early soap correction UI','real pointer friction','rinse-dry-safe closure','focused retry','Arabic RTL / English LTR','all 24 poses render at phone viewport','360, 390, 768, 1440 widths without overflow','fingertip contact plane'],contact,errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
