/* Additive integration only. Existing records and workflow behaviour remain unchanged. */
(()=>{'use strict';
const D=window.QMS_DEMO_DATA,KEY='tobruk-qms-prototype-v01',href='sustainability/?v=20261003-04';
const draft={id:'D-SUS-FORM-001',code:'NUR-FRM-SUS-001',title:'اختبار المؤسسية والاستدامة التشغيلية — نموذج تجريبي',version:'0.4',status:'draft',owner:'قسم التوثيق والأرشفة',approval:'quality',location:'وحدة المؤسسية داخل المساحة — حفظ محلي تجريبي فقط',current:true,sourceUrl:href};
if(D){if(!D.documents.some(x=>x.id===draft.id))D.documents.push({...draft});if(!D.roles.some(x=>x.id==='archive'))D.roles.push({id:'archive',label:'قسم التوثيق والأرشفة',kind:'staff',unit:'التوثيق والأرشفة',icon:'▤',description:'الإدخال والحفظ المنظم ضمن اختصاص القسم — دور تجريبي غير محمي.'});}
try{const raw=localStorage.getItem(KEY);if(raw){const state=JSON.parse(raw);if(Array.isArray(state.documents)&&!state.documents.some(x=>x.id===draft.id)){state.documents.push({...draft});localStorage.setItem(KEY,JSON.stringify(state));}}}catch{/* Do not overwrite unreadable data. The original workspace handles its storage error. */}
function link(label){const a=document.createElement('a');a.href=href;a.textContent=label;a.setAttribute('data-sustainability-link','');a.style.cssText='display:block;padding:12px 14px;border:1px solid #c5d5c8;border-radius:9px;margin:8px 0;background:#f1f6f2;color:#174b3b;text-decoration:none;line-height:1.8;font-weight:600';return a;}
function mount(){const nav=document.querySelector('#sidebar .nav');if(nav&&!nav.querySelector('[data-sustainability-link]')){const a=link('⇄ اختبار المؤسسية والاستدامة');const docs=nav.querySelector('[data-nav="documents"]');if(docs)docs.after(a);else nav.append(a);}const login=document.querySelector('.login-wrap');if(login&&!login.querySelector('[data-sustainability-link]')){const a=link('فتح مسودة اختبار المؤسسية والاستدامة التشغيلية');const note=login.querySelector('.login-note');if(note)note.after(a);else login.append(a);}const view=document.getElementById('view');if(view&&document.querySelector('[data-nav="documents"].active')&&!view.querySelector('[data-sustainability-link]')){view.prepend(link('فتح نموذج اختبار المؤسسية والاستدامة — أسئلة، شواهد، اختبار تسليم وخطة معالجة · محلي تجريبي'));}}
const app=document.getElementById('app');if(app){let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;mount();});}).observe(app,{childList:true,subtree:true});}mount();
})();