/* Additive navigation integration. Legacy assessments and files remain unchanged. */
(()=>{'use strict';
const D=window.QMS_DEMO_DATA,KEY='tobruk-qms-prototype-v01',href='sustainability/departments.html?v=20261003-1';
const draft={id:'D-CON-FORM-001',code:'NUR-FRM-CON-001',title:'فحص استمرارية أعمال الأقسام والوحدات — خمسة بنود لكل جهة',version:'1.0',status:'draft',owner:'قسم التوثيق والأرشفة',approval:'quality',location:'مسودة تفاعلية محلية — 20 بطاقة بحسب الهيكل المقترح',current:true,sourceUrl:href};
if(D){if(!D.documents.some(x=>x.id===draft.id))D.documents.push({...draft});if(!D.roles.some(x=>x.id==='archive'))D.roles.push({id:'archive',label:'قسم التوثيق والأرشفة',kind:'staff',unit:'التوثيق والأرشفة',icon:'▤',description:'الإدخال والحفظ المنظم ضمن اختصاص القسم — دور تجريبي غير محمي.'});}
try{const raw=localStorage.getItem(KEY);if(raw){const state=JSON.parse(raw);if(Array.isArray(state.documents)&&!state.documents.some(x=>x.id===draft.id)){state.documents.push({...draft});localStorage.setItem(KEY,JSON.stringify(state));}}}catch{/* Never replace unreadable data. */}
function link(label){const a=document.createElement('a');a.href=href;a.textContent=label;a.setAttribute('data-sustainability-link','');a.style.cssText='display:block;padding:12px 14px;border:1px solid #c5d5c8;border-radius:9px;margin:8px 0;background:#f1f6f2;color:#174b3b;text-decoration:none;line-height:1.8;font-weight:600';return a;}
function mount(){const nav=document.querySelector('#sidebar .nav');if(nav&&!nav.querySelector('[data-sustainability-link]')){const a=link('⇄ فحص استمرارية أعمال الأقسام');const docs=nav.querySelector('[data-nav="documents"]');if(docs)docs.after(a);else nav.append(a);}const login=document.querySelector('.login-wrap');if(login&&!login.querySelector('[data-sustainability-link]')){const a=link('فتح فحص استمرارية أعمال الأقسام — خمسة بنود فقط لكل جهة');const note=login.querySelector('.login-note');if(note)note.after(a);else login.append(a);}const view=document.getElementById('view');if(view&&document.querySelector('[data-nav="documents"].active')&&!view.querySelector('[data-sustainability-link]')){view.prepend(link('فتح فحص استمرارية أعمال الأقسام والوحدات — قائمة تحقق مختصرة · حفظ محلي تجريبي'));}}
const app=document.getElementById('app');if(app){let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;mount();});}).observe(app,{childList:true,subtree:true});}mount();
})();
