/* Local review prototype. No network submission, scoring, monitoring, or changes to legacy stores. */
(()=>{'use strict';
const D=window.ContinuityData,KEY='tobruk-continuity-departments-v1',FORMAT='tobruk-continuity-departments',MAX=500;
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={'':'لم تُحدد الحالة',yes:'متوفر',needs:'يحتاج استكمالًا',unknown:'لم أتحقق بعد',na:'لا ينطبق'};
const reasons={first:'فحص أولي',handover:'تغيّر المسؤول',change:'تغيّر جوهري في العمل',need:'ظهرت حاجة أو مشكلة'};
const scopes={active:'فحص العمل القائم',inactive:'الجهة غير مفعّلة حاليًا',within:'الأعمال تُؤدّى ضمن جهة أخرى'};
const today=()=>{const a=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Tripoli',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const v=t=>a.find(p=>p.type===t).value;return v('year')+'-'+v('month')+'-'+v('day');};
const uid=()=>globalThis.crypto?.randomUUID?.()||'c-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
const unit=id=>D.units.find(u=>u.id===id);
function fresh(id,previous=''){return{id:uid(),unit:id,previous,createdAt:new Date().toISOString(),date:today(),reason:previous?'need':'first',scope:'active',within:'',answers:['','','','',''],note:'',closedAt:''};}
function describe(r){
 if(r.scope==='inactive')return {title:'لم يُجر الفحص: الجهة غير مفعّلة حاليًا',detail:'لا تُسجل كإخفاق. تُراجع البطاقة عند تفعيل الجهة أو إسناد أعمالها.',kind:'inactive'};
 const a=r.answers,n=a.filter(x=>x==='needs').length,k=a.filter(x=>x==='unknown').length,b=a.filter(x=>x==='').length;
 if(n)return{title:'توجد نقاط محددة تحتاج استكمالًا',detail:'تظهر البنود أدناه. تُراجع الحاجة إلى إجراء مناسب دون إنشاء تكليف آلي.'+(b?' توجد أيضًا بنود لم تُحدد حالتها.':'')+(k?' وبعض البنود تحتاج تحققًا.':''),kind:'needs'};
 if(b)return{title:'الفحص لم يكتمل بعد',detail:'بقيت بنود لم تُحدد حالتها. المربع الفارغ ليس إجابة سلبية.',kind:'draft'};
 if(k)return{title:'بعض البنود تحتاج تحققًا',detail:'لا يُستنتج توافرها أو غيابها قبل التحقق من الواقع.',kind:'unknown'};
 if(a.every(x=>x==='na'))return{title:'البنود محددة بأنها لا تنطبق',detail:'لا يُستنتج من ذلك تحقق الاستمرارية. تُراجع ملاءمة البطاقة لطبيعة العمل.',kind:'na'};
 return{title:'لم تُسجّل نواقص في البنود المنطبقة',detail:'وصف بحسب الإجابات فقط؛ ليس تقييمًا للموظفين أو إثباتًا مستقلًا لاستدامة العمل.',kind:'available'};
}
function clean(r){
 if(!r||typeof r!=='object'||!unit(r.unit)||typeof r.id!=='string'||!/^[\w-]{1,100}$/.test(r.id)||(!validDate(r.date)&&!(r.date===''&&!r.closedAt))||!Object.hasOwn(reasons,r.reason)||!Object.hasOwn(scopes,r.scope)||!Array.isArray(r.answers)||r.answers.length!==5||r.answers.some(x=>!Object.hasOwn(labels,x)))throw Error('بيانات بطاقة غير متوافقة؛ لم تُستبدل السجلات.');
 for(const [key,max] of [['note',3000],['within',180],['previous',100],['createdAt',40],['closedAt',40]])if(typeof r[key]!=='string'||r[key].length>max)throw Error('حقل غير صالح في ملف الاستيراد.');
 if(!Number.isFinite(Date.parse(r.createdAt))||(r.closedAt&&!Number.isFinite(Date.parse(r.closedAt))))throw Error('تاريخ سجل غير صالح.');
 return{id:r.id,unit:r.unit,previous:r.previous,createdAt:r.createdAt,date:r.date,reason:r.reason,scope:r.scope,within:r.within,answers:[...r.answers],note:r.note,closedAt:r.closedAt};
}
window.ContinuityCore={fresh,describe,clean,today,labels,KEY};
let records=[],current='',mode='home',filter='all',query='',lastRaw=null,blocked='',timer;
try{lastRaw=localStorage.getItem(KEY);if(lastRaw!==null){const p=JSON.parse(lastRaw);if(p.version!==1||!Array.isArray(p.records)||p.records.length>MAX)throw Error();const a=p.records.map(clean);if(new Set(a.map(r=>r.id)).size!==a.length)throw Error();records=a;}}catch{blocked='تعذر قراءة الحفظ المحلي. لم تُستبدل البيانات السابقة؛ يمكنك التجربة والتصدير، لكن الحفظ في المتصفح غير متاح.';}
const active=()=>records.find(r=>r.id===current);
function notify(text){$('toast').textContent=text;clearTimeout(timer);timer=setTimeout(()=>$('toast').textContent='',6500);}
function showStorage(){const e=$('storage-alert');e.hidden=!blocked;e.className='storage-warning';e.textContent=blocked;const s=$('save-state');if(s)s.textContent=blocked?'التغييرات في الذاكرة فقط — صدّر نسخة قبل إغلاق الصفحة.':'تُحفظ الإجابات تلقائيًا في هذا المتصفح فقط؛ لا يوجد إرسال للكلية.';}
function persist(){if(blocked){showStorage();return false;}try{const actual=localStorage.getItem(KEY);if(actual!==lastRaw){blocked='تغيرت البيانات في نافذة أخرى. أوقفنا الحفظ هنا لمنع استبدالها؛ صدّر تعديلاتك ثم أعد تحميل الصفحة.';showStorage();return false;}const next=JSON.stringify({version:1,records});localStorage.setItem(KEY,next);lastRaw=next;showStorage();return true;}catch{blocked='تعذر الحفظ في المتصفح أو امتلأت مساحته. التغييرات في الذاكرة فقط؛ صدّر نسخة قبل المغادرة.';showStorage();return false;}}
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue!==lastRaw){blocked='تغيرت السجلات في نافذة أخرى. صدّر تعديلاتك قبل إعادة التحميل؛ لم نستبدل بيانات أي نافذة.';showStorage();}});
function opts(map,value){return Object.entries(map).map(([v,t])=>`<option value="${escape(v)}"${v===value?' selected':''}>${escape(t)}</option>`).join('');}
function setRoute(){const u=new URL(location.href);u.hash=(mode==='card'||mode==='summary')?'record='+encodeURIComponent(current):mode==='history'?'history':'';history.replaceState(null,'',u);}
function afterRender(focus=true){$('nav-home').classList.toggle('active',mode!=='history');$('nav-history').classList.toggle('active',mode==='history');showStorage();setRoute();if(focus){const h=$('view').querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}}
function changeView(next,focus=true){mode=next;if(next==='home')renderHome();else if(next==='history')renderHistory();else if(next==='card')renderCard();else renderSummary();afterRender(focus);}
function latest(id){return [...records].reverse().find(r=>r.unit===id);}
function openUnit(id){if(!unit(id))return;let r=latest(id);if(!r){if(records.length>=MAX){notify('بلغت التجربة حد السجلات. صدّر العمل وراجعه قبل إضافة سجلات أخرى.');return;}r=fresh(id);records.push(r);persist();}current=r.id;changeView(r.closedAt?'summary':'card');}
function openRecord(id){const r=records.find(x=>x.id===id);if(!r)return;current=id;changeView(r.closedAt?'summary':'card');}
function newReview(){const r=active();if(!r)return;const draft=records.find(x=>x.unit===r.unit&&!x.closedAt);if(draft&&draft.id!==r.id){openRecord(draft.id);notify('لديك مسودة قائمة لهذه الجهة؛ فُتحت لتجنب التكرار.');return;}if(records.length>=MAX){notify('بلغت التجربة حد السجلات.');return;}const n=fresh(r.unit,r.id);records.push(n);current=n.id;persist();changeView('card');notify('بدأ فحص جديد بإجابات فارغة. السجل السابق محفوظ كما هو.');}
function normalize(s){return s.normalize('NFKC').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').toLowerCase();}
function catalog(){const list=D.units.filter(u=>(filter==='all'||String(u.group)===filter)&&normalize(u.name).includes(normalize(query.trim())));if(!list.length)return '<div class="empty">لا توجد جهة مطابقة. جرّب اسمًا أقصر أو اختر جميع الجهات.</div>';return D.groups.map((g,i)=>{const found=list.filter(u=>u.group===i);if(!found.length)return '';return `<section class="group"><div class="group-head"><h2>${escape(g)}</h2><div class="group-line"></div></div><div class="directory">${found.map(u=>{const r=latest(u.id);return `<button class="unit" data-command="unit" data-id="${u.id}"><span class="unit-top"><span class="unit-num">${Number(u.id).toLocaleString('ar')}</span><span class="unit-state">${r?(r.closedAt?'سجل محفوظ محليًا':'مسودة قيد العمل'):'بطاقة من ٥ بنود'}</span></span><h3>${escape(u.name)}</h3><span class="unit-bottom"><span>${r?(r.closedAt?'عرض الفحص المحفوظ':'متابعة المسودة'):'فتح بطاقة الجهة'}</span><span aria-hidden="true">←</span></span></button>`;}).join('')}</div></section>`;}).join('');}
function tools(){return `<details class="tools"><summary>نقل نسخة من التجربة واستعادتها</summary><p class="small">التصدير ملف غير مشفّر يضم سجلات هذا النموذج فقط. الاستيراد يضيف السجلات ولا يستبدل الموجود، ولا يمنحها صفة رسمية.</p><div class="actions"><button class="btn secondary" data-command="export-all">تصدير السجلات</button><button class="btn quiet" data-command="import">استيراد نسخة</button><input id="import-file" type="file" accept=".json,application/json"></div></details>`;}
function renderHome(){ $('view').innerHTML=`<section class="hero"><div><div class="eyebrow">حفظ العمل · وضوح المتابعة · سهولة التسليم</div><h1>فحص استمرارية أعمال الكلية</h1><p>اختر جهتك فقط. خمس عبارات عمّا يحفظ العمل ويسهّل مواصلته، وملاحظة واحدة عند الحاجة.</p></div><div class="hero-note" aria-label="خمسة بنود في كل بطاقة"><b>٥</b><span>بنود لجهتك</span><div class="small">لا درجات ولا نسب</div></div></section><div class="search"><label class="sr-only" for="unit-search">ابحث عن القسم أو الوحدة</label><input id="unit-search" type="search" placeholder="ابحث عن القسم أو الوحدة…" value="${escape(query)}"></div><div class="filters" aria-label="المسارات"><button class="${filter==='all'?'active':''}" data-filter="all">جميع الجهات</button>${D.groups.map((g,i)=>`<button class="${String(i)===filter?'active':''}" data-filter="${i}">${escape(g)}</button>`).join('')}</div><div id="catalog">${catalog()}</div>${tools()}`;}
function row(text,i,value){return `<div class="checkrow" data-row="${i}" data-value="${value}"><label class="checklabel" for="q-${i}"><input id="q-${i}" type="checkbox" data-check="${i}"${value==='yes'?' checked':''}><span>${escape(text)}</span></label><div class="alt-status"><select id="s-${i}" data-status="${i}" aria-label="حالة البند ${i+1}">${opts(labels,value)}</select></div></div>`;}
function renderCard(){const r=active(),u=unit(r.unit);$('view').innerHTML=`<div class="form-width"><button class="linkbtn back" data-command="home">→ اختيار جهة أخرى</button><section class="card"><div class="card-head"><div><div class="eyebrow">${escape(D.groups[u.group])}</div><h1>${escape(u.name)}</h1></div><span class="pill">٥ بنود فقط</span></div><p class="intro">ضع ✓ أمام المتوفر. عند الحاجة اختر «يحتاج استكمالًا» أو «لم أتحقق بعد» أو «لا ينطبق». ترك المربع فارغًا لا يعني وجود خلل.</p><details class="metadata"><summary>تاريخ الفحص وسببه وحالة الجهة</summary><div class="grid"><label class="field"><span>التاريخ</span><input type="date" id="review-date" data-field="date" max="${today()}" value="${r.date}"></label><label class="field"><span>سبب الفحص</span><select data-field="reason">${opts(reasons,r.reason)}</select></label><label class="field wide"><span>حالة الجهة في هذه المراجعة</span><select id="review-scope" data-field="scope">${opts(scopes,r.scope)}</select></label><label class="field wide" id="within-field"${r.scope!=='within'?' hidden':''}><span>الجهة التي تؤدي هذه الأعمال</span><input data-field="within" maxlength="180" value="${escape(r.within)}" placeholder="الاسم الوظيفي للجهة، دون أسماء أشخاص"></label></div></details><div id="inactive-note" class="soft"${r.scope!=='inactive'?' hidden':''}>الجهة غير مفعلة حاليًا؛ تُحفظ هذه المعلومة دون إجراء الفحص أو اعتبارها إخفاقًا.</div><div id="questions" class="checks"${r.scope==='inactive'?' hidden':''}>${u.items.map((q,i)=>row(q,i,r.answers[i])).join('')}</div><label class="field"><span>عائق استمرار أو تحسين مطلوب، إن وجد <small>— اختياري</small></span><textarea id="review-note" data-field="note" maxlength="3000" placeholder="سطر يوضح ما يساعد العمل على الاستمرار. لا تكتب بيانات شخصية أو حساسة.">${escape(r.note)}</textarea></label><div class="actions"><button class="btn" data-command="finish">حفظ الفحص وعرض الملخص</button><button class="btn quiet" data-command="home">العودة مع حفظ المسودة</button></div><div id="save-state" class="save-state" role="status"></div><details class="small" style="margin-top:14px"><summary>مرجع البطاقة</summary><p>${escape(u.reference)}</p><p>مرجع للصياغة المقترحة، وليس قرارًا بتفعيل جهة أو منح صلاحية.</p></details></section></div>`;}
function resultBody(r){const u=unit(r.unit),d=describe(r);return `<div class="eyebrow">${escape(D.groups[u.group])}</div><h1>${escape(u.name)}</h1><p class="small">تاريخ الفحص: ${escape(r.date)} · ${escape(reasons[r.reason])}</p>${r.scope==='within'?`<div class="soft">الأعمال تُؤدّى ضمن: ${escape(r.within||'لم تُحدد الجهة بعد')}</div>`:''}<div class="soft"><h2 class="summary-title">${escape(d.title)}</h2><p>${escape(d.detail)}</p></div>${r.scope==='inactive'?'':u.items.map((q,i)=>`<div class="summary-row" data-value="${r.answers[i]}"><span class="pill">${escape(labels[r.answers[i]])}</span><p>${escape(q)}</p></div>`).join('')}${r.note.trim()?`<div style="margin-top:22px"><h2>الملاحظة المسجلة</h2><p class="note-block">${escape(r.note)}</p><p class="small">تُراجع عند الحاجة ضمن المتابعة القائمة؛ لم يُنشأ تكليف أو إشعار تلقائي.</p></div>`:''}<p class="small" style="margin-top:18px">ملخص وصفي بحسب الإجابات. لا درجة، ولا حكم على الأشخاص، ولا إثبات مستقل للاستدامة.</p>`;}
function renderSummary(){const r=active();$('view').innerHTML=`<div class="form-width"><button class="linkbtn back" data-command="home">→ جميع الجهات</button><section class="card"><div class="card-head"><span class="pill">${r.closedAt?'سجل تجربة محلي':'معاينة المسودة'}</span><span class="small">${blocked?'غير محفوظ في المتصفح':'لم يُرسل إلى الكلية'}</span></div>${resultBody(r)}<div class="actions"><button class="btn" data-command="edit">العودة لتعديل هذا الفحص</button>${r.closedAt?'<button class="btn secondary" data-command="new-review">فحص جديد عند الحاجة</button>':''}<button class="btn secondary" data-command="print">طباعة الملخص</button><button class="btn quiet" data-command="export-one">تصدير هذا الفحص</button></div><div id="save-state" class="save-state"></div></section>${r.previous?'<p class="small">هذا فحص جديد مستقل؛ لم تُنسخ إليه إجابات السجل السابق.</p>':''}</div>`;}
function renderHistory(){const sorted=[...records].reverse();$('view').innerHTML=`<section class="hero"><div><div class="eyebrow">ما حفظته في هذا المتصفح</div><h1>سجلات التجربة</h1><p>السجلات تخص هذا الجهاز فقط. يمكن الرجوع إلى فحص سابق أو بدء فحص جديد عند الحاجة.</p></div></section>${sorted.length?`<section class="card">${sorted.map(r=>`<article class="record"><div><h3>${escape(unit(r.unit).name)}</h3><p>${escape(r.date)} · ${escape(reasons[r.reason])} · ${r.closedAt?'سجل تجربة':'مسودة'}</p><p>${escape(describe(r).title)}</p></div><button class="btn secondary" data-command="record" data-id="${r.id}">${r.closedAt?'عرض':'متابعة'}</button></article>`).join('')}</section>`:'<div class="empty">لا توجد سجلات بعد. اختر جهة وابدأ ببطاقتها.</div>'}${tools()}`;}
function finish(){const r=active();if(!r||r.closedAt)return;if(!validDate(r.date)||r.date>today()){notify('اختر تاريخًا صحيحًا لا يقع في المستقبل.');const el=$('review-date');el.closest('details').open=true;el.focus();return;}if(r.scope==='within'&&!r.within.trim()){notify('اكتب الجهة التي تؤدي الأعمال حتى تبقى المسؤولية واضحة.');const el=$('within-field').querySelector('input');el.closest('details').open=true;el.focus();return;}r.closedAt=new Date().toISOString();const ok=persist();changeView('summary');notify(ok?'حُفظ الفحص في هذا المتصفح فقط.':'عُرض الملخص، لكن الحفظ المحلي لم ينجح؛ صدّر نسخة.');}
function download(items){if(!items.length){notify('لا توجد سجلات لتصديرها بعد.');return;}let checked;try{checked=items.map(clean);}catch(err){notify('تعذر التصدير: أكمل التاريخ الصحيح في المسودة أولًا.');return;}const pack={format:FORMAT,version:1,exportedAt:new Date().toISOString(),notice:'تجربة محلية غير مشفرة؛ ليست وثيقة مؤسسية معتمدة.',records:checked};const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='continuity-'+today()+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);notify('جُهّز ملف التصدير. يحتفظ بسجلات هذه النسخة فقط ولا يتضمن مرفقات النموذج السابق.');}
const fingerprint=r=>JSON.stringify([r.unit,r.createdAt,r.date,r.reason,r.scope,r.within,r.answers,r.note,r.closedAt]);
async function importFile(file){if(!file)return;if(file.size>5*1024*1024)throw Error('ملف الاستيراد أكبر من الحد المسموح.');const p=JSON.parse(await file.text());if(p.format!==FORMAT||p.version!==1||!Array.isArray(p.records)||p.records.length>MAX)throw Error('اختر نسخة صُدرت من فحص الأقسام المختصر. النموذج السابق له صيغة مختلفة.');const list=p.records.map(clean),seen=new Set(records.map(fingerprint)),add=[];for(const r of list){const f=fingerprint(r);if(seen.has(f))continue;seen.add(f);r.id=uid();add.push(r);}if(records.length+add.length>MAX)throw Error('عدد السجلات يتجاوز حد التجربة.');if(!add.length){notify('هذه السجلات موجودة بالفعل؛ لم نكررها.');return;}records.push(...add);const ok=persist();changeView('history');notify(ok?'أضيفت السجلات المستوردة دون استبدال الموجود.':'أضيفت في الذاكرة فقط؛ تعذر الحفظ المحلي.');}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;renderHome();return;}const b=e.target.closest('[data-command]');if(!b)return;const c=b.dataset.command;if(c==='home')changeView('home');else if(c==='history')changeView('history');else if(c==='unit')openUnit(b.dataset.id);else if(c==='record')openRecord(b.dataset.id);else if(c==='finish')finish();else if(c==='edit'){active().closedAt='';persist();changeView('card');}else if(c==='new-review')newReview();else if(c==='export-all')download(records);else if(c==='export-one')download([active()]);else if(c==='import')$('import-file').click();else if(c==='print'){$('print-area').innerHTML='<h2>كلية التمريض، جامعة طبرق</h2><p>فحص استمرارية أعمال الكلية — تجربة محلية</p>'+resultBody(active())+'<p class="small">الإجابات محفوظة محليًا فقط، ولا تمثل إرسالًا للمؤسسة أو اعتمادًا رسميًا.</p>';window.print();}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='unit-search'){query=t.value;$('catalog').innerHTML=catalog();return;}const r=active();if(mode!=='card'||!r||r.closedAt||!t.dataset.field)return;if(['note','within'].includes(t.dataset.field)){r[t.dataset.field]=t.value;persist();}});
document.addEventListener('change',async e=>{const t=e.target;if(t.id==='import-file'){try{await importFile(t.files[0]);}catch(err){notify('لم يُستورد الملف: '+(err instanceof SyntaxError?'الصيغة ليست ملف JSON صالحًا.':err.message));}t.value='';return;}const r=active();if(mode!=='card'||!r||r.closedAt)return;let i;if(t.dataset.check!==undefined)i=Number(t.dataset.check);else if(t.dataset.status!==undefined)i=Number(t.dataset.status);if(i!==undefined){if(!Number.isInteger(i)||i<0||i>4)return;const v=t.dataset.check!==undefined?(t.checked?'yes':''):t.value;if(!Object.hasOwn(labels,v))return;r.answers[i]=v;const focusId=t.id;t.closest('[data-row]').outerHTML=row(unit(r.unit).items[i],i,v);$(focusId)?.focus({preventScroll:true});persist();return;}const f=t.dataset.field;if(f==='reason'&&Object.hasOwn(reasons,t.value))r.reason=t.value;else if(f==='date')r.date=t.value;else if(f==='scope'&&Object.hasOwn(scopes,t.value)){r.scope=t.value;$('within-field').hidden=r.scope!=='within';$('questions').hidden=r.scope==='inactive';$('inactive-note').hidden=r.scope!=='inactive';}else return;persist();});
if(!D||D.units.length!==20){$('view').textContent='تعذر تحميل بطاقات الأقسام. أعد تحميل الصفحة.';return;}
const hash=new URLSearchParams(location.hash.slice(1)),requested=hash.get('record'),requestedUnit=new URLSearchParams(location.search).get('unit');
if(requested&&records.some(r=>r.id===requested))openRecord(requested);else if(requestedUnit&&unit(requestedUnit))openUnit(requestedUnit);else changeView(location.hash==='#history'?'history':'home',false);
})();
