(function(){
'use strict';
const topics=window.ClinicalDiscoveryTopics||[], $=s=>document.querySelector(s);
let lang='ar',group='all';
const words={all:['الكل','All'],medicines:['الأدوية والتعامل معها','Medication handling'],charts:['السجلات','Charts'],devices:['الأجهزة','Devices'],confidence:['اسأل بثقة','Ask confidently']};
const tx=(ar,en)=>lang==='ar'?ar:en, esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tr(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-ar][data-en]').forEach(e=>e.textContent=e.dataset[lang]);$('#language').textContent=lang==='ar'?'English':'العربية';$('#language').setAttribute('aria-label',tx('Switch to English','التبديل إلى العربية'));$('#search').placeholder=tx('ابحث عن شيء…','Search something…');document.title=tx('اكتشف بثقة · كلية التمريض، جامعة طبرق','Discover with confidence · Tobruk Nursing');}
function filters(){const box=$('#filters');box.replaceChildren();Object.entries(words).forEach(([key,value])=>{const b=document.createElement('button');b.type='button';b.textContent=value[lang==='ar'?0:1];b.setAttribute('aria-pressed',String(group===key));b.addEventListener('click',()=>{group=key;filters();cards();});box.appendChild(b);});}
function cards(){const q=$('#search').value.trim().toLocaleLowerCase();const list=topics.filter(t=>(group==='all'||t.group===group)&&[t.title.ar,t.title.en,t.intro.ar,t.intro.en,t.term].join(' ').toLocaleLowerCase().includes(q));$('#cards').innerHTML=list.map(t=>`<article class="topic-card"><span class="symbol" aria-hidden="true">${esc(t.symbol)}</span><h3>${esc(t.title[lang])}</h3><span class="term" lang="en">${esc(t.term)}</span><p>${esc(t.intro[lang])}</p><a href="#${esc(t.id)}">${tx('تعرّف عليه','Explore it')}</a></article>`).join('');$('#empty').hidden=list.length!==0;}
function feedback(id,part,label){return `<div data-feedback-topic="${esc(id)}" data-feedback-part="${esc(part)}" data-feedback-label="${esc(label)}"></div>`;}
function visual(t){const a=tx;let h='';switch(t.visual){
case 'label':h=`<div class="label-demo"><div class="demo-kicker">FICTIONAL LABEL · NOT A REAL MEDICINE</div><strong>DEMO MEDICINE</strong><div class="label-grid"><div>Active ingredient<small>${a('اسم المادة الفعالة','Name of the active substance')}</small></div><div>Strength / concentration<small>${a('التركيز ليس الجرعة الموصوفة','Not the prescribed dose')}</small></div><div>Form / route<small>${a('الشكل وطريق الإعطاء','Formulation and route')}</small></div><div>Expiry / storage<small>${a('الصلاحية وتعليمات الحفظ','Expiry and storage conditions')}</small></div></div></div>`;break;
case 'chart':h=`<div class="table-scroll"><table><caption>${a('نموذج مبسط: ليست وثيقة لمريض حقيقي','Simplified example: no real patient')}</caption><thead><tr><th>${a('دواء افتراضي','Fictional medicine')}</th><th>${a('الوقت المقرر','Scheduled')}</th><th>${a('الإعطاء الفعلي','Actual administration')}</th><th>${a('التوثيق','Record')}</th></tr></thead><tbody><tr><td>Demo A</td><td>10:00</td><td>${a('لم يؤخذ بعد','Not taken yet')}</td><td>${a('لا يُسجل بأنه أُعطي','Do not mark as given')}</td></tr></tbody></table></div>`;break;
case 'vials':h=`<div class="pair"><div class="vial"><b>Single-dose</b><small>${a('مريض واحد · مناسبة إعطاء واحدة','One patient · one administration occasion')}</small></div><div class="vial"><b>Multi-dose</b><small>${a('راجع تعليمات المنتج وسياسة المؤسسة','Check product instructions and local policy')}</small></div></div>`;break;
case 'tablet':h=`<div class="pair"><div class="tablet"><b>MR / SR / XL</b><small>${a('تحقق من خصائص الإطلاق','Check release properties')}</small></div><div class="tablet"><b>EC / GR</b><small>${a('تحقق من خصائص التغليف','Check coating properties')}</small></div></div>`;break;
case 'oximeter':h=`<div class="monitor"><div class="reading"><span>SpO₂ %</span><strong>97</strong><small>${a('تقدير تشبع الأكسجين','Estimated oxygen saturation')}</small></div><div class="reading"><span>PR / min</span><strong>78</strong><small>${a('معدل النبض','Pulse rate')}</small></div></div>`;break;
case 'pump':h=`<div class="pump-face"><div class="demo-kicker">GENERIC DISPLAY · NO SETTINGS</div><p><span>Rate</span><b>—</b></p><p><span>Volume</span><b>—</b></p><div class="alarm">${a('منطقة التنبيهات · تختلف حسب الطراز','Alerts area · varies by model')}</div></div>`;break;
case 'conversation':h=`<blockquote class="quote" dir="ltr" lang="en">“Could you show me what this is used for?”</blockquote><p style="text-align:center">${a('هل توضح لي فيما يُستخدم هذا؟','A simple question can start a useful explanation.')}</p>`;break;
}return `<div class="visual">${h}<p class="visual-caption">${a('رسم تخطيطي/نموذج توضيحي، وليس صورة منتج أو إعدادًا علاجيًا.','Schematic/example, not a product photograph or treatment setting.')}</p>${feedback(t.id,'visual',t.title[lang]+' — '+a('المثال المرئي','Visual example'))}</div>`;}
function speak(text){const status=$('#speech-status');if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){status.textContent=tx('القراءة الصوتية غير متاحة على هذا المتصفح.','Speech is unavailable in this browser.');alert(status.textContent);return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.88;window.speechSynthesis.speak(u);}
function route(){const raw=location.hash.slice(1),t=topics.find(x=>x.id===raw);$('#home').hidden=!!t;$('#detail').hidden=!t;if(!t){$('#detail').replaceChildren();cards();if(window.HubFeedback)window.HubFeedback.mount($('#home'));return;}
const headings={recognise:tx('تعرّف عليه','Recognise it'),notice:tx('ما الذي أنتبه إليه؟','What should I notice?'),ask:tx('اسأل أو استوضح','Ask or clarify')};
$('#detail').innerHTML=`<a class="back" href="#">${tx('رجوع إلى الموضوعات','Back to topics')}</a><div class="detail-head"><h1 tabindex="-1">${esc(t.title[lang])}</h1><div class="term-line"><span dir="ltr" lang="en">${esc(t.term)}</span><button type="button" class="speak">${tx('اسمع العبارة الإنجليزية','Hear the English term')}</button></div><p>${esc(t.intro[lang])}</p></div>${visual(t)}${t.sections.map(s=>`<section class="learning-part"><h2>${headings[s.id]}</h2><p>${esc(s.text[lang])}</p>${feedback(t.id,s.id,t.title[lang]+' — '+headings[s.id])}</section>`).join('')}<section class="try"><h2>${tx('جرّب موقفًا صغيرًا','Try a small situation')}</h2><p>${esc(t.question[lang])}</p><div class="choices">${t.choices.map((c,i)=>`<button type="button" data-choice="${i}" aria-pressed="false">${esc(c[lang])}</button>`).join('')}</div><div class="answer" role="status" aria-live="polite" hidden></div>${feedback(t.id,'situation',t.title[lang]+' — '+tx('الموقف','Situation'))}</section><details class="sources"><summary>${tx('المصادر وحدود هذا المحتوى','Sources and scope')}</summary>${t.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`).join('')}<p>${tx('مراجع تعليمية دولية، لا تُعرض بوصفها لوائح ليبية أو بروتوكولًا محليًا. النسخة الأولية ليست معتمدة سريريًا.','International educational references, not Libyan regulations or a local protocol. This initial edition is not clinically approved.')}</p><p>20261009-1 · ${tx('معرفة عامة، دون ربط بالمقررات أو الامتحانات','General knowledge, without course or exam links')}</p></details>`;
$('.speak').addEventListener('click',()=>speak(t.term));document.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const box=$('.answer'),ok=Number(b.dataset.choice)===t.correct;box.hidden=false;box.textContent=(ok?tx('هذه هي الفكرة. ','That is the idea. '):tx('لنراجع الفكرة معًا. ','Let us look at the idea together. '))+t.explanation[lang];}));if(window.HubFeedback)window.HubFeedback.mount($('#detail'));
}
$('#language').addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';tr();filters();cards();route();if(window.HubFeedback)window.HubFeedback.refresh();});$('#search').addEventListener('input',cards);window.addEventListener('hashchange',()=>{route();window.scrollTo({top:0,behavior:'auto'});const h=$('#detail h1');if(h)h.focus({preventScroll:true});});tr();filters();cards();route();
})();
