(() => {
'use strict';
const VERSION='20261009-atlas-0.1';
const $=id=>document.getElementById(id), root=document.documentElement;
const all=[...window.ATLAS_CHARTS,...window.ATLAS_ITEMS];
const categories={all:'All notebook pages|كل صفحات الدفتر',charts:'Charts & records|السجلات والنماذج',tools:'Clinical tools|الأدوات',devices:'Medical devices|الأجهزة',dressings:'Dressings|الضمادات',wounds:'Wound recognition|التعرّف إلى الجروح',medicines:'Medicines & forms|الأدوية وأشكالها'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pair=(s,tag='span')=>{let [en,ar]=String(s??'').split('|');return ar===undefined?`<bdi>${esc(en)}</bdi>`:`<${tag} class="ar" lang="ar">${esc(ar)}</${tag}><${tag} class="en" lang="en">${esc(en)}</${tag}>`;};
const norm=s=>String(s).toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه');
const readStore=(k,d)=>{try{const v=localStorage.getItem('tobruk-atlas:'+k);return v?JSON.parse(v):d;}catch{return d;}};
let storageOK=true;
const store=(k,v)=>{try{localStorage.setItem('tobruk-atlas:'+k,JSON.stringify(v));return true;}catch{storageOK=false;return false;}};
const storedMarks=readStore('marks',[]),storedNotes=readStore('notes',{});
let marks=new Set(Array.isArray(storedMarks)?storedMarks.filter(x=>all.some(y=>y.id===x)):[]);
let notes=storedNotes&&typeof storedNotes==='object'&&!Array.isArray(storedNotes)?storedNotes:{};
let cat='all',onlySaved=false,current=null,blank=false,selectedField=-1;
let mode=readStore('mode','both');if(!['ar','en','both'].includes(mode))mode='both';
function language(){root.dataset.mode=mode;root.lang=mode==='en'?'en':'ar';root.dir=mode==='en'?'ltr':'rtl';$('mode').value=mode;document.title=current?current.title.split('|')[mode==='en'?0:1]+' · Nursing Pocket Atlas':'أطلس التمريض المصوّر · Nursing Pocket Atlas';}
function announce(s){$('status').textContent=s;}
function nav(){ $('categories').innerHTML=Object.entries(categories).map(([id,label])=>`<button type="button" data-category="${id}" class="category ${cat===id?'active':''}" aria-pressed="${cat===id}"><span>${pair(label)}</span><small>${id==='all'?all.length:all.filter(x=>x.cat===id).length}</small></button>`).join('');}
function filtered(){let q=norm($('search').value.trim());let terms=q.split(/\s+/).filter(Boolean);let list=all.filter(x=>(cat==='all'||x.cat===cat)&&(!onlySaved||marks.has(x.id))&&terms.every(t=>norm([x.title,x.about,x.parts||'',x.id].join(' ')).includes(t)));if(cat==='all'&&!q&&!onlySaved){const featured=['chart-vitals','stethoscope','infusion-pump','foam','chart-fluid','vial','incision','chart-mar','oximeter'];list.sort((a,b)=>{const rank=x=>featured.includes(x.id)?featured.indexOf(x.id):100+all.indexOf(x);return rank(a)-rank(b);});}return list;}
function catalog(){nav();let list=filtered();$('countBadge').innerHTML=pair(`${all.length} pages · ${window.ATLAS_CHARTS.length} charts|${all.length} صفحة · ${window.ATLAS_CHARTS.length} سجلًا`);$('catalogTitle').innerHTML=pair((onlySaved?'Saved pages|الصفحات المحفوظة':categories[cat]))+` <small>(${list.length})</small>`;$('cards').innerHTML=list.map(x=>`<a class="card" data-cat="${x.cat}" href="#${x.id}" aria-label="${esc(x.title.replace('|',' / '))}">${marks.has(x.id)?'<span class="saved-mark" aria-hidden="true">★</span>':''}<div class="cardart">${window.atlasArt(x.art)}</div><div class="cardcopy"><div class="cardcategory">${pair(categories[x.cat])}</div><h3>${pair(x.title)}</h3></div></a>`).join('');$('empty').hidden=list.length>0;$('saved').setAttribute('aria-pressed',String(onlySaved));}
function goCategory(id){cat=id;onlySaved=false;$('search').value='';if(location.hash){history.pushState(null,'',location.pathname+location.search);}current=null;$('reader').hidden=true;$('catalog').hidden=false;catalog();language();$('catalogTitle').scrollIntoView({block:'start',behavior:'auto'});}
function tableHTML(x){let thead=x.fields.map((f,i)=>`<th scope="col"${selectedField===i?' class="highlight"':''}><button type="button" data-field="${i}" aria-label="${esc('Explain / شرح '+f.label.replace('|',' / '))}">${pair(f.label)}</button></th>`).join('');let rows=blank?Array.from({length:Math.max(4,Math.min(x.rows.length,7))},()=>x.fields.map(()=>'')):x.rows;let body=rows.map(row=>`<tr>${row.map((v,i)=>`<td class="${blank?'blankcell ':''}${selectedField===i?'highlight':''}">${blank?'&nbsp;':pair(v)}</td>`).join('')}</tr>`).join('');return `<div class="tablewrap" tabindex="0" role="region" aria-label="Scrollable example chart / سجل توضيحي قابل للتمرير"><table><caption class="sr-only">${esc(x.title.replace('|',' / '))}</caption><thead><tr>${thead}</tr></thead><tbody>${body}</tbody></table></div>`;}
function plot(x){if(blank||!x.plot)return '';if(x.plot==='temperature'){
const vals=x.rows.map(r=>Number(r[1])), xs=[75,235,395,555], y=v=>165-(v-36.5)*100;
let grid=[36.5,37,37.5,38].map(v=>`<path d="M65 ${y(v)}H585" stroke="#d6dfd0"/><text x="55" y="${y(v)+4}" text-anchor="end">${v.toFixed(1)}</text>`).join('');
return `<div class="plot"><svg viewBox="0 0 630 205" role="img" aria-label="Temperature values 36.8, 37.1, 37.5, 37.2 degrees Celsius"><g font-family="Arial" font-size="12" fill="#405447">${grid}<polyline points="${vals.map((v,i)=>xs[i]+','+y(v)).join(' ')}" fill="none" stroke="#2a7058" stroke-width="3"/>${vals.map((v,i)=>`<circle cx="${xs[i]}" cy="${y(v)}" r="4" fill="#2a7058"/><text x="${xs[i]}" y="${y(v)-11}" text-anchor="middle">${v.toFixed(1)}</text><text x="${xs[i]}" y="193" text-anchor="middle">${x.rows[i][0]}</text>`).join('')}<text x="20" y="14">°C</text></g></svg></div>`;
}
let d='';for(let px=0;px<=750;px++){let t=px/125,phase=((t-.4)%0.8+0.8)%0.8;let g=(m,s,a)=>a*Math.exp(-.5*((phase-m)/s)**2);let mv=g(.11,.025,.12)+g(.27,.012,-.12)+g(.30,.010,1)+g(.33,.012,-.23)+g(.51,.055,.27);d+=(px?'L':'M')+px.toFixed(1)+' '+(135-50*mv).toFixed(2);}
return `<div class="plot"><svg viewBox="0 0 750 190" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Synthetic ECG at 25 millimetres per second and 10 millimetres per millivolt"><defs><pattern id="gridSmall" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M5 0H0V5" fill="none" stroke="#ead5cf" stroke-width=".5"/></pattern><pattern id="gridBig" width="25" height="25" patternUnits="userSpaceOnUse"><rect width="25" height="25" fill="url(#gridSmall)"/><path d="M25 0H0V25" fill="none" stroke="#d5b6ad" stroke-width=".8"/></pattern></defs><rect width="750" height="190" fill="url(#gridBig)"/><path d="${d}" fill="none" stroke="#264d3a" stroke-width="1.6"/><g fill="#294736" font-family="Arial" font-size="12"><text x="12" y="20">SYNTHETIC · 25 mm/s · 10 mm/mV</text><text x="59" y="109">P</text><text x="81" y="70">QRS</text><text x="106" y="110">T</text><text x="568" y="21">R–R: 0.8 s / 75 min⁻¹</text></g><path d="M20 166 H25 V116 H50 V166 H55" stroke="#264d3a" fill="none" stroke-width="2"/></svg></div><p class="plotnote">${pair('Schematic grid, not physical screen millimetres. Calibration pulse represents 1 mV.|شبكة توضيحية وليست ملليمترات فعلية على الشاشة. تمثّل نبضة المعايرة 1 ملي فولت.')}</p>`;
}
function paper(x){return `<div class="clinical-paper"><div class="paperhead"><h3>${pair(x.title)}</h3><span class="watermark">TEACHING EXAMPLE · NOT FOR PATIENT CARE / مثال تعليمي لاستخدام التعلّم فقط</span></div><div class="identifiers"><span>${pair('Fictional record: EX-01 · Adult example|سجل افتراضي: EX-01 · مثال للبالغين')}</span><span>${pair('Date: 09 Oct 2026 · Page '+x.id+'|التاريخ: 9 أكتوبر 2026 · الصفحة '+x.id)}</span><span>${pair('Real records require approved patient identifiers.|تتطلب السجلات الفعلية معرّفات المريض المعتمدة.')}</span><span>${pair('Allergy status is separate from an empty field.|حالة الحساسية لا تُستنتج من الحقل الفارغ.')}</span></div>${tableHTML(x)}${plot(x)}</div>`;}
function chartBody(x){return `<div class="formtools"><button id="sampleMode" type="button" aria-pressed="${!blank}">${pair('Worked example|مثال مسجل')}</button><button id="blankMode" type="button" aria-pressed="${blank}">${pair('Blank structure|البنية الفارغة')}</button></div><p class="formhint">${pair('Tap a column heading to explain it. On a phone, slide the chart sideways.|اضغط عنوان العمود لشرح معناه. على الهاتف يمكن تمرير السجل أفقيًا.')}</p><div id="paper">${paper(x)}</div><div id="fieldhint" class="fieldhint" hidden role="status"></div><section class="reading"><h2>${pair('Read this example|كيف نقرأ هذا المثال؟')}</h2><p>${pair(x.read)}</p></section><section class="fieldguide"><h2>${pair('Every field explained|شرح حقول السجل')}</h2>${x.fields.map((f,i)=>`<details id="field-${i}"><summary>${pair(f.label)}</summary><p>${pair(f.help)}</p></details>`).join('')}</section><section class="pitfalls"><h2>${pair('What not to assume · documentation pitfalls|ما لا ينبغي افتراضه · أخطاء التوثيق')}</h2><p>${pair(x.pitfalls)}</p></section>${x.official?`<a class="official" href="${esc(x.official)}" target="_blank" rel="noopener noreferrer">${pair('Open the original official chart ↗|افتح السجل الرسمي الأصلي ↗')}</a>`:''}`;}
function objectBody(x){return `<div class="object-layout"><figure class="object-figure">${window.atlasArt(x.art)}<figcaption>${pair('Original schematic illustration. Shapes vary by product; not an operating instruction.|رسم توضيحي أصلي. تختلف الأشكال حسب المنتج؛ وليس تعليمات تشغيل.')}</figcaption></figure><div><section class="info-block"><h2>${pair('What it is used for|ما استخدامه؟')}</h2><p>${pair(x.use)}</p></section><section class="info-block notice"><h2>${pair('What to notice|إلى ماذا تنتبه؟')}</h2><p>${pair(x.notice)}</p></section><section class="info-block"><h2>${pair('Recognition details|تفاصيل تساعد على التعرّف')}</h2><div class="parts">${pair(x.parts)}</div></section><button type="button" id="speak" class="primary">${pair('Hear the English name|استمع إلى الاسم الإنجليزي')}</button></div></div>`;}
function sources(x){return `<section class="sourcebox"><h2>${pair('Sources & further reading|المصادر والتوسع')}</h2>${x.refs.map(k=>{let s=window.ATLAS_SOURCES[k];return s?`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])} ↗</a>`:'';}).join('')}<small>${pair('Sources checked: 09 Oct 2026. Arabic explanations are educational adaptations, not official translations of these sources. No institutional endorsement is implied.|مراجعة المصادر: 9 أكتوبر 2026. الشروح العربية صياغة تعليمية وليست ترجمة رسمية للمراجع. الإحالات لا تعني موافقة الجهات على المحتوى.')}</small></section>`;}
function renderReader(x){current=x;language();$('catalog').hidden=true;$('reader').hidden=false;let i=all.indexOf(x);
$('reader').innerHTML=`<div class="readerbar"><a href="#">${pair('← Back to notebook|العودة إلى الدفتر ←')}</a><div class="actions"><button id="bookmark" type="button" aria-pressed="${marks.has(x.id)}">${marks.has(x.id)?'★':'☆'} ${pair('Save page|احفظ الصفحة')}</button><button id="copyLink" type="button">${pair('Copy link|نسخ الرابط')}</button><button id="print" type="button">${pair('Print page|طباعة الصفحة')}</button></div></div><div class="reader"><header class="pagehead"><div class="eyebrow"><span>${pair(categories[x.cat])}</span><span>PAGE ${String(i+1).padStart(2,'0')} / ${all.length}</span></div><h1>${pair(x.title)}</h1><p>${pair(x.about)}</p></header>${x.cat==='charts'?chartBody(x):objectBody(x)}${sources(x)}<details class="notesbox"><summary>${pair('My private notebook notes|ملاحظاتي الشخصية في الدفتر')}</summary><p>${pair('Only in this browser. Do not enter patient names, clinical records or student identifiers. Export to keep a backup.|في هذا المتصفح فقط. لا تدخل أسماء مرضى أو سجلات سريرية أو معرّفات طلبة. صدّر الملاحظات للاحتفاظ بنسخة.')}</p><label class="sr-only" for="note">ملاحظاتي · My notes</label><textarea id="note" maxlength="2000" placeholder="اكتب ما تريد تذكّره… / What would you like to remember?">${esc(typeof notes[x.id]==='string'?notes[x.id]:'')}</textarea><small id="noteStatus">${pair('Saved locally as you type.|تُحفظ محليًا أثناء الكتابة.')}</small></details><nav class="pagenav" aria-label="Previous and next pages">${i>0?`<a href="#${all[i-1].id}">← ${pair(all[i-1].title)}</a>`:'<span></span>'}${i<all.length-1?`<a href="#${all[i+1].id}">${pair(all[i+1].title)} →</a>`:''}</nav></div>`;
$('bookmark').onclick=()=>{marks.has(x.id)?marks.delete(x.id):marks.add(x.id);let ok=store('marks',[...marks]);$('bookmark').setAttribute('aria-pressed',String(marks.has(x.id)));$('bookmark').innerHTML=(marks.has(x.id)?'★ ':'☆ ')+pair('Save page|احفظ الصفحة');announce(ok?'Saved on this device / حُفظ على هذا الجهاز':'Could not persist saved pages / تعذر حفظ الصفحات');};
$('note').oninput=e=>{notes[x.id]=e.target.value;let ok=store('notes',notes);$('noteStatus').innerHTML=pair(ok?'Saved in this browser only.|حُفظت في هذا المتصفح فقط.':'Storage unavailable; export your notes before leaving.|الحفظ غير متاح؛ صدّر ملاحظاتك قبل المغادرة.');};
$('print').onclick=()=>window.print();$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('copyLink').innerHTML=pair('Copied ✓|نُسخ ✓');}catch{announce('Copy the address from your browser / انسخ العنوان من المتصفح');$('copyLink').innerHTML=pair('Copy browser address|انسخ عنوان المتصفح');}};
if(x.cat==='charts'){$('sampleMode').onclick=()=>switchBlank(false);$('blankMode').onclick=()=>switchBlank(true);}else{$('speak').disabled=!('speechSynthesis' in window);$('speak').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(x.title.split('|')[0].replace(' · purpose',''));u.lang='en-GB';u.rate=.85;speechSynthesis.speak(u);};}
}
function switchBlank(v){blank=v;selectedField=-1;$('paper').innerHTML=paper(current);$('sampleMode').setAttribute('aria-pressed',String(!blank));$('blankMode').setAttribute('aria-pressed',String(blank));$('fieldhint').hidden=true;}
function route(){if('speechSynthesis' in window)speechSynthesis.cancel();let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{id='';}blank=false;selectedField=-1;let x=all.find(x=>x.id===id);if(x){renderReader(x);window.scrollTo(0,0);}else{current=null;$('catalog').hidden=false;$('reader').hidden=true;catalog();language();if(id)announce('Page not found; notebook index shown / الصفحة غير موجودة؛ عُرض الفهرس');}}
$('mode').onchange=e=>{mode=e.target.value;store('mode',mode);language();};
$('categories').onclick=e=>{const b=e.target.closest('[data-category]');if(b)goCategory(b.dataset.category);};
$('openCharts').onclick=()=>goCategory('charts');$('search').oninput=catalog;$('clearSearch').onclick=()=>{$('search').value='';catalog();$('search').focus();};
$('saved').onclick=()=>{onlySaved=!onlySaved;current=null;if(location.hash)history.pushState(null,'',location.pathname+location.search);$('catalog').hidden=false;$('reader').hidden=true;catalog();language();$('catalogTitle').scrollIntoView({block:'start'});};
$('reader').onclick=e=>{const b=e.target.closest('[data-field]');if(!b||!current)return;selectedField=Number(b.dataset.field);let f=current.fields[selectedField];$('paper').innerHTML=paper(current);$('fieldhint').hidden=false;$('fieldhint').innerHTML=`<h3>${pair(f.label)}</h3>${pair(f.help)}`;$('fieldhint').scrollIntoView({block:'nearest'});};
$('export').onclick=()=>{let lines=['Nursing Pocket Atlas — personal notebook / الدفتر الشخصي',new Date().toISOString(),'Stored locally; no patient data / محفوظ محليًا؛ دون بيانات مرضى',''];for(const x of all){if(marks.has(x.id)||notes[x.id])lines.push(x.title.replace('|',' — '),(marks.has(x.id)?'★ ':'')+x.id,typeof notes[x.id]==='string'?notes[x.id]:'','');}let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));a.download='my-nursing-atlas-notes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('feedback').onclick=()=>{$('feedbackTopic').innerHTML=pair(current?current.title:'Notebook index|فهرس الدفتر');$('feedbackDialog').showModal();};
$('openFeedback').onclick=()=>{const url=new URL('https://docs.google.com/forms/d/e/1FAIpQLSdG7RX939cZgxhCeT0iweHtdLRdntXAiH-Mxv9aVeW7WaTq6A/viewform');url.searchParams.set('usp','pp_url');url.searchParams.set('entry.2046484445',`Nursing Pocket Atlas | page=${current?current.id:'index'} | part=${$('feedbackPart').value} | version=${VERSION}`);let a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.click();$('feedbackDialog').close();};
$('feedbackDialog').addEventListener('click',e=>{if(e.target===$('feedbackDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
window.addEventListener('hashchange',route);window.addEventListener('popstate',route);
window.addEventListener('beforeprint',()=>{document.querySelectorAll('.fieldguide details').forEach(d=>{d.dataset.wasOpen=String(d.open);d.open=true;});});window.addEventListener('afterprint',()=>{document.querySelectorAll('.fieldguide details').forEach(d=>d.open=d.dataset.wasOpen==='true');});
language();route();
})();
