/* Atlas 0.2: chapter definitions, source links and recognition equipment. */
window.ATLAS_CATS={
 tools:['Clinical tools','الأدوات التمريضية','forceps','Identify common bedside and procedure tools.','تعرّف إلى أدوات السرير والإجراءات الشائعة.'],
 devices:['Medical devices','الأجهزة الطبية','monitor','Recognise displays, connections and uses.','تعرّف إلى الأجهزة وشاشاتها واستخداماتها.'],
 mobility:['Moving & transferring','تحريك المريض ونقله','wheelchair','Transfer aids, mobility and handling safety.','وسائل الحركة والنقل وسلامة التعامل.'],
 dressings:['Dressings','الضمادات','foam','Materials, purposes and what differs.','المواد والاستخدامات والفروق بينها.'],
 wounds:['Wound recognition','التعرّف إلى الجروح','incision','Illustrated appearances and observations.','رسوم توضيحية وملاحظات تساعد على الفهم.'],
 medicines:['Medicines & forms','الأدوية وأشكالها','vial','Purposes, handling and documentation.','الأغراض والتعامل والتوثيق.'],
 charts:['Charts & records','السجلات والنماذج','chart','Realistic examples with field explanations.','أمثلة واقعية مع شرح حقولها.'],
 handover:['Nurse-to-nurse handover','تسليم الشفت واستلامه','handover','Worked reports across different settings.','أمثلة تسليم واستلام في أقسام مختلفة.'],
 boards:['Boards & notes','السبورات والملاحظات','board','Bedside, tasks, instructions and your notes.','سبورة السرير والمهام والتعليمات وملاحظاتك.'],
 emergency:['Emergency nursing','تمريض الطوارئ','crash-cart','Triage, assessment and emergency equipment.','الفرز والتقييم وتجهيزات الطوارئ.'],
 intensive:['Intensive care','العناية المشددة','ventilator','The ICU bed space, devices and daily care.','سرير العناية وأجهزته والعناية اليومية.'],
 cardiac:['Cardiac care','العناية بالقلب','heart-monitor','Monitoring, cardiac observations and recovery.','المراقبة والملاحظات القلبية والتعافي.'],
 firstaid:['First aid','الإسعافات الأولية','firstaid','Adult first responses; not paediatric algorithms.','الاستجابة الأولى للبالغين؛ ليست مسارات الأطفال.'],
 homecare:['Home & residential care','التمريض المنزلي ودور الرعاية','home','Visits, carers and continuity of care.','الزيارات ومقدمو الرعاية واستمراريتها.'],
 hospice:['Hospice & palliative care','الرعاية التلطيفية · Hospice','comfort','Comfort, dignity and support for the family.','الراحة والكرامة ودعم المريض وأسرته.']
};
Object.assign(window.ATLAS_SOURCES,{
 cauti:['CDC · Urinary catheter and drainage safety','https://www.cdc.gov/infection-control/hcp/cauti/summary-of-recommendations.html'],
 ngSafety:['HSSIB · Nasogastric tube placement safety','https://www.hssib.org.uk/patient-safety-investigations/placement-of-nasogastric-tubes/investigation-report/'],
 handling:['HSE · Moving and handling equipment','https://www.hse.gov.uk/healthservices/moving-handling/moving-handling-equipment.htm'],
 handlingRisk:['HSE · Individual moving and handling assessment','https://www.hse.gov.uk/healthservices/moving-handling/manage-the-risk.htm'],
 lifting:['FDA · Patient lift and sling safety','https://www.fda.gov/medical-devices/general-hospital-devices-and-supplies/patient-lifts'],
 movingHome:['NHS · Moving and handling someone safely','https://www.nhs.uk/social-care-and-support/practical-tips-if-you-care-for-someone/how-to-move-lift-and-handle-someone-else/'],
 handlingRCN:['Royal College of Nursing · Moving and handling','https://www.rcn.org.uk/Get-Help/RCN-advice/moving-and-handling'],
 bedside:['AHRQ · Nurse bedside shift report','https://www.ahrq.gov/patient-safety/patients-families/engagingfamilies/strategy3/index.html'],
 communication:['AHRQ · Communicating to improve quality','https://www.ahrq.gov/patient-safety/patients-families/engagingfamilies/strategy2/index.html'],
 residential:['AHRQ · Communicating a change in a resident’s condition','https://www.ahrq.gov/patient-safety/settings/long-term-care/resource/facilities/ltc/mod2sess2.html'],
 emergencyWHO:['WHO · Emergency Care Toolkit','https://www.who.int/teams/integrated-health-services/clinical-services-and-systems/emergency-and-critical-care/emergency-care-toolkit'],
 bec:['WHO–ICRC · Basic Emergency Care','https://www.who.int/teams/integrated-health-services/clinical-services-and-systems/emergency-and-critical-care/bec'],
 abcde:['Resuscitation Council UK · ABCDE approach','https://www.resus.org.uk/library/abcde-approach'],
 icu:['NHS · Intensive care','https://www.nhs.uk/tests-and-treatments/intensive-care/'],
 icuFamily:['Chelsea and Westminster Hospital · ICU guide','https://www.chelwest.nhs.uk/your-visit/patient-leaflets/icu/intensive-care-unit-icu-information-for-family-and-friends'],
 icuTech:['Mid Cheshire Hospitals · Critical care equipment','https://www.mcht.nhs.uk/our-services/critical-care/technology-and-equipment'],
 icuBundle:['SCCM · ICU Liberation A–F bundle','https://sccm.org/clinical-resources/iculiberation-home/abcdef-bundles'],
 icuUpdates:['SCCM · Adult and paediatric critical care resources','https://sccm.org/clinical-resources/iculiberation-home'],
 ccu:['Royal Cornwall Hospitals · Coronary Care Unit','https://royalcornwallhospitals.nhs.uk/wards/coronary-care-unit/'],
 telemetry:['Chelsea and Westminster Hospital · Cardiac monitoring','https://www.chelwest.nhs.uk/your-visit/patient-leaflets/medicine-services/cardiac-monitoring'],
 cath:['East Kent Hospitals · Cardiac catheterisation','https://leaflets.ekhuft.nhs.uk/cardiac-catheterisation/html/'],
 rehabilitation:['NHS · Cardiac recovery and rehabilitation','https://www.nhs.uk/conditions/coronary-heart-disease/recovery/'],
 firstaid2025:['Resuscitation Council UK · First aid guidelines 2025','https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/first-aid-guidelines'],
 bls2025:['Resuscitation Council UK · Adult basic life support 2025','https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/adult-basic-life-support-guidelines'],
 choking:['American Red Cross · Choking first aid','https://www.redcross.org/take-a-class/resources/learn-first-aid/adult-child-choking'],
 bleeding:['American Red Cross · Life-threatening external bleeding','https://www.redcross.org/take-a-class/resources/learn-first-aid/bleeding-life-threatening-external'],
 burns:['NHS · Burns and scalds','https://www.nhs.uk/conditions/burns-and-scalds/'],
 seizure:['American Red Cross · Seizures','https://www.redcross.org/take-a-class/resources/learn-first-aid/seizures'],
 stroke:['NHS · Stroke symptoms','https://www.nhs.uk/conditions/stroke/symptoms/'],
 anaphylaxis:['NHS · Anaphylaxis','https://www.nhs.uk/conditions/anaphylaxis/'],
 poisoning:['NHS · Poisoning','https://www.nhs.uk/conditions/poisoning/'],
 homePlan:['NICE · Person-centred home care planning','https://www.nice.org.uk/guidance/qs123/chapter/quality-statement-1-person-centred-planning'],
 homeNICE:['NICE · Home care for older people','https://www.nice.org.uk/guidance/ng21'],
 lone:['HSE · Managing the risks of lone working','https://www.hse.gov.uk/lone-working/employer/manage-the-risks-of-working-alone.htm'],
 ipc:['CDC · Core infection prevention in all care settings','https://www.cdc.gov/infection-control/hcp/core-practices/index.html'],
 palliative:['WHO · Palliative care','https://www.who.int/news-room/fact-sheets/detail/palliative-care'],
 hospice:['NHS · Hospice care','https://www.nhs.uk/tests-and-treatments/end-of-life-care/where-you-can-have-care/hospice-care/'],
 hospiceHome:['NHS · End of life care at home','https://www.nhs.uk/tests-and-treatments/end-of-life-care/where-you-can-have-care/care-at-home/'],
 dying:['NICE · Care of dying adults in the last days of life','https://www.nice.org.uk/guidance/ng31/chapter/recommendations'],
 hydration:['NICE · Hydration in the last days of life','https://www.nice.org.uk/guidance/qs144/chapter/quality-statement-4-hydration'],
 compassionate:['Marie Curie · Professional end of life care guidance','https://www.mariecurie.org.uk/professionals/palliative-care-knowledge-zone/national-guidelines-end-of-life']
});
window.ATLAS_EXTRA=[];
window.atlasAdd=(id,cat,title,art,about,use,notice,parts,refs,extra={})=>window.ATLAS_EXTRA.push({id,cat,title,art,about,use,notice,parts,refs,...extra});
const add=window.atlasAdd;
add('iv-cannula','tools','Peripheral IV cannula|القنية الوريدية الطرفية','cannula','A short flexible catheter placed into a peripheral vein.|قسطرة قصيرة مرنة توضع داخل وريد طرفي.','Provides access for prescribed fluids or medicines.|توفر وصولًا لإعطاء السوائل أو الأدوية الموصوفة.','The introducer needle is removed after placement; the flexible catheter remains. Colour does not replace reading the size. Pain, swelling and leakage need assessment.|تُزال إبرة الإدخال وتبقى القسطرة المرنة. لا يغني اللون عن قراءة المقاس. يحتاج الألم والتورم والتسرّب إلى تقييم.','Hub · flexible catheter · optional wings/port|وصلة · قسطرة مرنة · أجنحة/منفذ حسب النوع',['iv']);
add('venous-tourniquet','tools','Venepuncture tourniquet|رباط سحب الدم','tourniquet','A temporary band used during suitable vein-access procedures.|رباط مؤقت يستخدم في إجراءات الوصول الوريدي المناسبة.','Makes superficial veins easier to identify for a trained practitioner.|يساعد الممارس المدرّب على التعرف إلى الأوردة السطحية.','This is NOT the haemorrhage-control tourniquet used for life-threatening bleeding. Release and remove according to the procedure; do not leave it forgotten.|ليس هو عاصبة إيقاف النزف المهدد للحياة. يُرخى ويُزال وفق الإجراء؛ ولا يُترك منسيًا.','Band · buckle or release|رباط · مشبك أو وسيلة تحرير',['iv']);
add('giving-set','tools','IV giving set|طقم التسريب الوريدي','giving-set','Tubing connecting a compatible fluid container to the intended IV system.|أنبوب يصل عبوة سائل متوافقة بالنظام الوريدي المقصود.','Carries the prescribed infusion; some sets are designed for pumps or particular fluids.|ينقل التسريب الموصوف؛ وتخصص بعض الأطقم للمضخات أو لسوائل معينة.','Check set type, sterility, connections and pump compatibility. Drop factors differ: do not assume every drop equals the same volume.|تحقق من النوع والتعقيم والوصلات والتوافق مع المضخة. تختلف عوامل التقطير؛ فلا تفترض تساوي حجم كل قطرة.','Spike · drip chamber · tubing · clamp · connector|سن توصيل · حجرة تقطير · أنبوب · مشبك · وصلة',['iv']);
add('stopcock','tools','Three-way stopcock|محبس ثلاثي الاتجاهات','stopcock','A connector with a control handle and three ports.|وصلة لها مقبض تحكم وثلاثة منافذ.','Controls connections in an appropriate infusion system.|للتحكم في الاتصالات ضمن نظام تسريب مناسب.','Trace the line and read markings; do not guess flow direction. Unused ports require the approved closure. Manipulation can introduce air or contamination.|تتبّع الخط واقرأ العلامات ولا تخمّن اتجاه الجريان. تُغلق المنافذ غير المستخدمة بالطريقة المعتمدة. قد يسبب العبث دخول هواء أو تلوث.','Ports · handle · markings|منافذ · مقبض · علامات',['iv','ipc']);
add('kidney-dish','tools','Kidney dish|طبق كلوي','kidney-dish','A curved, kidney-shaped tray; reusable or disposable versions exist.|وعاء مقوّس بشكل الكلية، منه القابل لإعادة الاستخدام ومنه أحادي الاستخدام.','Holds suitable small items or collected material during a procedure.|لحمل أدوات صغيرة مناسبة أو مواد تجمع أثناء الإجراء.','A tray is not sterile simply because it is metal. Keep clean and contaminated workflows separate; it is not a sharps container.|لا يكون الوعاء معقمًا لمجرد أنه معدني. افصل النظيف عن الملوث؛ وهو ليس حاوية أدوات حادة.','Curved rim · basin|حافة مقوسة · حوض',['sterile','ipc']);
add('specimen-pot','tools','Specimen container|وعاء العينة','specimen-pot','A container chosen for a particular laboratory sample.|عبوة تختار بحسب نوع العينة المخبرية.','Contains and transports the correctly identified specimen.|لحفظ العينة الصحيحة التعريف ونقلها.','Check test, container and preservative requirements. Label according to policy at collection, never by bed number alone; use the correct transport packaging.|تحقق من الفحص والوعاء ومتطلبات المادة الحافظة. عرّف العينة وقت جمعها وفق السياسة، لا برقم السرير وحده؛ واستخدم تغليف النقل المناسب.','Lid · label area · container|غطاء · موضع الملصق · وعاء',['doc','ipc']);
add('urine-bag','tools','Urinary drainage bag|كيس تصريف البول','urine-bag','A graduated collection bag connected to the intended urinary drainage system.|كيس جمع مدرّج يتصل بنظام تصريف البول المقصود.','Collects urine and helps measure output over a recorded interval.|لجمع البول والمساعدة في قياس الخارج خلال فترة مسجلة.','Keep the bag below bladder level and off the floor; avoid kinks and unnecessary disconnections. A bag reading without a time interval is incomplete information.|يبقى أسفل مستوى المثانة وبعيدًا عن الأرض؛ وتُتجنب الالتواءات والفصل غير الضروري. القراءة دون فترة زمنية معلومة غير مكتملة.','Inlet tubing · graduated bag · outlet|أنبوب دخول · كيس مدرّج · مخرج',['cauti']);
add('urinary-catheter','tools','Indwelling urinary catheter|قسطرة بولية مستقرة','catheter','A tube draining the bladder; common designs include a retention balloon.|أنبوب يصرف المثانة؛ ومن أنواعه الشائعة ما يحتوي بالون تثبيت.','Used for an appropriate assessed indication, not simply for convenience.|يستخدم لداعٍ مناسب بعد التقييم، لا لمجرد تسهيل العمل.','Insertion and balloon handling require training and the correct product instructions. Review ongoing need, comfort and drainage; never pull against an inflated balloon.|يتطلب الإدخال والتعامل مع البالون تدريبًا وتعليمات المنتج. تُراجع الحاجة والراحة والتصريف؛ ولا تُسحب ضد بالون منتفخ.','Drainage lumen · balloon channel · connector|قناة تصريف · قناة بالون · وصلة',['cauti','device']);
add('feeding-tube','tools','Enteral feeding tube|أنبوب تغذية معوية','feeding-tube','A tube intended for delivery to the digestive tract, not a vein.|أنبوب مخصص للجهاز الهضمي وليس للوريد.','Provides prescribed enteral feeding, fluid or suitable medication via the approved route.|لإعطاء التغذية أو السوائل أو الدواء المناسب بالطريق المعوي المصرح.','Correct placement must be confirmed by the approved method before use. Do not use air-auscultation alone to confirm a nasogastric tube or connect enteral equipment to an IV line.|يجب التحقق من الموضع بالطريقة المعتمدة قبل الاستخدام. لا تعتمد على سماع الهواء وحده لتأكيد الأنبوب الأنفي المعدي، ولا توصله بخط وريدي.','Tube markings · enteral connector · fixation|علامات الأنبوب · وصلة معوية · تثبيت',['ngSafety']);
add('yankauer','tools','Yankauer suction tip|رأس شفط يانكاور','yankauer','A rigid suction tip usually recognised by its curved shape and enlarged end.|رأس شفط صلب، غالبًا مقوّس وذو نهاية متسعة.','Removes accessible oral secretions during appropriately supervised care.|لإزالة إفرازات فموية يمكن الوصول إليها أثناء العناية المناسبة.','It differs from a flexible suction catheter. Depth, suction and duration follow training and local policy; avoid traumatic or blind insertion.|يختلف عن قسطرة الشفط المرنة. يتبع العمق والضغط والمدة التدريب والسياسة؛ ويُتجنب الإدخال الرضّي أو الأعمى.','Tip · handle · suction connection|رأس · مقبض · وصلة شفط',['bec','device']);
add('haemostat','tools','Haemostatic forceps|ملقط مرقئ','clamp','A ring-handled instrument with a locking mechanism and jaws.|أداة بحلقات للأصابع وآلية قفل وفكّين.','Clamps appropriate tissue or material in a trained procedure.|يمسك أو يغلق نسيجًا أو مادة مناسبة ضمن إجراء مدرّب عليه.','Not a universal clamp for every tube: clamping the wrong line can cause harm. Tip shape, teeth and length vary.|ليس مشبكًا عامًا لكل أنبوب؛ فقد يضر إغلاق الخط الخطأ. تختلف الأطراف والأسنان والأطوال.','Finger rings · ratchet · jaws|حلقات · مسنن قفل · فكّان',['sterile']);
add('needle-holder','tools','Needle holder|ماسك إبرة الخياطة','needle-holder','A locking instrument with short, firm jaws designed for a suture needle.|أداة مقفلة ذات فكّين قصيرين متينين لإمساك إبرة الخياطة.','Controls a suture needle in a trained suturing procedure.|للتحكم بإبرة الخياطة أثناء إجراء مدرّب عليه.','It can resemble a haemostat but has a different working tip. Identify instruments before preparing a tray; sharps precautions still apply.|قد يشبه الملقط المرقئ لكن طرفه العامل مختلف. تعرّف إلى الأدوات قبل تجهيز الصينية؛ وتظل احتياطات الأدوات الحادة لازمة.','Short jaws · hinge · locking handles|فكّان قصيران · مفصل · مقبضان مقفلان',['sterile']);
add('wheelchair','mobility','Wheelchair|كرسي متحرك','wheelchair','A wheeled seat supporting mobility for an appropriately assessed person.|مقعد ذو عجلات يساعد شخصًا قُيّمت احتياجاته على الحركة.','Seated transport and independent or assisted movement.|للنقل جلوسًا والحركة الذاتية أو بالمساعدة.','Match size and support to the person. For transfers follow the brake and footplate instructions; footplates are not steps to stand on.|يلائم المقاس والدعم احتياجات الشخص. اتبع تعليمات الفرامل ومسندي القدم أثناء الانتقال؛ فالمسندان ليسا درجتين للوقوف.','Brakes · seat · armrests · footplates|فرامل · مقعد · مسندا ذراع · مسندا قدم',['handling','movingHome']);
add('stretcher','mobility','Stretcher / trolley|نقالة بعجلات','stretcher','A mobile surface for transporting a person lying down.|سطح متحرك لنقل الشخص مستلقيًا.','Transport between care areas with the assessed staff and equipment.|للنقل بين مناطق الرعاية بالفريق والتجهيزات المحددة بالتقييم.','Check capacity, securing arrangements, brakes, rails and route. Protect lines and drains; handing over equipment is part of handing over the patient.|افحص الحمولة ووسائل التأمين والفرامل والحواجز والمسار. احمِ الخطوط والمصارف؛ وتسليم التجهيزات جزء من تسليم المريض.','Mattress · rails · wheels · brakes|مرتبة · حواجز · عجلات · فرامل',['handlingRisk']);
add('slide-sheet','mobility','Slide sheet|ملاءة انزلاق','slide-sheet','A low-friction handling aid, sometimes used as a pair of layers.|وسيلة منخفضة الاحتكاك، وقد تستخدم بطبقتين.','Helps reposition a person without dragging skin across the bed.|تساعد على تغيير وضع الشخص دون جر جلده على السرير.','It is not a lifting sling. Use the assessed method and number of helpers; remove or retain only as the product and care plan specify.|ليست حمالة رفع. اتبع الطريقة وعدد المساعدين المحددين؛ وتُزال أو تترك فقط وفق تعليمات المنتج والخطة.','Low-friction layers · edge or handles by model|طبقات منخفضة الاحتكاك · حواف أو مقابض حسب النوع',['handling','handlingRCN']);
add('transfer-board','mobility','Transfer board|لوح انتقال','transfer-board','A rigid or semi-rigid bridge for a specified transfer task.|جسر صلب أو شبه صلب لمهمة انتقال محددة.','Assists selected lateral or seated transfers using an appropriate board type.|يساعد في انتقالات جانبية أو جلوسية مختارة بالنوع المناسب.','Seated and full-length lateral boards differ. Assess the gap, support surfaces, capacity and ability to assist; never improvise a bridge from furniture.|يختلف لوح الجلوس عن اللوح الجانبي الطويل. قيّم الفجوة والسطحين والحمولة وقدرة الشخص على المساعدة؛ ولا ترتجل جسرًا من الأثاث.','Board surface · ends · handholds if fitted|سطح اللوح · طرفان · فتحات إمساك إن وجدت',['handling','movingHome']);
add('patient-hoist','mobility','Patient hoist|رافعة المريض','hoist','A powered or manual lifting device used with compatible supports.|جهاز رفع كهربائي أو يدوي يعمل بوسائل دعم متوافقة.','Transfers a person when the assessment identifies a hoist as appropriate.|ينقل الشخص عندما يحدد التقييم ملاءمة الرافعة.','Training, weight limits and the approved sling combination are essential. Brake use differs by hoist; never assume all lifting equipment is operated alike.|يلزم التدريب وحدود الوزن وتوافق الحمالة المعتمد. تختلف تعليمات الفرامل؛ فلا تفترض تشابه تشغيل كل معدات الرفع.','Base · mast · boom · spreader bar · controls|قاعدة · عمود · ذراع · عارضة تعليق · تحكم',['lifting']);
add('patient-sling','mobility','Hoist sling|حمالة الرافعة','sling','A fabric support shaped for a particular patient, task and lift.|دعامة نسيجية مصممة لشخص ومهمة ورافعة محددة.','Supports the body during an assessed assisted transfer.|تدعم الجسم أثناء الانتقال بالمساعدة وفق التقييم.','No sling fits every hoist. Check approved compatibility, size, seams and attachment points; do not use a damaged sling.|لا تناسب الحمالة كل رافعة. تحقق من التوافق والمقاس والخياطة ونقاط التعليق؛ ولا تستخدم التالفة.','Body panel · leg supports · loops or clips|لوحة دعم الجسم · دعم الساقين · حلقات أو مشابك',['lifting']);
add('standing-aid','mobility','Standing transfer aid|وسيلة مساعدة على الوقوف','standing-aid','An aid for selected people who can participate in the required standing movement.|وسيلة لأشخاص مختارين يستطيعون المشاركة في حركة الوقوف المطلوبة.','Assists an assessed sit-to-stand or short transfer.|تساعد في النهوض من الجلوس أو الانتقال القصير بعد التقييم.','Not suitable for everyone unable to walk. Weight-bearing ability, cognition, symptoms and device criteria must be assessed before use.|لا تناسب كل من يتعذر عليه المشي. تُقيّم القدرة على تحمل الوزن والإدراك والأعراض وشروط الجهاز قبل الاستخدام.','Foot base · knee support · hand grips|قاعدة قدمين · دعم الركبتين · مقابض',['handlingRisk','handling']);
add('transfer-belt','mobility','Transfer / gait belt|حزام المساعدة على الانتقال','transfer-belt','A belt providing an approved handhold during selected assisted movement.|حزام يوفر موضع إمساك مناسبًا خلال حركات مختارة بالمساعدة.','Supports guidance and balance when individually indicated.|للمساعدة في التوجيه والتوازن عندما يناسب الشخص.','Not a lifting strap and not a restraint. Check suitability around wounds, tubes and abdominal conditions; do not hoist someone by the belt.|ليس حزام رفع ولا وسيلة تقييد. تحقق من الملاءمة مع الجروح والأنابيب وحالات البطن؛ ولا ترفع الشخص به.','Belt · buckle · designated grips|حزام · مشبك · مقابض مخصصة',['handlingRisk','handlingRCN']);
add('walking-frame','mobility','Walking frame|إطار مساعدة على المشي','walker','A frame that supplies additional support while walking.|إطار يوفر دعمًا إضافيًا أثناء المشي.','Helps an assessed person mobilise with the prescribed level of support.|يساعد الشخص بعد تقييمه على الحركة بمستوى الدعم المحدد.','Height, grip, ferrules or wheels must suit the person and task. A walking frame is not automatically a safe support to pull up from a chair.|يلائم الارتفاع والإمساك والأطراف أو العجلات الشخص والمهمة. ليس الإطار بالضرورة وسيلة آمنة للتعلق بها للنهوض من الكرسي.','Handles · frame · feet or wheels|مقابض · إطار · أرجل أو عجلات',['movingHome','handlingRisk']);
add('profiling-bed','mobility','Adjustable profiling bed|سرير قابل لتعديل الوضع والارتفاع','adjustable-bed','A bed with adjustable height and sections.|سرير يمكن تعديل ارتفاعه وأجزاء سطحه.','Supports positioning, comfort and safer access for care.|يساعد على تغيير الوضع والراحة والوصول الآمن أثناء العناية.','Keep controls and lines safe. Rails require individual assessment; they are not a universal fall-prevention solution and can create entrapment risk.|احمِ وحدات التحكم والخطوط. تحتاج الحواجز تقييمًا فرديًا؛ فهي ليست حلًا عامًا لمنع السقوط وقد تسبب خطر الانحشار.','Height control · backrest · knee section · brakes|تحكم الارتفاع · مسند ظهر · جزء الركبتين · فرامل',['handling','handlingRisk']);
