import {test} from 'node:test';import assert from 'node:assert/strict';import {fresh,transition as t,missing,checkpoint} from '../engine.mjs';
const run=(s,as)=>as.reduce((x,a)=>t(x,a),s);
function friction(s,omit=''){for(const area of Object.keys(s.areas)){if(area===omit)continue;for(let n=0;n<2;n++)s=t(s,'rub',{area,seconds:1});}return s;}
function wash(s=fresh()){s=run(s,['watch','water','warm','wet','soap']);s=friction(s);return run(s,['rinse','dry','faucet']);}
test('water → wet hands → soap: uninterrupted, no circular prerequisite',()=>{let s=run(fresh(),['water','wet','soap']);assert.ok(s.water&&s.wet&&s.soap);assert.equal(s.events.filter(e=>e.type==='sequence').length,0);});
test('normal full path to safe faucet completion',()=>{let s=wash();assert.ok(s.clean&&s.dry&&!s.water);});
test('soap before wet: supportive feedback, water/wet/soap remain available',()=>{let s=t(fresh(),'soap');assert.match(s.message,/wet/i);assert.equal(s.soap,false);s=run(s,['water','wet','soap']);assert.ok(s.soap);});
test('early drying: rinse remains available',()=>{let s=friction(run(fresh(),['water','wet','soap']));s=t(s,'dry');assert.match(s.message,/rinse/i);s=run(s,['rinse','dry']);assert.ok(s.dry&&s.clean);});
test('missed hand area: clean only it, retain prior work',()=>{let s=friction(run(fresh(),['water','wet','soap']),'left.fingertips');s=t(s,'rinse');assert.match(s.message,/left.fingertips/);let previous=s.areas['right.palms'];s=t(s,'rub',{area:'left.fingertips',seconds:1});assert.equal(s.areas['right.palms'],previous);s=t(s,'rinse');assert.ok(s.rinsed&&s.clean);});
test('recontamination: reset cleanliness, recover with new wash',()=>{let s=checkpoint('faucet');s=t(s,'faucet');assert.ok(!s.clean);assert.ok(s.events.some(e=>e.type==='contamination'));s=wash(s);assert.ok(s.clean);});
test('glove error freezes contact, retry only removal checkpoint',()=>{let s=checkpoint('removal');s=t(s,'removeFirst');s=t(s,'outer');assert.ok(s.freeze&&!s.clean);s=t(s,'retryRemoval');assert.ok(!s.freeze&&s.gloves===2&&s.dry);s=run(s,['removeFirst','removeSecond','bag','seal','dispose']);assert.ok(s.disposed);s=wash(s);assert.ok(s.complete);});
test('complete two-skill cycle and final handwash',()=>{let s=wash();s=run(s,['takeGlove','don','takeGlove','don','fit','care','removeFirst','removeSecond','bag','seal','dispose']);s=wash(s);assert.ok(s.complete);});
test('independent mode observes non-dangerous incorrect sequence',()=>{let s=t(fresh('independent'),'soap');assert.ok(s.soap);assert.ok(s.events.some(e=>e.type==='sequence'));s=t(s,'dry');assert.ok(s.dry);s=wash(s);assert.ok(s.clean);});
test('deterministic adversarial paths: every sampled handwashing state recovers',()=>{let seed=19;const rand=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const actions=['water','soap','wet','rinse','dry','faucet','towel','warm'];for(let i=0;i<300;i++){let s=fresh(i%2?'practice':'independent');for(let j=0;j<12;j++)s=t(s,actions[Math.floor(rand()*actions.length)]);s=wash(s);assert.ok(s.clean&&s.dry,`case ${i}`);}});
