let positionView='angled',comparison=false,paused=false;
let preview=P.map((_,i)=>safeSettings(i));
function mapping(i){const t=P[i];return `<div class="mapping"><span>${tr().notesRow}: <b>${t.notesNo??'—'}</b></span><span>${tr().checkRow}: <b>${t.checkNo??'—'}</b></span></div>`;}
function details(i,full=false){const t=P[i];return `${mapping(i)}${i===10?`<div class="shockFlag">${tr().sourceShock}</div>`:''}<div class="lessonGrid"><div><b>${tr().do}</b><ol>${t.steps.map(s=>`<li>${bi(s)}</li>`).join('')}</ol></div><div class="cue"><b>${t.hasRationale?tr().why:tr().noRationale}</b><p>${bi(t.why)}</p></div></div><div class="observe"><b>${tr().watch}</b><p>${bi(t.cue)}</p></div><div class="scopeNote"><b>${tr().extra}</b><p>${bi(t.extra)}</p><small>${cite(i)}</small></div>${full?`<details class="sourceLine"><summary>${tr().source}</summary><div>${t.sourceVariants.map(v=>`<b>${esc(v.file)} · ${v.entry}</b><blockquote dir="ltr" lang="en">${esc(v.text).replace(/\n/g,'<br>')}</blockquote>${v.rationale?`<b>${tr().sourceWhy}</b><blockquote dir="ltr" lang="en">${esc(v.rationale)}</blockquote>`:''}`).join('')}</div></details>`:''}`;}
function render(){comparison=false;if((mode==='train'||mode==='test')&&!testReview&&!record().gate){renderGate();return;}renderCore();if($('scene'))installSceneControls();if(mode==='guide'){const nav=document.createElement('div');nav.className='sourceMap';nav.innerHTML=`<details><summary>${tr().sourceMap}</summary><table><thead><tr><th>${tr().choose}</th><th>${tr().notesRow}</th><th>${tr().checkRow}</th></tr></thead><tbody>${P.map(t=>`<tr><td>${bi(t.title)}</td><td>${t.notesNo??'—'}</td><td>${t.checkNo??'—'}</td></tr>`).join('')}</tbody></table></details>`;$('content').prepend(nav);}if(mode==='test'&&testReview){$('content').insertAdjacentHTML('beforeend',`<div class="scopeNote">${tr().gateAttempts}: ${testing.reduce((n,r)=>n+r.gateAttempts,0)} · ${tr().stops}: ${testing.reduce((n,r)=>n+r.stops,0)}</div>`);}}
function renderGate(){shell();const r=record();$('content').innerHTML=`<section class="movementPanel"><h1>${bi(P[topic].title)}</h1><label>${tr().choose}<select id="gateTopic">${P.map((t,i)=>`<option value="${i}" ${i===topic?'selected':''}>${bi(t.title)}</option>`).join('')}</select></label>${mapping(topic)}<h2>${tr().safety}</h2><p>${tr().safetyIntro}</p>${paused?`<div class="feedback wrong">${tr().stopText}</div>`:''}<label class="option"><input id="assess" type="checkbox">${tr().assess}</label><label class="option"><input id="help" type="checkbox">${tr().help}</label><button id="ack" class="primary">${tr().ack}</button><p id="gateMessage" role="status"></p><button id="readGate" class="textButton">${tr().viewGuide}</button></section>`;$('gateTopic').onchange=e=>select(+e.target.value);$('ack').onclick=()=>{r.gateAttempts++;if(!$('assess').checked||!$('help').checked){$('gateMessage').textContent=tr().ackMissing;return;}r.gate=true;paused=false;render();};$('readGate').onclick=()=>openGuide(topic);}
function installSceneControls(){const wrap=$('scene').parentElement;
 wrap.insertAdjacentHTML('beforebegin',`${mapping(topic)}<div class="sceneTools"><div class="views">${['angled','profile','top'].map((v,i)=>`<button data-view="${v}" class="${positionView===v?'chosen':''}" aria-pressed="${positionView===v}">${tr().views[i]}</button>`).join('')}</div><div>${mode==='test'?'':`<button id="compare">${tr().compare}</button>`}<button id="stop" class="stopButton">${tr().stop}</button></div></div>`);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{positionView=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('chosen',x===b);x.setAttribute('aria-pressed',String(x===b));});draw();});
 $('stop').onclick=()=>{playing=false;lastInput=-999;drag=null;if(mode==='learn'){if(!$('stopMessage'))wrap.insertAdjacentHTML('afterend',`<p class="scopeNote" id="stopMessage" role="status">${tr().stopText}</p>`);}else{record().gate=false;record().ready=false;record().stops++;paused=true;render();}};
 if($('compare'))$('compare').onclick=()=>{if($('comparison')){$('comparison').remove();comparison=false;return;}comparison=true;const other=P[topic].compare;wrap.insertAdjacentHTML('afterend',`<section id="comparison"><p>${tr().compareNote}</p><div class="compareGrid"><div><h3>${bi(P[topic].title)}</h3><canvas id="compareA"></canvas></div><div><h3>${bi(P[other].title)}</h3><canvas id="compareB"></canvas></div></div><button id="closeComparison">${tr().closeCompare}</button></section>`);$('closeComparison').onclick=()=>{$('comparison').remove();comparison=false;};draw();};
 if(mode==='learn'){const cs=P[topic].controls.filter(c=>c.good.length>1);if(cs.length){wrap.insertAdjacentHTML('afterend',`<details class="previewControls"><summary>${tr().supportChoice}</summary><div>${cs.map(c=>`<label>${bi(c.label)}<select data-preview="${c.id}">${c.good.map(j=>`<option value="${j}" ${preview[topic][c.id]===j?'selected':''}>${bi(c.options[j])}</option>`).join('')}</select></label>`).join('')}</div></details>`);document.querySelectorAll('[data-preview]').forEach(e=>e.onchange=()=>{preview[topic][e.dataset.preview]=+e.value;draw();});}}
 draw();
}
function draw(){if(!$('scene'))return;window.drawPositioning($('scene'),topic,progress,mode==='learn'?preview[topic]:record().settings,{lang,view:positionView,hideLabels:mode==='test'});if($('comparison')){const j=P[topic].compare;window.drawPositioning($('compareA'),topic,1,safeSettings(topic),{lang,view:positionView});window.drawPositioning($('compareB'),j,1,safeSettings(j),{lang,view:positionView});}}
